export default function handler(req, res) {
  // 🔐 Allow all origins for testing — change to a specific domain in production
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "GET, OPTIONS");

  if (req.method === "OPTIONS") {
    return res.status(200).end(); // Respond to preflight requests
  }

  const { code } = req.query;

  const coupons = {
    Bhush: { name: "Bhushan", email: "bhushan@example.com" },
    SHARDULSIR2: { name: "Shardul Gangal", email: "shardul@indiraedu.com" },
    CHETANSIR2: { name: "Chetan Wakalkar", email: "cwakalkar@indiraedu.com" },
    MANISHSIR2: { name: "Manish Dalmia", email: "manish.dalmia@indiraedu.com" },
    2967: { name: "Manish Dalmia", email: "manish.dalmia@indiraedu.com", coupon: "MANISHDALMIA" },
    1705: { name: "Ravindra Sarje", email: "Director-admission@indiraedu.com", coupon: "RAVINDRASARJE" },
    3008: { name: "Priyashi Priya Yadav", email: "priyashi.yadav@indiraisbs.edu.in", coupon: "PRIYASHIPRIYAYADAV" },
    1817: { name: "Dr. Sachin Hapase", email: "sachin.hapase@indiraisbs.ac.in", coupon: "DRSACHINHAPASE" },
    2650: { name: "Sohel Javed Shaikh", email: "sohel.shaikh@indiraisbs.ac.in", coupon: "SOHELJAVEDSHAIKH" },
    2684: { name: "Abhinav Jha", email: "abhinav.jha@indiraiimp.edu.in", coupon: "ABHINAVJHA" },
    2634: { name: "Vishal Popat Pawar", email: "vishal.pawar@icacs.ac.in", coupon: "VISHALPOPATPAWAR" },
    2611: { name: "Avani Suresh Patel", email: "avani.patel@indiraiimp.edu.in", coupon: "AVANISURESHPATEL" },
    2577: { name: "Ms. Sweta Gour", email: "sweta.gour@indiraisbs.ac.in", coupon: "MSSWETAGOUR" },
    2683: { name: "Supriya Diwate", email: "supriya.diwate@indiraisbs.ac.in", coupon: "SUPRIYADIWATE" },
    2351: { name: "Nagalaxmi Erlapaty", email: "nagalaxmi.erlapaty@indiraisbs.ac.in", coupon: "NAGALAXMIERLAPATY" },
    2336: { name: "Neha Thakur", email: "neha.thakur@indiraisbs.ac.in", coupon: "NEHATHAKUR" },
    1757: { name: "Purva Yogesh Randive", email: "purva.randive@indiraisbs.ac.in", coupon: "PURVAYOGESHRANDIVE" },
    2084: { name: "Shital Pawar", email: "shital.pawar@indiraisbs.ac.in", coupon: "SHITALPAWAR" },
    2428: { name: "Sunita Barule", email: "sunita.barule@indiraisbs.ac.in", coupon: "SUNITABARULE" },
    2992: { name: "Shreyad Barai", email: "shreyad.barai@indiraisbs.ac.in", coupon: "SHREYADBARAI" },
    3022: { name: "Srushti Talwekar", email: "srushti.talwekar@iccs.ac.in", coupon: "SRUSHTITALWEKAR" },
    2994: { name: "Nitisha Ranit", email: "nitisha.ranit@iccs.ac.in", coupon: "NITISHARANIT" },
    3050: { name: "Meghal Gandhi", email: "meghal.gandhi@indiraiimp.edu.in", coupon: "MEGHALGANDHI" },
    2999: { name: "Shahin Tadvi", email: "shahin.tadvi@indiraiimp.edu.in", coupon: "SHAHINTADVI" },
    3043: { name: "Ragani Sonawane", email: "ragini.sonawane@indiraisbs.edu.in", coupon: "RAGANISONAWANE" },
    2857: { name: "Vaishnavi Bhagwat Godbole", email: "vaishnavi.godbole@icacs.ac.in", coupon: "VAISHNAVIBHAGWATGODBOL" },
    2991: { name: "Prajakta Telang", email: "prajakta.telang@indiraisbs.ac.in", coupon: "PRAJAKTATELANG" },
    2638: { name: "Trupti kakuste", email: "trupti.kakuste@indiraiimp.edu.in", coupon: "TRUPTIKAKUSTE" },
    2971: { name: "Tamanna Kalal", email: "tamannakalal@indiraicp.edu.in", coupon: "TAMANNAKALAL" },
    2679: { name: "Madhuri Pardeshi", email: "madhuri.pardeshi@indiraiimp.edu.in", coupon: "MADHURIPARDESHI" },
    2998: { name: "Prajwal Chauhan", email: "prajwal.chauhan@indiraiimp.edu.in", coupon: "PRAJWALCHAUHAN" },
    3030: { name: "Aarti Kamble", email: "Aarti.Kamble@indiraiimp.edu.in", coupon: "AARTIKAMBLE" },
    2913: { name: "Shashank Wani", email: "Shashank.wani@indiraicp.edu.in", coupon: "SHASHANKWANI" },
    1830: { name: "Kishor Gaikwad", email: "kishor.gaikwad@indiraisbs.ac.in", coupon: "KISHORGAIKWAD" },
    2716: { name: "Pankaj Bendale", email: "pankaj.bendale@indiraisbs.edu.in", coupon: "PANKAJBENDALE" },
    2386: { name: "Shubham Shahane", email: "shubham.shahane@icacs.ac.in", coupon: "SHUBHAMSHAHANE" },
    2360: { name: "Kavita Bhoite", email: "kavita@indiraedu.com", coupon: "KAVITABHOITE" },
    1959: { name: "Shubham Shingote", email: "shubham.shingote@indiraisc.edu.in", coupon: "SHUBHAMSHINGOTE" },
    2675: { name: "Vijaykumar Mali", email: "vijaykumar.mali@indiraisbs.edu.in", coupon: "VIJAYKUMARMALI" },
    2423: { name: "Yash Aryan", email: "yash.aryan@indiraedu.com", coupon: "YASHARYAN" },
    3031: { name: "Prerna Bhat", email: "prerna.bhat@indiraiimp.edu.in", coupon: "PRERNABHAT" },
    2997: { name: "Saumya Srivastava", email: "saumya.srivastava@indiraiimp.edu.in", coupon: "SAUMYASRIVASTAVA" },
    2264: { name: "Ishwar Malve", email: "ishwar.malve@indiraiimp.edu.in", coupon: "ISHWARMALVE" },
    2799: { name: "Rushikesh Jaju", email: "Rushikesh.jaju@indiraisbs.ac.in", coupon: "RUSHIKESHJAJU" },
    2439: { name: "Anand Ambekar", email: "anand.ambekar@indiraisc.edu.in", coupon: "ANANDAMBEKAR" },
    3011: { name: "Disha Ghai", email: "disha.ghai@indiraiimp.edu.in", coupon: "DISHAGHAI" },
    3010: { name: "Varun Soni", email: "varun.soni@indiraiimp.edu.in", coupon: "VARUNSONI" },
    INTERNNEHA: { name: "Neha Shekhavat", email: "neha24.shekhawat@gmail.com", coupon: "NEHASHEKHAVAT" },
    INTERNLAKSH: { name: "Laksh Dhanani", email: "lakshdhanani26@gmail.com", coupon: "LAKSHDHANANI" },
    2384: { name: "Vivek J", email: "vivek_j@indiraiimp.edu.in" },
    INTERNROHIT: { name: "Rohit Mane", email: "rohitsmane2029@gmail.com" },
    2553: { name: "Mrunalinee D", email: "mrunalinee.deshmukh@indiraisbs.ac.in" },
    2961: { name: "Mr. Rajive Bansal", email: "rajiv.bansal@indiraedu.com" },
    95: { name: "Dr Anagha Joshi", email: "vc@indirauniversity.edu.in" },
    2961: { name: "Dr. Rupa Hiremath", email: "rupa_hiremath@indiraedu.com" },
    2927: { name: "Ashwini Patwe", email: "ashwini.patve@indiraicp.edu.in" },
    2899: { name: "Suhas Koli", email: "suhas.koli@indiraisbs.edu.in" },
    2408: { name: "Anuja Babanrao Thube", email: "anuja.thube@icacs.ac.in" },
    2615: { name: "Mahendra Narke", email: "mknarke@gmail.com" },
    2724: { name: "Mitesh Kolhapure", email: "mitesh.kolhapure@icacs.ac.in" },
    2167: { name: "Nilesh Shrikantrao Khalikar", email: "nilesh.khalikar@icacs.ac.in" },
    2440: { name: "Punam Kavade", email: "punam.kavade@icacs.ac.in" },
    2156: { name: "Shobha Santosh Jagtap", email: "shobha.jagtap@icacs.ac.in" },
    2525: { name: "Swapnali Vayadande", email: "swapnali.vayadande@icacs.ac.in" },
    798: { name: "Vishal Parghale", email: "vishal.parghale@icacs.ac.in" },
    2074: { name: "Akaram Anna Tale", email: "akaram.tale@iccs.ac.in" },
    2914: { name: "Akash Kailas Gavhad", email: "akash.gavhad@iccs.ac.in" },
    1974: { name: "Amol Dattatraya Gaikwad", email: "amol.gaikwad90@iccs.ac.in" },
    2335: { name: "Anil Ramrao Kamlapure", email: "anil.kamlapure@iccs.ac.in" },
    83: { name: "Avinash Chandrakant Shingte", email: "avinash.shingate@iccs.ac.in" },
    568: { name: "Badshaha Gulab Nadaf", email: "nadaf@iccs.ac.in" },
    1716: { name: "Bharat Keshav Nagargoje", email: "bharat.nagargoje@iccs.ac.in" },
    1981: { name: "Dalnar Komal Shivajirao", email: "komal.dalnar@iccs.ac.in" },
    2431: { name: "Dattatraya Madhavrao Kulkarni", email: "dattatraya.kulkarni@iccs.ac.in" },
    1983: { name: "Divya Swapnil Chitre", email: "divya.chitre@iccs.ac.in" },
    333: { name: "Gouri Amol Vaidya", email: "vaidya.gouri@iccs.ac.in" },
    33: { name: "Janardan Adinath Pawar", email: "janardanp@iccs.ac.in" },
    712: { name: "Javed Masud Shaikh", email: "javed@iccs.ac.in" },
    341: { name: "Jyoti Narayan Shrote", email: "jyoti.shrote@iccs.ac.in" },
    2530: { name: "Jyoti Ramchandra Jadhav", email: "jyoti.jadhav@iccs.ac.in" },
    346: { name: "Kavita Yogesh Dhakad", email: "kavita.dhakad@iccs.ac.in" },
    1283: { name: "Madhavi Satish Avhankar", email: "madhavi.avhankar@iccs.ac.in" },
    90: { name: "Manisha Manish Patil", email: "manisha.patil@iccs.ac.in" },
    828: { name: "Marceline Fernandes", email: "marseline.fernandes@iccs.ac.in" },
    219: { name: "Nalanda Dyneshwar Wani", email: "nalanda.wani@iccs.ac.in" },
    2276: { name: "Nidhi Menaria", email: "nidhi.menaria@iccs.ac.in" },
    1433: { name: "Ninad Narayan Thorat", email: "ninad.thorat@iccs.ac.in" },
    570: { name: "Pashankar Shital S", email: "shital.pashankar@iccs.ac.in" },
    2672: { name: "Patil Sejal Deepak", email: "sejal.patil@iccs.ac.in" },
    1566: { name: "Prajwal Vitthal Bhalsing", email: "prajwal.bhalsing@iccs.ac.in" },
    1447: { name: "Pramod Ramesh Gholap", email: "pramod.gholap@iccs.ac.in" },
    86: { name: "Pravin Shantaram Mate", email: "pravin.mate@iccs.ac.in" },
    1717: { name: "Rajesh Navnath Bansode", email: "rajesh.bansode@iccs.ac.in" },
    1674: { name: "Rajminar Devidas Navgire", email: "rajminar.navgire@iccs.ac.in" },
    1742: { name: "Raju Babu Jagtap", email: "raju.jagtap@iccs.ac.in" },
    1567: { name: "Ramdas Sanjay Bolage", email: "ramdas.bolage@iccs.ac.in" },
    1672: { name: "Ranjeet Dattatray More", email: "ranjeet.more@iccs.ac.in" },
    1986: { name: "Rupali Jalindar Zaware", email: "jadhav.rupali@iccs.ac.in" },
    2713: { name: "Sagar Babasaheb Kharade", email: "sagar.kharade@iccs.ac.in" },
    229: { name: "Sarika Yogesh Thakare", email: "sarika.thakare@iccs.ac.in" },
    118: { name: "Sarita Mareppa Byagar", email: "sarita.byagar@iccs.ac.in" },
    2295: { name: "Shambhu Anil Mahadik", email: "shambhu.mahadik@iccs.ac.in" },
    2180: { name: "Shubhangi Deepak Gore", email: "shubhangi.gore@iccs.ac.in" },
    1964: { name: "Shubhangi Sanjay Chavan", email: "shubhangi.chavan@iccs.ac.in" },
    1982: { name: "Soman Vikrant Sanjay", email: "vikrant.soman@iccs.ac.in" },
    2053: { name: "Sonali Pramod Patil (Bujbal)", email: "sonali.bhujbal@iccs.ac.in" },
    1204: { name: "Sumit Subhash Sasane", email: "Sumit.sasane@iccs.ac.in" },
    78: { name: "Sunita Tukaram Gawade", email: "sunita.gawade@iccs.ac.in" },
    1707: { name: "Suwarna Suresh Kedari", email: "kedari.suwarna@iccs.ac.in" },
    532: { name: "Tejashri Anil Phalke", email: "tejashriphalle@iccs.ac.in" },
    719: { name: "Thomson Varghese", email: "thomson.varghese@iccs.ac.in" },
    1970: { name: "Valmik Kashinath Dhanwate", email: "valmik.dhanwate@iccs.ac.in" },
    2933: { name: "Vede Amit Ankush", email: "amit.vede@iccs.ac.in" },
    335: { name: "Vijay Daulatrao More", email: "vijay.more@iccs.ac.in" },
    235: { name: "Vishal Pramod Verma", email: "vishal.verma@iccs.ac.in" },
    2127: { name: "Vividha Bahety", email: "vividha.bahety@iccs.ac.in" },
    1978: { name: "Yewale Sharmila B", email: "sharmila.yewale@iccs.ac.in" },
    1318: { name: "Yogesh Shamrao Bhusari", email: "yogesh.bhusari@iccs.ac.in" },
    316: { name: "Abhijit Chandratreya", email: "abhijitc@indiraiimp.edu.in" },
    1621: { name: "Anil Parkhe", email: "anil.parkhe@indiraiimp.edu.in" },
    2271: { name: "Ashish Marne", email: "ashish.marne@indiraiimp.edu.in" },
    2150: { name: "Ashutosh Kulkarni", email: "ashutosh.kulkarni@indiraiimp.edu.in" },
    103: { name: "Dinkar Kamble", email: "dinkar.kamble@indiraiimp.edu.in" },
    744: { name: "Dipanjay Jayant Bhalerao", email: "dipanjay.bhalerao@indiraiimp.edu.in" },
    2082: { name: "Sakshi Mann", email: "sakshi.mann@indiraiimp.edu.in" },
    310: { name: "Gopal Nandurkar", email: "gopal.nandurkar@indiraiimp.edu.in" },
    1513: { name: "Jyoti Gore", email: "jyoti.gore@indiraiimp.edu.in" },
    902: { name: "Kailas Mhetre", email: "kailas.mhetre@indiraiimp.edu.in" },
    95: { name: "Kailash Pawar", email: "kailas_p@indiraiimp.edu.in" },
    29: { name: "Khandu Inamke", email: "khandu.inamke@indiraiimp.edu.in" },
    2243: { name: "Kirti Vasudeo", email: "kirti.vasudeo@indiraiimp.edu.in" },
    2260: { name: "Laxman Narute", email: "laxman.narute@indiraiimp.edu.in" },
    318: { name: "Manasi Patil", email: "manasi.pawar@indiraiimp.edu.in" },
    85: { name: "Girish Parekh", email: "girishparekh@indiraedu.com" },
    1239: { name: "Neha Ramteke", email: "neha.ramteke@indiraiimp.edu.in" },
    1905: { name: "Nitin Joshi", email: "nitin.joshi@indiraiimp.edu.in" },
    2220: { name: "Priti Kulkarni", email: "priti.kulkarni@indiraiimp.edu.in" },
    429: { name: "Punam Bhoyar", email: "punam.bhoyar@indiraiimp.edu.in" },
    109: { name: "Purvi Shah", email: "purvi.shah@indiraiimp.edu.in" },
    1745: { name: "Rahul Pande", email: "rahul.pande@indiraedu.com" },
    1679: { name: "Ravi Baijulal Bhandari", email: "ravi.bhandari@indiraiimp.edu.in" },
    733: { name: "Rita Dangre", email: "rita.dangre@indiraedu.com" },
    205: { name: "Sachin Ramchandra Kamble", email: "sachin@indiraedu.com" },
    294: { name: "Sagar Kamble", email: "sagar.kamble@indiraiimp.edu.in" },
    2064: { name: "Sanchit Bhauso Pansare", email: "sanchit.pansare@indiraiimp.edu.in" },
    39: { name: "Sandeep Gunjal", email: "sandeep.gunjal@indiraiimp.edu.in" },
    1358: { name: "Sanjay Bhale", email: "sanjay.bhale@indiraiimp.edu.in" },
    1338: { name: "Shashikant Bade", email: "shashikant.bade@indiraiimp.edu.in" },
    13: { name: "Subhash Gaikwad", email: "subhash.gaikwad@indiraiimp.edu.in" },
    1650: { name: "Sumit Omprakash Sharma", email: "sumit.sharma@indiraedu.com" },
    2357: { name: "Sunil Maske", email: "sunil.maske@indiraiimp.edu.in" },
    2358: { name: "Swapnali Amol Kulkarni", email: "swapnali.kulkarni@indiraiimp.edu.in" },
    2833: { name: "Swati Patil", email: "swati.patil@indiraiimp.edu.in" },
    1797: { name: "Tushar Patil", email: "tushar.patil@indiraiimp.edu.in" },
    88: { name: "Yestrela Evangelist Vaz", email: "yestrela.vaz@indiraiimp.edu.in" },
    1880: { name: "Renu Darshan Garg", email: "renu.garg@indiraisc.edu.in" },
    2590: { name: "Alisha Mukhopadhayay", email: "alisha.mukhopadhayay@indiraiimp.edu.in" },
    1862: { name: "Anjali P Kalkar", email: "anjali.kalkar@indiraiimp.edu.in" },
    2429: { name: "Manoj Hemant Tapaswi", email: "manoj.tapaswi@indiraiimp.edu.in" },
    2176: { name: "P S Deepa", email: "deepa.sakthi@indiraiimp.edu.in" },
    2027: { name: "Patil Sudhir Jijabrao", email: "prof.sudhir.patil@indiraiimp.edu.in" },
    2034: { name: "Sachin Shankar Hadapad", email: "sachin.hadpad@indiraiimp.edu.in" },
    2141: { name: "Santoshkumar Tatyaram Kadam", email: "santoshkumar.kadam@indiraiimp.edu.in" },
    2613: { name: "Sarika Ravindranath Sagar", email: "sarika.sagar@indiraiimp.edu.in" },
    1960: { name: "Sonali Suresh Shrotri", email: "sonali.shrotri@indiraiimp.edu.in" },
    1922: { name: "Swapnil Dattatray Kharde", email: "swapnil.kharde@indiraiimp.edu.in" },
    2340: { name: "Torsha Ghosh", email: "torsha.ghosh@indiraiimp.edu.in" },
    2028: { name: "Vijayalakshmi Ganganna Nemmaniwar", email: "dr.vijayalaxmi@indiraiimp.edu.in" },
    1254: { name: "Akshay Ranjan Pawar", email: "akshay.pawar@indiraicp.edu.in" },
    1472: { name: "Amruta Prasann Walvekar", email: "amruta.walvekar@indiraicp.edu.in" },
    405: { name: "Anil Rama Gaikwad", email: "anil.gaikwad@indiraicp.edu.in" },
    2806: { name: "Anirudha Vasant Munde", email: "anirudha.munde@indiraicp.edu.in" },
    2258: { name: "Ashutosh Narayan Misal", email: "ashutosh.misal@indiraiimp.edu.in" },
    2817: { name: "Ashwini Chitrangad Kotkar", email: "ashwini.kotkar@indiraicp.edu.in" },
    354: { name: "Dayanand Mukund Kannur", email: "dayanand.kannur@indiraicp edu.in" },
    1813: { name: "Digambar Balkrishna Ambikar", email: "digambar.ambikar@indiraicp.edu.in" },
    32: { name: "Dilip Maruti Dhamale", email: "dilipdhamale@indiraicp.edu.in" },
    2803: { name: "Divya Ashok Kulkarni", email: "divya.kulkarni@indiraicp.edu.in" },
    446: { name: "Manasi Jayant Wagdarikar", email: "mansi.wagdarikar@indiraicp.edu.in" },
    153: { name: "Manohar Vitthal Jadhav", email: "manohar.jadhav@indiraicp.edu.in" },
    1577: { name: "Meghna Mandar Dabhadkar", email: "meghna.dabhadkar@indiraicp.edu.in" },
    1509: { name: "Pallavi Yogendra Singh Chouhan", email: "pallavi.chouhan@indiraicp.edu.in" },
    1388: { name: "Pradnya Parag Kulkarni", email: "pradnya.kulkarni@indiraicp.edu.in" },
    2805: { name: "Rajanigandha Rajendra Jori", email: "rajanigandha.jori@indiraicp.edu.in" },
    723: { name: "Ramling Arjun Gaikwad", email: "Ramling.gaikwad@indiraicp.edu.in" },
    2524: { name: "Rutuja Saurabh Lokhande", email: "rutuja.lokhande@indiraicp.edu.in" },
    224: { name: "Samadhan Prabhakar Gaikwad", email: "samadhan.gaikwad@indiraicp.edu.in" },
    2824: { name: "Sharmishtha Anurag Singh", email: "sharmishthasingh@indiraicp.edu.in" },
    1474: { name: "Shraddha Prakash Devarshi", email: "shraddha.devarshi@indiraicp.edu.in" },
    1699: { name: "Shubham Vijay Pawar", email: "shubham.pawar@indiraicp.edu.in" },
    2812: { name: "Sneha Anil Pachore", email: "sneha.pachore@indiraicp.edu.in" },
    2814: { name: "Sneha Ganesh Nawkar", email: "sneha.nawkar@indiraicp.edu.in" },
    1712: { name: "Sneha Vishwas Joshi", email: "sneha.joshi@indiraicp.edu.in" },
    2099: { name: "Snehali Pandurang Saykar", email: "snehali.saykar@indiraicp.edu.in" },
    1470: { name: "Swapnil Vilas Dhamale", email: "swapnil.dhamale@indiraicp.edu.in" },
    1870: { name: "Abhijit Prabhakar Bobde", email: "abhijit.bobde@indiraisbs.ac.in" },
    2703: { name: "Anita Sanjay Mathapati", email: "anita.mathapati@indiraisbs.edu.in" },
    2041: { name: "Bibeesh Kannan P.V.", email: "bibeesh.p@indiraisbsmba.edu.in" },
    2158: { name: "Dhanashri Swapnil Deshpande", email: "dhanashri.deshpande@indiraisbs.edu.in" },
    34: { name: "Haridas Ashok Deshmukh", email: "harish.deshmukh@indiraiimp.ac.in" },
    2153: { name: "Harshal Suresh Gajbhe", email: "harshal.gajbhe@indiraisbsmba.edu.in" },
    1623: { name: "Kalpana Kamalakar Deshmukh", email: "kalpana.deshmukh@indiraisbs.ac.in" },
    1334: { name: "Laxman Navnath Misal", email: "laxman.misal@indiraisbs.ac.in" },
    1869: { name: "Mrityunjay Kameshwar Lal Kumar", email: "mrityunjay.Kumar@indiraisbs.ac.in" },
    2838: { name: "Mrunalini Saheb Khandare", email: "mrunalini.khandare@indiraisbs.edu.in" },
    2893: { name: "Poonam Nitin Satpute", email: "poonam.satpute@indiraisbs.edu.in" },
    2823: { name: "Pravin Dnyandev Dolas", email: "pravin.dolas@indiraisbs.edu.in" },
    2087: { name: "Rajneesh Madanlal Bali", email: "rajneesh.bali@indiraedu.com" },
    132: { name: "Sangita Shahu Devare", email: "sangeeta.devare@indiraisbs.ac.in" },
    2493: { name: "Sanjay Kapoorchand Asati", email: "sanjay.asati@indiraisbs.edu.in" },
    1606: { name: "Subhash Tukaram Ghogare", email: "subhash.ghogare@indiraisbs.ac.in" },
    2478: { name: "Sushil Dashrath Shende", email: "sushil.shende@indiraisbs.edu.in" },
    1237: { name: "Tanaji Gopal Durgade", email: "tanaji.durgade@indiraisbs.ac.in" },
    2666: { name: "Tilak Kisan Nugurwar", email: "tilak.nugurwar@indiraedu.com" },
    2836: { name: "Vaibhavi Shashikant Shahane", email: "vaibhavi.shahane@indiraisbs.edu.in" },
    2908: { name: "Yogesh Sunil Pansare", email: "yogesh.pansare@indiraisbs.edu.in" },
    1307: { name: "Amruta Deshpande", email: "amruta.deshpande@indiraisbs.ac.in" },
    1671: { name: "Anagha Bhope", email: "anagha1.bhope@indiraisbs.ac.in" },
    1654: { name: "Anil Chalke", email: "anil.chalke@indiraisbs.ac.in" },
    2653: { name: "Anna Philips", email: "anna.philips@indiraisbs.ac.in" },
    133: { name: "Arun Padale", email: "arun.padale@indiraiscs.ac.in" },
    2399: { name: "Bharti Shukla", email: "bharti.shukla@indiraisbs.ac.in" },
    1575: { name: "Chetan Parange", email: "chetan.parange@indiraisbs.ac.in" },
    1635: { name: "Dipesh Kawale", email: "dipesh.kawale@indiraisbs.ac.in" },
    1541: { name: "Gaganpreet Ahluwalia", email: "gaganpreet.ahluwalia@indiraisbs.ac.in" },
    2270: { name: "Jaya Saxena", email: "jaya.saxena@indiraisbs.ac.in" },
    1957: { name: "Jayanthi Kumbhar", email: "jayanti.kumbhar@indiraisbs.ac.in" },
    1616: { name: "Jitendra Patil", email: "jitendra.patil@indiraisbs.ac.in" },
    2686: { name: "Kishan Giri", email: "kishan.giri@indiraisbs.ac.in" },
    1952: { name: "Kumendra Raheja", email: "kumendrar@indiraisbs.ac.in" },
    2380: { name: "Madan Khandekar", email: "madan.khandekar@indiraedu.com" },
    762: { name: "Mahesh Mangaonkar", email: "mahesh.mangaonkar@indiraisbs.ac.in" },
    1951: { name: "Mahesh Pol", email: "mahesh.pol@indiraisbs.ac.in" },
    5441: { name: "Maruti Uttekar", email: "maruti.utterkar@indiranationalschool.ac.in" },
    2221: { name: "Mayuresh Naregalkar", email: "mayuresh.naregalkar@indiraisbs.ac.in" },
    1855: { name: "Meghasham Chaudhari", email: "meghasham.chaudhari@indiraisbs.ac.in" },
    2241: { name: "Mohan Rathod", email: "mohan.rathod@indiraisbs.ac.in" },
    1399: { name: "Neetal Vyas", email: "neetal.vyas@indiraisbs.ac.in" },
    1899: { name: "Padmashree Chandak", email: "padmashree.chandak@indiraisbs.ac.in" },
    2029: { name: "Piyush Dixit", email: "piyush.dixit@indiraisbs.ac.in" },
    569: { name: "Pradip Patil", email: "pradip.patil@indiraisbs.ac.in" },
    1595: { name: "Pramod Shinde", email: "pramod.shinde@indiraicp.edu.in" },
    1279: { name: "Prashant Rege", email: "prashant.rege@indiraisbs.ac.in" },
    1182: { name: "Rajendra Vikhar", email: "rajendra.vikhar@indiraisbs.ac.in" },
    2245: { name: "Ravindra Shinde", email: "ravindra.shinde@indiraedu.com" },
    171: { name: "Sachin More", email: "sachin.more@indiraisbs.ac.in" },
    1357: { name: "Sadhana Ingle", email: "sadhana.ingle@indiraisbs.edu.in" },
    59: { name: "Sahebrao Patil", email: "sahebrao.patil@indiraisbs.ac.in" },
    2702: { name: "Sajid Shaikh", email: "sajid.shaikh@indiraisbs.ac.in" },
    508: { name: "Sameer Sheshgir", email: "samir.sheshgir@indiraicp.edu.in" },
    1536: { name: "Sanjay Muthal", email: "sanjay.muthal@indiraisbs.ac.in" },
    1538: { name: "Sanjay Rathod", email: "sanjay.rathod@indiraisbs.ac.in" },
    2521: { name: "Sarita Agarwal", email: "sarita.agarwal@indiraisbs.ac.in" },
    1050: { name: "Shikha Sindhu", email: "shikha.sindhu@indiraisbs.ac.in" },
    2720: { name: "Shweta Vyas", email: "shweta.vyas@indiraisbs.ac.in" },
    2395: { name: "Sumit Shinde", email: "sumit.shinde@indiraedu.com" },
    2078: { name: "Sushmitha Rao", email: "sushmitha.rao@indiraisbs.ac.in" },
    1214: { name: "Tausif Mistry", email: "tausif.mistry@indiraisbs.ac.in" },
    2718: { name: "Trupti Sharad Joshi", email: "padirector@indiraisbs.ac.in" },
    1729: { name: "Umesh Jagdale", email: "umesh.jagdale@indiraisbs.edu.in" },
    2721: { name: "Varsha Nagpure", email: "varsha.murhe@indiraisbs.ac.in" },
    26: { name: "Vinay Khawale", email: "vinayk@indiraedu.com" },
    2415: { name: "Yamini Ghanghorkar", email: "yamini.ghanghorkar@indiraisbs.ac.in" },
    3012: { name: "Karun Kumar Chaugule", email: "karunkumar.chaugule@indiraiimp.edu.in" },
    3027: { name: "Bharti Khaire", email: "bharti.khaire@indiraiimp.edu.in" },
    3021: { name: "Sunil Kashinath Sakhare", email: "sunil.sakhare@indiraedu.com" },
    3034: { name: "Kadambari Vishnu Suryawanshi", email: "Kadambari.Suryawanshi@indiraiimp.edu.in" },
    3048: { name: "Kavita Mathad", email: "dean.sob@indirauniversity.edu.in" },
    3037: { name: "Prakash Vishnu Khadse", email: "prakash.khadse@indiraedu.com" },
    2789: { name: "Shashwat Doshetti", email: "shashwat.doshetti@indiraigsb.edu.in" },

  };

  if (coupons[code]) {
    return res.status(200).json({
      success: true,
      name: coupons[code].name,
      email: coupons[code].email,
    });
  } else {
    return res.status(404).json({
      success: false,
      message: "Invalid or expired coupon code",
    });
  }
}
