export default function handler(req, res) {
  // 🔐 Allow all origins for testing — change to a specific domain in production
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "GET, OPTIONS");

  if (req.method === "OPTIONS") {
    return res.status(200).end(); // Respond to preflight requests
  }

  const { code } = req.query;

  const coupons = {
    SHARDULSIR2: { name: "Shardul Gangal", email: "shardul@indiraedu.com" },
    CHETANSIR2: { name: "Chetan Wakalkar", email: "cwakalkar@indiraedu.com" },
    MANISHSIR2: { name: "Manish Dalmia", email: "manish.dalmia@indiraedu.com" },
    2967: { name: "Manish Dalmia", email: "manish.dalmia@indiraedu.com", coupon: "MANISHDALMIA" },
    1705: { name: "Ravindra Sarje", email: "Director-admission@indiraedu.com", coupon: "RAVINDRASARJE" },
    3008: { name: "Priyashi Priya Yadav", email: "priyashi.yadav@indiraisbs.edu.in", coupon: "PRIYASHIPRIYAYADAV" },
    1817: { name: "Dr. Sachin Hapase", email: "sachin.hapase@indiraisbs.ac.in", coupon: "DRSACHINHAPASE" },
    2650: { name: "Sohel Javed Shaikh", email: "sohel.shaikh@indiraisbs.ac.in", coupon: "SOHELJAVEDSHAIKH" },
    2684: { name: "Abhinav Jha", email: "abhinav.jha@indiraiimp.edu.in", coupon: "ABHINAVJHA" },
    2634: { name: "Vishal Popat Pawar", email: "vishal.pawar@icacs.ac.in", coupon: "VISHALPOPATPAWAR" },
    2611: { name: "Avani Suresh Patel", email: "avani.patel@indiraiimp.edu.in", coupon: "AVANISURESHPATEL" },
    2577: { name: "Ms. Sweta Gour", email: "sweta.gour@indiraisbs.ac.in", coupon: "MSSWETAGOUR" },
    2683: { name: "Supriya Diwate", email: "supriya.diwate@indiraisbs.ac.in", coupon: "SUPRIYADIWATE" },
    2351: { name: "Nagalaxmi Erlapaty", email: "nagalaxmi.erlapaty@indiraisbs.ac.in", coupon: "NAGALAXMIERLAPATY" },
    2336: { name: "Neha Thakur", email: "neha.thakur@indiraisbs.ac.in", coupon: "NEHATHAKUR" },
    1757: { name: "Purva Yogesh Randive", email: "purva.randive@indiraisbs.ac.in", coupon: "PURVAYOGESHRANDIVE" },
    2084: { name: "Shital Pawar", email: "shital.pawar@indiraisbs.ac.in", coupon: "SHITALPAWAR" },
    2428: { name: "Sunita Barule", email: "sunita.barule@indiraisbs.ac.in", coupon: "SUNITABARULE" },
    2992: { name: "Shreyad Barai", email: "shreyad.barai@indiraisbs.ac.in", coupon: "SHREYADBARAI" },
    3022: { name: "Srushti Talwekar", email: "srushti.talwekar@iccs.ac.in", coupon: "SRUSHTITALWEKAR" },
    2994: { name: "Nitisha Ranit", email: "nitisha.ranit@iccs.ac.in", coupon: "NITISHARANIT" },
    96: { name: "Dr Anagh Joshi", email: "vc@indirauniversity.edu.in", coupon: "96" },
    3050: { name: "Meghal Gandhi", email: "meghal.gandhi@indiraiimp.edu.in", coupon: "MEGHALGANDHI" },
    2999: { name: "Shahin Tadvi", email: "shahin.tadvi@indiraiimp.edu.in", coupon: "SHAHINTADVI" },
    3043: { name: "Ragani Sonawane", email: "ragini.sonawane@indiraisbs.edu.in", coupon: "RAGANISONAWANE" },
    2857: { name: "Vaishnavi Bhagwat Godbole", email: "vaishnavi.godbole@icacs.ac.in", coupon: "VAISHNAVIBHAGWATGODBOL" },
    2991: { name: "Prajakta Telang", email: "prajakta.telang@indiraisbs.ac.in", coupon: "PRAJAKTATELANG" },
    2638: { name: "Trupti kakuste", email: "trupti.kakuste@indiraiimp.edu.in", coupon: "TRUPTIKAKUSTE" },
    2971: { name: "Tamanna Kalal", email: "tamannakalal@indiraicp.edu.in", coupon: "TAMANNAKALAL" },
    2679: { name: "Madhuri Pardeshi", email: "madhuri.pardeshi@indiraiimp.edu.in", coupon: "MADHURIPARDESHI" },
    2998: { name: "Prajwal Chauhan", email: "prajwal.chauhan@indiraiimp.edu.in", coupon: "PRAJWALCHAUHAN" },
    3030: { name: "Aarti Kamble", email: "Aarti.Kamble@indiraiimp.edu.in", coupon: "AARTIKAMBLE" },
    2913: { name: "Shashank Wani", email: "Shashank.wani@indiraicp.edu.in", coupon: "SHASHANKWANI" },
    1830: { name: "Kishor Gaikwad", email: "kishor.gaikwad@indiraisbs.ac.in", coupon: "KISHORGAIKWAD" },
    2716: { name: "Pankaj Bendale", email: "pankaj.bendale@indiraisbs.edu.in", coupon: "PANKAJBENDALE" },
    2386: { name: "Shubham Shahane", email: "shubham.shahane@icacs.ac.in", coupon: "SHUBHAMSHAHANE" },
    2360: { name: "Kavita Bhoite", email: "kavita@indiraedu.com", coupon: "KAVITABHOITE" },
    1959: { name: "Shubham Shingote", email: "shubham.shingote@indiraisc.edu.in", coupon: "SHUBHAMSHINGOTE" },
    2675: { name: "Vijaykumar Mali", email: "vijaykumar.mali@indiraisbs.edu.in", coupon: "VIJAYKUMARMALI" },
    2423: { name: "Yash Aryan", email: "yash.aryan@indiraedu.com", coupon: "YASHARYAN" },
    3031: { name: "Prerna Bhat", email: "prerna.bhat@indiraiimp.edu.in", coupon: "PRERNABHAT" },
    2997: { name: "Saumya Srivastava", email: "saumya.srivastava@indiraiimp.edu.in", coupon: "SAUMYASRIVASTAVA" },
    2264: { name: "Ishwar Malve", email: "ishwar.malve@indiraiimp.edu.in", coupon: "ISHWARMALVE" },
    2799: { name: "Rushikesh Jaju", email: "Rushikesh.jaju@indiraisbs.ac.in", coupon: "RUSHIKESHJAJU" },
    2439: { name: "Anand Ambekar", email: "anand.ambekar@indiraisc.edu.in", coupon: "ANANDAMBEKAR" },
    3011: { name: "Disha Ghai", email: "disha.ghai@indiraiimp.edu.in", coupon: "DISHAGHAI" },
    3010: { name: "Varun Soni", email: "varun.soni@indiraiimp.edu.in", coupon: "VARUNSONI" },
    INTERNNEHA: { name: "Neha Shekhavat", email: "neha24.shekhawat@gmail.com", coupon: "NEHASHEKHAVAT" },
    INTERNLAKSH: { name: "Laksh Dhanani", email: "lakshdhanani26@gmail.com", coupon: "LAKSHDHANANI" },
    2384: { name: "Vivek J", email: "vivek_j@indiraiimp.edu.in" },
    INTERNROHIT: { name: "Rohit Mane", email: "rohitsmane2029@gmail.com" },
    2553: { name: "Mrunalinee D", email: "mrunalinee.deshmukh@indiraisbs.ac.in" },
    2961: { name: "Mr. Rajive Bansal", email: "rajiv.bansal@indiraedu.com" },
    95: { name: "Dr Anagha Joshi", email: "vc@indirauniversity.edu.in" },
    2961: { name: "Dr. Rupa Hiremath", email: "rupa_hiremath@indiraedu.com" },
    2927: { name: "Ashwini Patwe", email: "ashwini.patve@indiraicp.edu.in" },
    2899: { name: "Suhas Koli", email: "suhas.koli@indiraisbs.edu.in" },
    //IGI
    2408: { name: "Anuja Babanrao Thube", email: "anuja.thube@icacs.ac.in" },
    2615: { name: "Mahendra Narke", email: "mknarke@gmail.com" },
    2724: { name: "Mitesh Kolhapure", email: "mitesh.kolhapure@icacs.ac.in" },
    2167: { name: "Nilesh Shrikantrao Khalikar", email: "nilesh.khalikar@icacs.ac.in" },
    2440: { name: "Punam Kavade", email: "punam.kavade@icacs.ac.in" },
    2156: { name: "Shobha Santosh Jagtap", email: "shobha.jagtap@icacs.ac.in" },
    2525: { name: "Swapnali Vayadande", email: "swapnali.vayadande@icacs.ac.in" },
    798: { name: "Vishal Parghale", email: "vishal.parghale@icacs.ac.in" },
    2074: { name: "Akaram Anna Tale", email: "akaram.tale@iccs.ac.in" },
    2914: { name: "Akash Kailas Gavhad", email: "akash.gavhad@iccs.ac.in" },
    1974: { name: "Amol Dattatraya Gaikwad", email: "amol.gaikwad90@iccs.ac.in" },
    2335: { name: "Anil Ramrao Kamlapure", email: "anil.kamlapure@iccs.ac.in" },
    83: { name: "Avinash Chandrakant Shingte", email: "avinash.shingate@iccs.ac.in" },
    568: { name: "Badshaha Gulab Nadaf", email: "nadaf@iccs.ac.in" },
    1716: { name: "Bharat Keshav Nagargoje", email: "bharat.nagargoje@iccs.ac.in" },
    1981: { name: "Dalnar Komal Shivajirao", email: "komal.dalnar@iccs.ac.in" },
    2431: { name: "Dattatraya Madhavrao Kulkarni", email: "dattatraya.kulkarni@iccs.ac.in" },
    1983: { name: "Divya Swapnil Chitre", email: "divya.chitre@iccs.ac.in" },
    333: { name: "Gouri Amol Vaidya", email: "vaidya.gouri@iccs.ac.in" },
    33: { name: "Janardan Adinath Pawar", email: "janardanp@iccs.ac.in" },
    712: { name: "Javed Masud Shaikh", email: "javed@iccs.ac.in" },
    341: { name: "Jyoti Narayan Shrote", email: "jyoti.shrote@iccs.ac.in" },
    2530: { name: "Jyoti Ramchandra Jadhav", email: "jyoti.jadhav@iccs.ac.in" },
    346: { name: "Kavita Yogesh Dhakad", email: "kavita.dhakad@iccs.ac.in" },
    1283: { name: "Madhavi Satish Avhankar", email: "madhavi.avhankar@iccs.ac.in" },
    90: { name: "Manisha Manish Patil", email: "manisha.patil@iccs.ac.in" },
    828: { name: "Marceline Fernandes", email: "marseline.fernandes@iccs.ac.in" },
    219: { name: "Nalanda Dyneshwar Wani", email: "nalanda.wani@iccs.ac.in" },
    2276: { name: "Nidhi Menaria", email: "nidhi.menaria@iccs.ac.in" },
    1433: { name: "Ninad Narayan Thorat", email: "ninad.thorat@iccs.ac.in" },
    570: { name: "Pashankar Shital S", email: "shital.pashankar@iccs.ac.in" },
    2672: { name: "Patil Sejal Deepak", email: "sejal.patil@iccs.ac.in" },
    1566: { name: "Prajwal Vitthal Bhalsing", email: "prajwal.bhalsing@iccs.ac.in" },
    1447: { name: "Pramod Ramesh Gholap", email: "pramod.gholap@iccs.ac.in" },
    86: { name: "Pravin Shantaram Mate", email: "pravin.mate@iccs.ac.in" },
    1717: { name: "Rajesh Navnath Bansode", email: "rajesh.bansode@iccs.ac.in" },
    1674: { name: "Rajminar Devidas Navgire", email: "rajminar.navgire@iccs.ac.in" },
    1742: { name: "Raju Babu Jagtap", email: "raju.jagtap@iccs.ac.in" },
    1567: { name: "Ramdas Sanjay Bolage", email: "ramdas.bolage@iccs.ac.in" },
    1672: { name: "Ranjeet Dattatray More", email: "ranjeet.more@iccs.ac.in" },
    1986: { name: "Rupali Jalindar Zaware", email: "jadhav.rupali@iccs.ac.in" },
    2713: { name: "Sagar Babasaheb Kharade", email: "sagar.kharade@iccs.ac.in" },
    229: { name: "Sarika Yogesh Thakare", email: "sarika.thakare@iccs.ac.in" },
    118: { name: "Sarita Mareppa Byagar", email: "sarita.byagar@iccs.ac.in" },
    2295: { name: "Shambhu Anil Mahadik", email: "shambhu.mahadik@iccs.ac.in" },
    2180: { name: "Shubhangi Deepak Gore", email: "shubhangi.gore@iccs.ac.in" },
    1964: { name: "Shubhangi Sanjay Chavan", email: "shubhangi.chavan@iccs.ac.in" },
    1982: { name: "Soman Vikrant Sanjay", email: "vikrant.soman@iccs.ac.in" },
    2053: { name: "Sonali Pramod Patil (Bujbal)", email: "sonali.bhujbal@iccs.ac.in" },
    1204: { name: "Sumit Subhash Sasane", email: "Sumit.sasane@iccs.ac.in" },
    78: { name: "Sunita Tukaram Gawade", email: "sunita.gawade@iccs.ac.in" },
    1707: { name: "Suwarna Suresh Kedari", email: "kedari.suwarna@iccs.ac.in" },
    532: { name: "Tejashri Anil Phalke", email: "tejashriphalle@iccs.ac.in" },
    719: { name: "Thomson Varghese", email: "thomson.varghese@iccs.ac.in" },
    1970: { name: "Valmik Kashinath Dhanwate", email: "valmik.dhanwate@iccs.ac.in" },
    2933: { name: "Vede Amit Ankush", email: "amit.vede@iccs.ac.in" },
    335: { name: "Vijay Daulatrao More", email: "vijay.more@iccs.ac.in" },
    235: { name: "Vishal Pramod Verma", email: "vishal.verma@iccs.ac.in" },
    2127: { name: "Vividha Bahety", email: "vividha.bahety@iccs.ac.in" },
    1978: { name: "Yewale Sharmila B", email: "sharmila.yewale@iccs.ac.in" },
    1318: { name: "Yogesh Shamrao Bhusari", email: "yogesh.bhusari@iccs.ac.in" },
    316: { name: "Abhijit Chandratreya", email: "abhijitc@indiraiimp.edu.in" },
    1621: { name: "Anil Parkhe", email: "anil.parkhe@indiraiimp.edu.in" },
    2271: { name: "Ashish Marne", email: "ashish.marne@indiraiimp.edu.in" },
    2150: { name: "Ashutosh Kulkarni", email: "ashutosh.kulkarni@indiraiimp.edu.in" },
    103: { name: "Dinkar Kamble", email: "dinkar.kamble@indiraiimp.edu.in" },
    744: { name: "Dipanjay Jayant Bhalerao", email: "dipanjay.bhalerao@indiraiimp.edu.in" },
    2082: { name: "Sakshi Mann", email: "sakshi.mann@indiraiimp.edu.in" },
    310: { name: "Gopal Nandurkar", email: "gopal.nandurkar@indiraiimp.edu.in" },
    1513: { name: "Jyoti Gore", email: "jyoti.gore@indiraiimp.edu.in" },
    902: { name: "Kailas Mhetre", email: "kailas.mhetre@indiraiimp.edu.in" },
    95: { name: "Kailash Pawar", email: "kailas_p@indiraiimp.edu.in" },
    29: { name: "Khandu Inamke", email: "khandu.inamke@indiraiimp.edu.in" },
    2243: { name: "Kirti Vasudeo", email: "kirti.vasudeo@indiraiimp.edu.in" },
    2260: { name: "Laxman Narute", email: "laxman.narute@indiraiimp.edu.in" },
    318: { name: "Manasi Patil", email: "manasi.pawar@indiraiimp.edu.in" },
    85: { name: "Girish Parekh", email: "girishparekh@indiraedu.com" },
    1239: { name: "Neha Ramteke", email: "neha.ramteke@indiraiimp.edu.in" },
    1905: { name: "Nitin Joshi", email: "nitin.joshi@indiraiimp.edu.in" },
    2220: { name: "Priti Kulkarni", email: "priti.kulkarni@indiraiimp.edu.in" },
    429: { name: "Punam Bhoyar", email: "punam.bhoyar@indiraiimp.edu.in" },
    109: { name: "Purvi Shah", email: "purvi.shah@indiraiimp.edu.in" },
    1745: { name: "Rahul Pande", email: "rahul.pande@indiraedu.com" },
    1679: { name: "Ravi Baijulal Bhandari", email: "ravi.bhandari@indiraiimp.edu.in" },
    733: { name: "Rita Dangre", email: "rita.dangre@indiraedu.com" },
    205: { name: "Sachin Ramchandra Kamble", email: "sachin@indiraedu.com" },
    294: { name: "Sagar Kamble", email: "sagar.kamble@indiraiimp.edu.in" },
    2064: { name: "Sanchit Bhauso Pansare", email: "sanchit.pansare@indiraiimp.edu.in" },
    39: { name: "Sandeep Gunjal", email: "sandeep.gunjal@indiraiimp.edu.in" },
    1358: { name: "Sanjay Bhale", email: "sanjay.bhale@indiraiimp.edu.in" },
    1338: { name: "Shashikant Bade", email: "shashikant.bade@indiraiimp.edu.in" },
    13: { name: "Subhash Gaikwad", email: "subhash.gaikwad@indiraiimp.edu.in" },
    1650: { name: "Sumit Omprakash Sharma", email: "sumit.sharma@indiraedu.com" },
    2357: { name: "Sunil Maske", email: "sunil.maske@indiraiimp.edu.in" },
    2358: { name: "Swapnali Amol Kulkarni", email: "swapnali.kulkarni@indiraiimp.edu.in" },
    2833: { name: "Swati Patil", email: "swati.patil@indiraiimp.edu.in" },
    1797: { name: "Tushar Patil", email: "tushar.patil@indiraiimp.edu.in" },
    88: { name: "Yestrela Evangelist Vaz", email: "yestrela.vaz@indiraiimp.edu.in" },
    1880: { name: "Renu Darshan Garg", email: "renu.garg@indiraisc.edu.in" },
    2590: { name: "Alisha Mukhopadhayay", email: "alisha.mukhopadhayay@indiraiimp.edu.in" },
    1862: { name: "Anjali P Kalkar", email: "anjali.kalkar@indiraiimp.edu.in" },
    2429: { name: "Manoj Hemant Tapaswi", email: "manoj.tapaswi@indiraiimp.edu.in" },
    2176: { name: "P S Deepa", email: "deepa.sakthi@indiraiimp.edu.in" },
    2027: { name: "Patil Sudhir Jijabrao", email: "prof.sudhir.patil@indiraiimp.edu.in" },
    2034: { name: "Sachin Shankar Hadapad", email: "sachin.hadpad@indiraiimp.edu.in" },
    2141: { name: "Santoshkumar Tatyaram Kadam", email: "santoshkumar.kadam@indiraiimp.edu.in" },
    2613: { name: "Sarika Ravindranath Sagar", email: "sarika.sagar@indiraiimp.edu.in" },
    1960: { name: "Sonali Suresh Shrotri", email: "sonali.shrotri@indiraiimp.edu.in" },
    1922: { name: "Swapnil Dattatray Kharde", email: "swapnil.kharde@indiraiimp.edu.in" },
    2340: { name: "Torsha Ghosh", email: "torsha.ghosh@indiraiimp.edu.in" },
    2028: { name: "Vijayalakshmi Ganganna Nemmaniwar", email: "dr.vijayalaxmi@indiraiimp.edu.in" },
    1254: { name: "Akshay Ranjan Pawar", email: "akshay.pawar@indiraicp.edu.in" },
    1472: { name: "Amruta Prasann Walvekar", email: "amruta.walvekar@indiraicp.edu.in" },
    405: { name: "Anil Rama Gaikwad", email: "anil.gaikwad@indiraicp.edu.in" },
    2806: { name: "Anirudha Vasant Munde", email: "anirudha.munde@indiraicp.edu.in" },
    2258: { name: "Ashutosh Narayan Misal", email: "ashutosh.misal@indiraiimp.edu.in" },
    2817: { name: "Ashwini Chitrangad Kotkar", email: "ashwini.kotkar@indiraicp.edu.in" },
    354: { name: "Dayanand Mukund Kannur", email: "dayanand.kannur@indiraicp edu.in" },
    1813: { name: "Digambar Balkrishna Ambikar", email: "digambar.ambikar@indiraicp.edu.in" },
    32: { name: "Dilip Maruti Dhamale", email: "dilipdhamale@indiraicp.edu.in" },
    2803: { name: "Divya Ashok Kulkarni", email: "divya.kulkarni@indiraicp.edu.in" },
    446: { name: "Manasi Jayant Wagdarikar", email: "mansi.wagdarikar@indiraicp.edu.in" },
    153: { name: "Manohar Vitthal Jadhav", email: "manohar.jadhav@indiraicp.edu.in" },
    1577: { name: "Meghna Mandar Dabhadkar", email: "meghna.dabhadkar@indiraicp.edu.in" },
    1509: { name: "Pallavi Yogendra Singh Chouhan", email: "pallavi.chouhan@indiraicp.edu.in" },
    1388: { name: "Pradnya Parag Kulkarni", email: "pradnya.kulkarni@indiraicp.edu.in" },
    2805: { name: "Rajanigandha Rajendra Jori", email: "rajanigandha.jori@indiraicp.edu.in" },
    723: { name: "Ramling Arjun Gaikwad", email: "Ramling.gaikwad@indiraicp.edu.in" },
    2524: { name: "Rutuja Saurabh Lokhande", email: "rutuja.lokhande@indiraicp.edu.in" },
    224: { name: "Samadhan Prabhakar Gaikwad", email: "samadhan.gaikwad@indiraicp.edu.in" },
    2824: { name: "Sharmishtha Anurag Singh", email: "sharmishthasingh@indiraicp.edu.in" },
    1474: { name: "Shraddha Prakash Devarshi", email: "shraddha.devarshi@indiraicp.edu.in" },
    1699: { name: "Shubham Vijay Pawar", email: "shubham.pawar@indiraicp.edu.in" },
    2812: { name: "Sneha Anil Pachore", email: "sneha.pachore@indiraicp.edu.in" },
    2814: { name: "Sneha Ganesh Nawkar", email: "sneha.nawkar@indiraicp.edu.in" },
    1712: { name: "Sneha Vishwas Joshi", email: "sneha.joshi@indiraicp.edu.in" },
    2099: { name: "Snehali Pandurang Saykar", email: "snehali.saykar@indiraicp.edu.in" },
    1470: { name: "Swapnil Vilas Dhamale", email: "swapnil.dhamale@indiraicp.edu.in" },
    1870: { name: "Abhijit Prabhakar Bobde", email: "abhijit.bobde@indiraisbs.ac.in" },
    2703: { name: "Anita Sanjay Mathapati", email: "anita.mathapati@indiraisbs.edu.in" },
    2041: { name: "Bibeesh Kannan P.V.", email: "bibeesh.p@indiraisbsmba.edu.in" },
    2158: { name: "Dhanashri Swapnil Deshpande", email: "dhanashri.deshpande@indiraisbs.edu.in" },
    34: { name: "Haridas Ashok Deshmukh", email: "harish.deshmukh@indiraiimp.ac.in" },
    2153: { name: "Harshal Suresh Gajbhe", email: "harshal.gajbhe@indiraisbsmba.edu.in" },
    1623: { name: "Kalpana Kamalakar Deshmukh", email: "kalpana.deshmukh@indiraisbs.ac.in" },
    1334: { name: "Laxman Navnath Misal", email: "laxman.misal@indiraisbs.ac.in" },
    1869: { name: "Mrityunjay Kameshwar Lal Kumar", email: "mrityunjay.Kumar@indiraisbs.ac.in" },
    2838: { name: "Mrunalini Saheb Khandare", email: "mrunalini.khandare@indiraisbs.edu.in" },
    2893: { name: "Poonam Nitin Satpute", email: "poonam.satpute@indiraisbs.edu.in" },
    2823: { name: "Pravin Dnyandev Dolas", email: "pravin.dolas@indiraisbs.edu.in" },
    2087: { name: "Rajneesh Madanlal Bali", email: "rajneesh.bali@indiraedu.com" },
    132: { name: "Sangita Shahu Devare", email: "sangeeta.devare@indiraisbs.ac.in" },
    2493: { name: "Sanjay Kapoorchand Asati", email: "sanjay.asati@indiraisbs.edu.in" },
    1606: { name: "Subhash Tukaram Ghogare", email: "subhash.ghogare@indiraisbs.ac.in" },
    2478: { name: "Sushil Dashrath Shende", email: "sushil.shende@indiraisbs.edu.in" },
    1237: { name: "Tanaji Gopal Durgade", email: "tanaji.durgade@indiraisbs.ac.in" },
    2666: { name: "Tilak Kisan Nugurwar", email: "tilak.nugurwar@indiraedu.com" },
    2836: { name: "Vaibhavi Shashikant Shahane", email: "vaibhavi.shahane@indiraisbs.edu.in" },
    2908: { name: "Yogesh Sunil Pansare", email: "yogesh.pansare@indiraisbs.edu.in" },
    1307: { name: "Amruta Deshpande", email: "amruta.deshpande@indiraisbs.ac.in" },
    1671: { name: "Anagha Bhope", email: "anagha1.bhope@indiraisbs.ac.in" },
    1654: { name: "Anil Chalke", email: "anil.chalke@indiraisbs.ac.in" },
    2653: { name: "Anna Philips", email: "anna.philips@indiraisbs.ac.in" },
    133: { name: "Arun Padale", email: "arun.padale@indiraiscs.ac.in" },
    2399: { name: "Bharti Shukla", email: "bharti.shukla@indiraisbs.ac.in" },
    1575: { name: "Chetan Parange", email: "chetan.parange@indiraisbs.ac.in" },
    1635: { name: "Dipesh Kawale", email: "dipesh.kawale@indiraisbs.ac.in" },
    1541: { name: "Gaganpreet Ahluwalia", email: "gaganpreet.ahluwalia@indiraisbs.ac.in" },
    2270: { name: "Jaya Saxena", email: "jaya.saxena@indiraisbs.ac.in" },
    1957: { name: "Jayanthi Kumbhar", email: "jayanti.kumbhar@indiraisbs.ac.in" },
    1616: { name: "Jitendra Patil", email: "jitendra.patil@indiraisbs.ac.in" },
    2686: { name: "Kishan Giri", email: "kishan.giri@indiraisbs.ac.in" },
    1952: { name: "Kumendra Raheja", email: "kumendrar@indiraisbs.ac.in" },
    2380: { name: "Madan Khandekar", email: "madan.khandekar@indiraedu.com" },
    762: { name: "Mahesh Mangaonkar", email: "mahesh.mangaonkar@indiraisbs.ac.in" },
    1951: { name: "Mahesh Pol", email: "mahesh.pol@indiraisbs.ac.in" },
    5441: { name: "Maruti Uttekar", email: "maruti.utterkar@indiranationalschool.ac.in" },
    2221: { name: "Mayuresh Naregalkar", email: "mayuresh.naregalkar@indiraisbs.ac.in" },
    1855: { name: "Meghasham Chaudhari", email: "meghasham.chaudhari@indiraisbs.ac.in" },
    2241: { name: "Mohan Rathod", email: "mohan.rathod@indiraisbs.ac.in" },
    1399: { name: "Neetal Vyas", email: "neetal.vyas@indiraisbs.ac.in" },
    1899: { name: "Padmashree Chandak", email: "padmashree.chandak@indiraisbs.ac.in" },
    2029: { name: "Piyush Dixit", email: "piyush.dixit@indiraisbs.ac.in" },
    569: { name: "Pradip Patil", email: "pradip.patil@indiraisbs.ac.in" },
    1595: { name: "Pramod Shinde", email: "pramod.shinde@indiraicp.edu.in" },
    1279: { name: "Prashant Rege", email: "prashant.rege@indiraisbs.ac.in" },
    1182: { name: "Rajendra Vikhar", email: "rajendra.vikhar@indiraisbs.ac.in" },
    2245: { name: "Ravindra Shinde", email: "ravindra.shinde@indiraedu.com" },
    171: { name: "Sachin More", email: "sachin.more@indiraisbs.ac.in" },
    1357: { name: "Sadhana Ingle", email: "sadhana.ingle@indiraisbs.edu.in" },
    59: { name: "Sahebrao Patil", email: "sahebrao.patil@indiraisbs.ac.in" },
    2702: { name: "Sajid Shaikh", email: "sajid.shaikh@indiraisbs.ac.in" },
    508: { name: "Sameer Sheshgir", email: "samir.sheshgir@indiraicp.edu.in" },
    1536: { name: "Sanjay Muthal", email: "sanjay.muthal@indiraisbs.ac.in" },
    1538: { name: "Sanjay Rathod", email: "sanjay.rathod@indiraisbs.ac.in" },
    2521: { name: "Sarita Agarwal", email: "sarita.agarwal@indiraisbs.ac.in" },
    1050: { name: "Shikha Sindhu", email: "shikha.sindhu@indiraisbs.ac.in" },
    2720: { name: "Shweta Vyas", email: "shweta.vyas@indiraisbs.ac.in" },
    2395: { name: "Sumit Shinde", email: "sumit.shinde@indiraedu.com" },
    2078: { name: "Sushmitha Rao", email: "sushmitha.rao@indiraisbs.ac.in" },
    1214: { name: "Tausif Mistry", email: "tausif.mistry@indiraisbs.ac.in" },
    2718: { name: "Trupti Sharad Joshi", email: "padirector@indiraisbs.ac.in" },
    1729: { name: "Umesh Jagdale", email: "umesh.jagdale@indiraisbs.edu.in" },
    2721: { name: "Varsha Nagpure", email: "varsha.murhe@indiraisbs.ac.in" },
    26: { name: "Vinay Khawale", email: "vinayk@indiraedu.com" },
    2415: { name: "Yamini Ghanghorkar", email: "yamini.ghanghorkar@indiraisbs.ac.in" },
    3012: { name: "Karun Kumar Chaugule", email: "karunkumar.chaugule@indiraiimp.edu.in" },
    3027: { name: "Bharti Khaire", email: "bharti.khaire@indiraiimp.edu.in" },
    3021: { name: "Sunil Kashinath Sakhare", email: "sunil.sakhare@indiraedu.com" },
    3034: { name: "Kadambari Vishnu Suryawanshi", email: "Kadambari.Suryawanshi@indiraiimp.edu.in" },
    3048: { name: "Kavita Mathad", email: "dean.sob@indirauniversity.edu.in" },
    3037: { name: "Prakash Vishnu Khadse", email: "prakash.khadse@indiraedu.com" },
    2789: { name: "Shashwat Doshetti", email: "shashwat.doshetti@indiraigsb.edu.in" },
    //INS
    2322: { name: "Abhilasha Tiwari", email: "abhilasha.tiwari@ins.ac.in" },
    2972: { name: "Akshay Thosar", email: "thosarra45@gmail.com" },
    2329: { name: "Alwin Daniel Satpute", email: "alwin.satpute@ins.ac.in" },
    2307: { name: "Anand Hari Patil", email: "ananda.patil@ins.ac.in" },
    2585: { name: "Asha Mahendra Ghodke", email: "asha.ghodke@ins.ac.in" },
    2947: { name: "Bhagyashree Yogesh Vispute", email: "bhagyashree.vispute@ins.ac.in" },
    2558: { name: "Bharat Chandrakant Kshirsagar", email: "bharat.kshirsagar@ins.ac.in" },
    683: { name: "Dattatraya Mohan Sutar", email: "dattatraya.sutar@ins.ac.in" },
    1645: { name: "Gayatri Jorwekar", email: "gayatri.jorwekar@indiraedu.com" },
    2568: { name: "Jyoti Santosh Thorat", email: "Jyoti.thorat@ins.ac.in" },
    2306: { name: "Kamaljit Kaur Sidhu", email: "kamaljit.sidhu@ins.ac.in" },
    2962: { name: "Kasturi Kapil Kedari", email: "kasturi.kedari@ins.ac.in" },
    2587: { name: "Meenakshi Sisodia", email: "meenakshi.sisodia@ins.ac.in" },
    2691: { name: "Mrunal Vaidya", email: "mrunal.vaidya@ins.ac.in" },
    2633: { name: "Nisha Nitin Deore", email: "nisha.deore@ins.ac.in" },
    2697: { name: "Pallavi Nitin Chinchole", email: "pallavi.chinchole@ins.ac.in" },
    2981: { name: "Pallavi Shejwal", email: "pallavi.shejwal@ins.ac.in" },
    2320: { name: "Prachi Jain", email: "prachi.jain@ins.ac.in" },
    2312: { name: "Prachi Sandeep Sant", email: "prachi.sant@ins.ac.in" },
    2693: { name: "Ruchi Dilip Tulshyan", email: "ruchi.tulshyan@ins.ac.in" },
    2936: { name: "Saroj Jain", email: "saroj.jain@ins.ac.in" },
    2647: { name: "Shilpa Sachin Biradar", email: "shilpa.biradar@ins.ac.in" },
    2727: { name: "Shravani Shriniwas Arole", email: "shravani.arole@ins.ac.in" },
    2629: { name: "Shreya Roy", email: "shreya.roy@ins.ac.in" },
    2569: { name: "Shweta Santosh Sawant", email: "sweta.sawant@ins.ac.in" },
    2333: { name: "Sipra Ray", email: "sipra.ray@ins.ac.in" },
    2308: { name: "Snehal Pravin Kakade", email: "snehal.kakade@ins.ac.in" },
    2689: { name: "Sonal Jha", email: "sonal.jha@ins.ac.in" },
    2561: { name: "Sonam Keshwani", email: "Sonam.Keshwani@ins.ac.in" },
    1523: { name: "Suhas Suryawanshi", email: "suhas.suryawanshi@indiraiimp.edu.in" },
    1198: { name: "Sunil Namdeo Thakar", email: "sunil.thakar@ins.ac.in" },
    2572: { name: "Sushma Sachin Bora", email: "sushma.bora@ins.ac.in" },
    2324: { name: "Tapati Sil", email: "tapati.sil@ins.ac.in" },
    2555: { name: "Vedanti Shinde", email: "vedanti.shinde@ins.ac.in" },
    2692: { name: "Yogita Lamkanikar", email: "yogita.lamkanikar@ins.ac.in" },
    37: { name: "Ganesh Dhumal", email: "ganesh.dhumal@indiraiimp.edu.in" },
    E5406: { name: "Sumit Sunil Adkitte", email: "sumit.adkitte@ins.ac.in" },
    E5351: { name: "Yogita Dattatraya Sutar", email: "yogita.sutar@ins.ac.in" },
    E5459: { name: "Swapnali Gaikwad", email: "Swapnali.gaikwad@ins.ac.in" },
    E5347: { name: "Umesh Gajanan Palande", email: "umesh.palande@ins.ac.in" },
    E5846: { name: "Seema Ghogare", email: "seema.ghogare@ins.ac.in" },
    E5569: { name: "Indrani Das", email: "Indrani.Das@ins.ac.in" },
    E5005: { name: "Tanu Pankaj Pandhi", email: "tanu.pandhi@ins.ac.in" },
    E5007: { name: "Sangeeta Vimal Khandka", email: "sangeeta.khandka@ins.ac.in" },
    E5021: { name: "Anjali Nitin Dharmadhikari", email: "anjali.dharmadhikari@ins.ac.in" },
    E5023: { name: "Jayashree Vivek Thorat", email: "jayashree.thorat@ins.ac.in" },
    E5036: { name: "Vrushali Nitin Deshmukh", email: "vrushali.deshmukh@ins.ac.in" },
    E5047: { name: "Ravindra Gyanba Kamble", email: "ravindra.kamble@ins.ac.in" },
    E5050: { name: "Nitin Chandrakant Sangme", email: "nitin.sangme@ins.ac" },
    E5051: { name: "Anup Dattatray Kutwal", email: "anup.kutwal@ins.ac.in" },
    E5065: { name: "Prashant Sakharam Paste", email: "prashant.paste@ins.ac.in" },
    E6446: { name: "Ganesh Raju Pawar", email: "ganesh.pawar@ins.ac.in" },
    E5067: { name: "Nivas Vasant Pujari", email: "niwas.pujari@ins.ac.in" },
    E5040: { name: "Vinit Ramesh Yadav", email: "Vinit.yadav@ins.ac.in" },
    E5025: { name: "Nima Velangi", email: "nima.velangi@ins.c.in" },
    E5010: { name: "Archana Abhijit Hulawale", email: "archana.hulawale@ins.ac.in" },
    E5027: { name: "Smita Yogesh Kataria", email: "Smita.Kataria@ins.ac.in" },
    E5054: { name: "Abhijit Balasaheb Mankar", email: "abhijit.mankar@ins.ac.in" },
    E5015: { name: "Varsha Prasad Joshi", email: "varsha.joshi@ins.ac.in" },
    E5029: { name: "Aarti Chandrashekhar Garampalli", email: "aarti.garampalli@indiranationalschool.ac.in" },
    E5042: { name: "Suman Rangarao Mane", email: "suman.mane@ins.ac.in" },
    E5018: { name: "Urmila Gaikwad", email: "Urmila.gaikwad@ins.ac.in" },
    E5039: { name: "Premchand Mohanlal Kumbhar", email: "Premchand.Kumbhar@ins.ac.in" },
    E5072: { name: "Supriya Akhilesh Shukla", email: "Supriya.Wankhede@ins.ac.in" },
    E5064: { name: "Amit Uttam Yerunkar", email: "amit.yerunkar@ins.ac.in" },
    E6003: { name: "Aakanksha Anand Bhangaonkar", email: "aakanksha.bhangaonkar@indiranationalschool.ac.in" },
    E5090: { name: "Gurunath Baban Kale", email: "Gurunath.Kale@ins.ac.in" },
    E5087: { name: "Najeeb Ahmed Munshi", email: "najeeb.munshi@ins.ac.in" },
    E5098: { name: "Neelima Srivastava", email: "Neelima. Srivastava@ins.ac.in" },
    E5105: { name: "Shivaji Kashiram Uttekar", email: "shivaji.uttekar@ins.ac.in" },
    E5106: { name: "Anita Suryabhan Shinde", email: "anita.shinde@ins.ac.in" },
    E5108: { name: "Sameer Alam Shaikh", email: "sameer.shaikh@ins.ac.in" },
    E5107: { name: "Yogini Pankaj Randive", email: "yogini.ranadive@ins.ac.in" },
    E5125: { name: "Aparna Vineet Bhasin", email: "Aparna.Bhasin@ins.ac.in" },
    E5131: { name: "Aradhana Narayan Budhwant", email: "aradhana.budhwant@ins.ac.in" },
    E5447: { name: "Munjaji Pitale", email: "munjaji.pithale@ins.ac.in" },
    E5152: { name: "Tanima Sanjoy Sengupta", email: "tanima.sengupta@ins.ac.in" },
    E5155: { name: "Nidhi Abhijitkumar Saxena", email: "nidhi.saxena@ins.ac.in" },
    E5137: { name: "Lakshmi Prabha Mitra", email: "lakshmi.mitra1@ins.ac.in" },
    E5444: { name: "Vijaypal Galthya Singh", email: "vijaypal.singh@ins.ac.in" },
    E5077: { name: "Vaishali Bhaskar Khatal", email: "vaishali.khatal@ins.ac.in" },
    E5102: { name: "Gauri Mani", email: "Gauri.Mani@ins.ac.in" },
    E5225: { name: "Swanandi Sagar Shinde", email: "swanandi.shinde@ins.ac.in" },
    E5103: { name: "Roli Sachin Jain", email: "roli.jain@ins.ac.in" },
    E5104: { name: "Mukul Vinaykumar Pal", email: "mukul.pal@ins.ac.in" },
    E5076: { name: "Lucky Manash Sengupta", email: "lucky.sengupta@ins.ac.in" },
    E5168: { name: "Chaitali Guha", email: "chaitali.guha@ins.ac.in" },
    E5349: { name: "Bhausaheb Madhukar Kalkhair", email: "bhausaheb.kalkhair@ins.ac.in" },
    E5452: { name: "Sachin Bhimaji Salunke", email: "sachin.salunke@ins.ac.in" },
    E5210: { name: "Jyoti Nilkanth Mahajan", email: "jyoti.mahajan@ins.ac.in" },
    E5580: { name: "Indira Rajeshwari", email: "Indira.Rajeshwari@ins.ac.in" },
    E5238: { name: "Shravina Satish Dubey", email: "shravina.dubey@ins.ac.in" },
    E5247: { name: "Shabana Salim Shaikh", email: "shabana.shaikh@ins.ac.in" },
    1367: { name: "Gautam Suhas Sabnis", email: "gautam.sabnis@indiraedu.com" },
    E5240: { name: "Reshmi Shubhadeep Ghosh", email: "Reshmi.Ghosh@ins.ac.in" },
    E5439: { name: "Amol Dilip Pimple", email: "amol.pimple@indiraedu.com" },
    E5300: { name: "Meghna Mittal", email: "meghna.mittal@ins.ac.in" },
    E5309: { name: "Manasi Rahul Deshpande", email: "Mansi.deshpande@ins.ac.in" },
    E5301: { name: "Ranjana Negi", email: "ranjana.negi@ins.ac.in" },
    E5290: { name: "Swati Kailas Kumbhar", email: "Swati.kumbhar@ins.ac.in" },
    E5353: { name: "Rajan Gyanba Jamdade", email: "Rajan.Jamdade@ins.ac.in" },
    E5324: { name: "Preetam Deepak Kale", email: "preetam.kale@ins.ac.in" },
    E5291: { name: "Pooja Sandeep Jahagirdar", email: "Pooja.Jahagirdar@ins.ac.in" },
    E5327: { name: "Shamal Sandesh Vartak", email: "Shamal.Vartak@ins.ac.in" },
    E5453: { name: "Nilesh Bhiku Ratwadkar", email: "nilesh.ratwadkar@ins.ac.in" },
    E5726: { name: "Shalini Baghel", email: "shalini.baghel@ins.ac.in" },
    E5344: { name: "Ram Niwas", email: "ram.niwas@ins.ac.in" },
    E5358: { name: "Priya Samudre", email: "priya.samudre@ins.ac.in" },
    E5383: { name: "Manisha Martule", email: "Manisha.Martule@ins.ac.in" },
    E5381: { name: "Smita Anand Desai", email: "smita.desai@ins.ac.in" },
    E5387: { name: "Kiran Rahul Gaikwad", email: "Indira National School" },
    E5438: { name: "Soni Singh", email: "soni.singh@ins.ac.in" },
    E5478: { name: "Mala Gupta", email: "Mala.Gupta@ins.ac.in" },
    E5470: { name: "Prajakta Shirolikar", email: "prajakta.shirolikar@ins.ac.in" },
    E5476: { name: "Elizabeth Samuel", email: "elizabeth.samuel@ins.in.ac" },
    E5579: { name: "Sujata Mohod", email: "sujata.mohod@ins.ac.in" },
    E5461: { name: "Nancy Sachdeva", email: "Nancy.Sachdeva@ins.ac.in" },
    E5495: { name: "Manisha Jha Choudhary", email: "Manisha.Choudhary@ins.ac.in" },
    E5602: { name: "Aarti Bhalerao", email: "aarti.bhalerao@ins.ac.in" },
    E5501: { name: "Kanchan Bala Goel", email: "Kanchan.Goel@ins.ac.in" },
    E5518: { name: "Amol Zarkar", email: "amol.zarkar@ins.ac.in" },
    E5523: { name: "Ananya Aniket Dhuru", email: "ananya.dhuru@ins.ac.in" },
    E5549: { name: "Anant Jodh", email: "anant.jodh@ins.ac.in" },
    E5566: { name: "Durga Dnyaneshwar Chavan", email: "durga.chavan@ins.ac.in" },
    E5595: { name: "Satish Vitthal Bade", email: "satish.bade@indiraiimp.edu.in" },
    E5260: { name: "Gaurav Navaskar", email: "gaurav.navaskar@ins.ac.in" },
    E5565: { name: "Ashwini Shashank Kulkarni", email: "ashwini.kulkarni@ins.ac.in" },
    E5568: { name: "Uma Senthil Kumar", email: "uma. senthilkumar@ins.ac.in" },
    E5348: { name: "Sadhu Ganoba Landge", email: "sadhu.landge@ins.ac.in" },
    E5588: { name: "Jayram Jadhav", email: "jayaram.jadhav@ins.ac.in" },
    E5589: { name: "Jyoti Deepak Thosar", email: "jyoti.thosar@ins.ac.in" },
    E5591: { name: "Ganesh Jadhav", email: "ganesh.jadhav@ins.ac.in" },
    E5421: { name: "Sanjeevani Thaksen Gadhave", email: "sanjeevani.gadhave@ins.ac.in" },
    E5599: { name: "Chaiti Bhowmick", email: "Chaiti.bhowmick@ins.ac.in" },
    1351: { name: "Sandeep Sukalal Dhangar", email: "sandip.suryawanshi@indiraedu.com" },
    998: { name: "Bhausaheb Changdeo Gaikwad", email: "bhausaheb.gaikwad@indiraicem.ac.in" },
    E5610: { name: "Balaji Udhav Yekile", email: "balaji.yekile@ins.ac.in" },
    E5608: { name: "Vaibhav Kakade", email: "Vaibhav.Kakade@ins.ac.in" },
    E5622: { name: "Aditi Pramanick", email: "Aditi.Pramanick@ins.ac.in" },
    E5616: { name: "Nandita Sanjib Mustafi", email: "nandita.mustafi@ins.ac.in" },
    E5621: { name: "Gayatri Chawla", email: "gayatri.chawla@ins.ac.in" },
    E5625: { name: "Sarika Bhauso Mane", email: "Sarika.Mane@ins.ac.in" },
    E5624: { name: "Ranjeeta Dixit", email: "ranjeeta.dixit@ins.ac.in" },
    E5615: { name: "Monika Rajput", email: "monika.rajput@ins.ac.in" },
    E5620: { name: "Vasanti Mahadik", email: "vasanti.mahadik@ins.ac.in" },
    E5639: { name: "Vijaya Borhade", email: "vijaya.borhade@ins.ac.in" },
    E5637: { name: "Rohini Sukhdeo Jadhav", email: "rohini.jadhav@ins.ac.in" },
    E5642: { name: "Samiksha Sanjay Jadhav", email: "samiksha.jadhav@ins.ac.in" },
    E5521: { name: "Akshay Shete", email: "akshay.shete@ins.ac.in" },
    137: { name: "Sachin Waghmare", email: "archanasachin208@gmail.com" },
    676: { name: "Harilal Gorakhnath Yadav", email: "Harilal.Gorakhnath@ins.ac.in" },
    697: { name: "Rajendra Laxman Parase", email: "rajendraparse@indiraedu.com" },
    1724: { name: "Vaibhav Pawar", email: "vaibhav.pawar@indiraisbs.ac.in" },
    1212: { name: "Sachin Dhumal", email: "sachin.dhumal@indiraicem.ac.in" },
    1177: { name: "Umesh Shrirang Waghmare", email: "umesh.waghmare@IndiraInternationalSchool.ac.in" },
    E5641: { name: "Rajasouriya Singh", email: "rajasouriya.singh@ins.ac.in" },
    194: { name: "Gangadhar Kurhade", email: "gangadhar.kurhade@indiraiimp.edu.in.in" },
    E5649: { name: "Himani Bhole", email: "himani.bhole@ins.ac.in" },
    1386: { name: "Dagdu Rokade", email: "" },
    1090: { name: "Prashant Yeole", email: "prashant.yeole@indiraiimp.edu.in" },
    E5653: { name: "Shubhangi Desai", email: "shubhangi.desai@ins.ac.in" },
    1431: { name: "Sameer Surendra Waghmare", email: "sameer.waghmare@indiraiimp.edu.in" },
    E5652: { name: "Shubhangi Bodhankar", email: "Shubhangi.bodhankar@ins.ac.in" },
    E5660: { name: "Antima Jaipuria", email: "Antima.Jaipuria@ins.ac.in" },
    E5657: { name: "Rohini Yadav", email: "rohini.yadav@ins.ac.in" },
    E5666: { name: "Kirti Vikas Joshi", email: "kirti.joshi@ins.ac.in" },
    E5664: { name: "Swati Bavaskar", email: "Swati.Bavaskar@ins.ac.in" },
    E5670: { name: "Shruti Chadha", email: "Shruti.chadha@ins.ac.in" },
    E5668: { name: "Manjusha Koranne", email: "manjusha.koranne@ins.ac.in" },
    E5715: { name: "Snehal Ankush Basutkar", email: "Snehal.badutkar@ins.ac.in" },
    E5676: { name: "Archana Singh", email: "Archana.Singh@ins.ac.in" },
    E5686: { name: "Renuka Pande", email: "renuka.pande@ins.ac.in" },
    E5688: { name: "Kalpana Claudius", email: "kalpana.claudius@ins.ac.in" },
    E5679: { name: "Madhurani Mathane", email: "Madhurani.mathane@ins.ac.in" },
    E5682: { name: "Preeti Purohit", email: "Preeti.Purohit@ins.ac.in" },
    E5704: { name: "Manisha Badlamwar", email: "manisha.badlamwar@ins.ac.in" },
    E5707: { name: "Priti Singh", email: "Priti.singh@ins.ac" },
    E5716: { name: "Ganesh Dhawale", email: "ganesh.dhawale@ins.ac.in" },
    E5706: { name: "Aaditi Maheshwari", email: "aaditi.maheshwari@ins.ac.in" },
    E5022: { name: "Uma Pradeep", email: "uma.pradeep@indiranationalschool.ac.in" },
    E5717: { name: "Sireesha Kongara", email: "sireesha.kongara@ins.ac.in" },
    E5187: { name: "Mariamma Shibu Anthony", email: "mariamma.anthony@ins.ac.in" },
    E5728: { name: "Ashwini Mahesh Nagargoje", email: "ashwini.nagargoje@ins.ac.in" },
    E5735: { name: "Vandana Patnaik", email: "vandana.patnaik@ins.ac.in" },
    E5722: { name: "Anagha Yogesh Tungar", email: "anagha.tungar@ins.ac.in" },
    E5721: { name: "Parmeshwar Sonpasare", email: "parmeshwar.sonpasare@ins.ac.in" },
    E5743: { name: "Vinay Eknath Suryavanshi", email: "vinay.suryavanshi@ins.ac.in" },
    E5740: { name: "Mahesh Baban Gadave", email: "Mahesh.Gadave@ins.ac.in" },
    E5736: { name: "Sunil Vishwas Gaikwad", email: "Sunil.gaikwad@ins.ac.in" },
    E5741: { name: "Jitendra Pratap Rokade", email: "Jitendra.Rokade@ins.ac.in" },
    E5746: { name: "Mamta Salokhe", email: "mamta.salokhe@ins.ac.in" },
    E5745: { name: "Nikita Sikandar Sawant", email: "nikita.sawant@ins.ac.in" },
    E5732: { name: "Ravi Gotsurwe", email: "ravi.gotsurve@ins.ac.in" },
    E5724: { name: "Vaishnavi Anil Bhangare", email: "Vaishnavi.Bhangare@ins.ac.in" },
    192: { name: "Santosh Koli", email: "Santosh.koli@indiraiimp.edu.in" },
    183: { name: "Mangesh Gaikwad", email: "mangesh.gaikwad@ins.ac.in" },
    E5753: { name: "Deepak Kodak", email: "Deepak.kodak@ins.ac.in" },
    E5749: { name: "Bharati Sillode", email: "Bharati.sillode@ins.ac.in" },
    E5750: { name: "Neha Solanki", email: "Neha.solanki@ins.ac.in" },
    1886: { name: "Sheetal Todkar", email: "sheetal.todkar@indiraiimp.edu.in" },
    E5763: { name: "Vaishnavi Ghumai", email: "vaishnavi.ghumai@ins.ac.in" },
    E5767: { name: "Bhagyashri Ainapure", email: "Bhagyashri.Ainpure@ins.ac.in" },
    E5758: { name: "Vaishnavi Ghadage", email: "Vaishnavi.ghadage@indiranationalschool.ac.in" },
    E5783: { name: "Vaishali Sonawane", email: "vaishali.sonawane@ins.ac.in" },
    E5778: { name: "Manisha Hirekude", email: "" }, // E5778 has no email
    E5784: { name: "Mohini Joshi", email: "mohini.joshi@ins.ac.in" },
    E5794: { name: "Anita Sharma", email: "anita.sharma@ins.ac.in" },
    1992: { name: "Harshal Papal", email: "harshal.papal@indiraiimp.edu.in" },
    E5795: { name: "Swapnali Ahire", email: "Swapnali.Ahire@ins.ac.in" },
    E5797: { name: "Sankari Roy Das", email: "Sankari.roydas@ins.ac.in" },
    E5798: { name: "Medini Pohare", email: "medini.pohare@ins.ac.in" },
    E5796: { name: "Ranjana Tiwari", email: "ranjana.tiwari@ins.ac.in" },
    E5799: { name: "Purnima Mohite", email: "purnima.mohite@ins.ac.in" },
    E5805: { name: "Rasika Patil", email: "rasika.patil@ins.ac.in" },
    E5800: { name: "Saurabh Sharma", email: "Saurabh.sharma@ins.ac.in" },
    E5802: { name: "Neelam Bhagwat", email: "Neel.Bhagwat@ins.ac.in" },
    E5801: { name: "Pooja Bandgar", email: "pooja.bandgar@ins.ac.in" },
    E5808: { name: "Rajesh Dhebe", email: "rajesh.dhebe@ins.ac.in" },
    E5810: { name: "Fatima Banu", email: "fatima.banu@ins.ac.in" },
    E5811: { name: "Tanushree Das", email: "tanushree.das@indiranationalschool.ac.in" },
    E5812: { name: "Rohan Jagtap", email: "rohan.jagtap@ins.ac.in" },
    E5814: { name: "Seenul Kaparwan", email: "seenul.kaparwan@ins.ac.in" },
    E5816: { name: "Rucha Ubale", email: "rucha.ubale@ins.ac.in" },
    E5820: { name: "Protusha Mukherjee", email: "protusha.mukherjee@ins.ac.in" },
    E5819: { name: "Shrikant Panda", email: "shrikant.panda@ins.ac.in" },
    E5817: { name: "Alpa Patadia", email: "alpa.patadia@ins.ac.in" },
    E5818: { name: "Kanchan Gongle", email: "Kanchan.gongle@ins.ac.in" },
    E5813: { name: "Swati Khekare", email: "swati.khekare@ins.ac.in" },
    E5822: { name: "Pinal Kotak", email: "pinal.kotak@ins.ac.in" },
    E5824: { name: "Ashat Pujari", email: "Ashat.pujari@ins.ac.in" },
    E5823: { name: "Suvarna Dawkhar", email: "suvarna.dawkhar@ins.ac.in" },
    E5832: { name: "Darshana Parte", email: "darshana.parte@indiranationalschool.ac.in" },
    E5834: { name: "Soujanya Jamajaggali", email: "soujanya.jamajaggali@ins.ac.in" },
    E5829: { name: "Padmashri Pagar", email: "Padmashri.Pagar@ins.ac.in" },
    E5791: { name: "Shubhangi Narayane", email: "shubhangi.narayane@ins.ac.in" },
    E5804: { name: "Dhammapal Kamble", email: "Dhammapal.Kamble@ins.ac.in" },
    E5839: { name: "Pradeep Kadam", email: "Pradeep.kadam@ins.in.ac" }, // Possibly invalid domain
    E5860: { name: "Ram Panday", email: "Ram.panday@ins.ac.in" },
    E5847: { name: "Sachin Talole", email: "sachin.talole@ins.ac.in" },
    E5851: { name: "Sasmita Bhanja", email: "sasmita.bhanja@ins.ac.in" },
    E5858: { name: "Vinita Mandlik", email: "Vinita.Mandlik@ins.ac.in" },
    E5848: { name: "Tejas Mistry", email: "tejas.mestry@ins.ac.in" },
    E5854: { name: "Ashwini Ekbote", email: "ashwini.ekbote@ins.ac.in" },
    E5861: { name: "Siddharth Terdale", email: "siddharth.terdale@ins.ac.in" },
    E5864: { name: "Shubhangee Gaikwad", email: "Shubhangee.Gaikwad@ins.ac.in" },
    E5865: { name: "Juhi Dhall", email: "juhi.dhall@ins.ac.in" },
    E5870: { name: "Shreya Mukherjee", email: "shreya.mukherjee@ins.ac.in" },
    E5872: { name: "Karuna Rokade", email: "Karuna.Rokade@ins.ac.in" },
    E5880: { name: "Pramathesh Karandikar", email: "pramathesh.karandikar@ins.ac.in" },
    E5787: { name: "Abhijeet Kadam", email: "abhijeet.kadam@ins.ac.in" },
    E5887: { name: "Mayuri Ghorpade", email: "Mayuri.Ghorpade@ins.ac.in" },
    E5885: { name: "Swati Karande", email: "Swati.Karande@ins.ac.in" },
    E5889: { name: "Poonam Shirsat", email: "Poonam.shirsat@ins.ac.in" },
    E5892: { name: "Madhura Shukla", email: "Madhura.Shukla@ins.ac.in" },
    E5895: { name: "Ganesh Singh", email: "ganesh.singh@ins.ac.in" },
    E5896: { name: "Deepti Pandey", email: "deepti.pandey@ins.ac.in" },
    E5897: { name: "Sonia Chawla", email: "Sonia.chawla@ins.ac.in" },
    E5901: { name: "Apurva Solapure", email: "apurva.solapure@ins.ac.in" },
    E5903: { name: "Vishakha Nemade", email: "vishakha.nemade@ins.ac.in" },
    E5911: { name: "Puja Sangme", email: "info@indiranationalschool.ac.in" },
    E5908: { name: "Swapnil Ranit", email: "swapnil.ranit@ins.ac.in" },
    E5909: { name: "Mamta Mantri", email: "Mamta.Mantri@ins.ac.in" },
    E5915: { name: "Kiran Tiwari", email: "Kiran.tiwari@ins.ac.in" },
    E5898: { name: "Apurwa Chauhan", email: "Apurwa.chauhan@ins.ac.in" },
    E5899: { name: "Varsha Ambegave", email: "Varsha.ambegave@ins.ac.in" },
    E5907: { name: "Veena Yadav", email: "Veena.Yadav@ins.ac.in" },
    E5917: { name: "Reena Brahmane", email: "reena.brahmane@ins.ac.in" },
    E5912: { name: "Rashmi Bawankar", email: "rashmi.bawankar@ins.ac.in" },
    E5906: { name: "Vidya Sankpal", email: "Vidya.sankpal@ins.ac.in" },
    E5902: { name: "Pooja Chaudhary", email: "pooja.chaudhary@ins.ac.in" },
    E5919: { name: "Abhishree More", email: "abhishree.more@ins.ac.in" },
    E5918: { name: "Ashwin Mohite", email: "ashwin.mohite@ins.ac.in" },
    E5883: { name: "Bhushan Sutar", email: "bhushan.sutar@ins.ac.in" },
    E5597: { name: "Vishnu K. Kulkarni", email: "vishnu.kulkarni@indiraedu.com" },
    E5598: { name: "Vaibhav Vasant Joshi", email: "vaibhav.joshi@ins.ac.in" },
    1365: { name: "Shailesh Adinath Pawar", email: "shailesh.adinath@ins.ac.in" },
    E5925: { name: "Santosh Itkare", email: "santosh.itkare@ins.ac.in" },
    E5928: { name: "Nivedita Joshi", email: "nivedita.joshi@ins.com" }, // Possibly invalid domain
    E5929: { name: "Shital Joshi", email: "Shital.Joshi@ins.ac.in" },
    E5930: { name: "Raju Raut", email: "raju.raut@ins.ac.in" },
    E5931: { name: "Vibha Mathur", email: "vibha.mathur@ins.ac.in" },
    E5933: { name: "Mansi Pandhare", email: "mansi.pandhare@ins.ac.in" },
    E5935: { name: "Swapnil Kadam", email: "swapnil.kadam@ins.ac.in" },
    E5936: { name: "Pranita Patil", email: "pranita.patil@ins.ac.in" },
    E5937: { name: "Swati Shinde", email: "Swati.Shinde@ins.ac.in" },
    E5938: { name: "Sanket Surve", email: "sanket.surve@ins.ac.in" },
    E5809: { name: "Salim Shaikh", email: "salim.shaikh@ins.ac.in" },
    E5941: { name: "Yogita Jadhav", email: "Yogita.jadhav@ins.ac.in" },
    E5942: { name: "Pooja Gidveer", email: "pooja.gidveer@ins.ac.in" },
    E5943: { name: "Kavita Gaikwad", email: "kavita.gaikwad@ins.ac.in" },
    E5944: { name: "Pratima Yadav", email: "pratima.yadav@ins.ac.in" },
    E5945: { name: "Madhuri Jagadale", email: "madhuri.jagadale@ins.ac.in" },
    E5946: { name: "Rajani Lakhyani", email: "rajani.lakhyani@ins.ac.in" },
    E5951: { name: "Sunita Dhane", email: "sunita.dhane@ins.ac.in" },
    E5955: { name: "Mayuri Jain", email: "mayuri.jain@ins.ac.in" },
    E5956: { name: "Swapna Kadekar", email: "Swapna.kadekar@ins.ac.in" },
    E5959: { name: "Komada Shinde", email: "komada.shinde@ins.ac.in" },
    E5964: { name: "Jayashree Patil", email: "jayashree.patil@indiranationalschool.ac.in" },
    E5965: { name: "Sumitkumar Gandhi", email: "sumitkumar.gandhi@ins.ac.in" },
    E5966: { name: "Adinath Satpute", email: "adinath.satpute@ins.ac.in" },
    E5852: { name: "Akash Shetty", email: "akash.shetty@ins.ac.in" },
    E5762: { name: "Vinod Sathe", email: "vinod.sathe@ins.ac.in" },
    240: { name: "Eazaz R. Bagwan", email: "eazaz.bagwan@indiraedu.com" },
    E5967: { name: "Indira Choudhary", email: "indira.choudhary@ins.ac.in" },
    E5968: { name: "Amol Lambhate", email: "amol.lambhate@ins.ac.in" },
    E5973: { name: "Nimishaben Trivedi", email: "nimishaben.trivedi@ins.ac.in" },
    E5975: { name: "Priyanka Sapkale", email: "priyanka.sapkale@ins.ac.in" },
    E5976: { name: "Taru Shikha", email: "taru.shikha@ins.ac.in" },
    E5890: { name: "Prathamesh Salunke", email: "prathamesh.salunke@ins.ac.in" },
    E5978: { name: "Supriya Aglaye", email: "Supriya.m.todkar@gmail.com" },
    E5979: { name: "Arti Badola", email: "Arti.badola@ins.ac.in" },
    E5981: { name: "Eesha Deshpande", email: "eesha.deshpande@ins.ac.in" },
    E5985: { name: "Vinay Waghmare", email: "vinay.waghmare@ins.ac.in" },
    E5986: { name: "Tejal Mehta", email: "tejal.mehta@ins.ac.in" },
    E5988: { name: "Debasmita Biswas", email: "debasmita.biswas@ins.ac.in" },
    E5989: { name: "Angha Nalgirkar", email: "anagha.nalgirkar@ins.ac.in" },
    E5990: { name: "Suraj Bhise", email: "suraj.bhise@ins.ac.in" },
    328: { name: "Babasaheb Patil", email: "babasaheb.patil@ins.ac.in" },
    E5991: { name: "Vaibhavkumar Dhundle", email: "Vaibhavkumar.dhundle@ins.ac.in" },
    E5992: { name: "Reema Punjabi", email: "reema.punjabi@ins.ac.in" },
    E5994: { name: "Harpreet Kaur", email: "harpreet.kaur@ins.ac.in" },
    E5995: { name: "Sonam Lonkar", email: "sonam.lonkar@ins.ac.in" },
    E5997: { name: "Swapna Kulkarni", email: "swapna.kulkarni@ins.ac.in" },
    E5998: { name: "Devshree Patil", email: "devshree.patil@ins.ac.in" },
    E5999: { name: "Shobhana Pardeshi", email: "shobhana.pardessi@ins.ac.in" },
    E6000: { name: "Rupali Shirsat", email: "rupali.shirsat@ins.ac.in" },
    E6001: { name: "Jayshri Deshpande", email: "jayshri.deshpande@ins.co.in" }, // Possibly incorrect domain
    E6004: { name: "Kritika Alwani", email: "kritika.alwani@ins.ac.in" },
    E6005: { name: "Jyotika Biswas", email: "jyotika.biswas@ins.ac.in" },
    E6006: { name: "Niharika Singh", email: "niharika.singh@ins.ac.in" },
    E6008: { name: "Archana Trisal", email: "archana.trisal@ins.ac.in" },
    E6009: { name: "Sajed Shaikh", email: "sajed.shaikh@ins.ac.in" },
    E6010: { name: "Dipali Koli", email: "dipali.koli@ins.ac.in" },
    E6011: { name: "Chandrakant Sathe", email: "csathe01@gmail.com" },
    E5984: { name: "Pallavi Patankar", email: "pallavi.patankar@INS.ac.in" },
    E6012: { name: "Garima Sinha", email: "garima.sinha@ins.ac.in" },
    E6013: { name: "Ranjita Yelmule", email: "ranjita.yelmule@ins.ac.in" },
    E6014: { name: "Nidashireen Khan", email: "Nidashireen.khan@ins.ac.in" },
    E6015: { name: "Pranali Waghmare", email: "Pranali.waghmare@ins.ac.in" },
    E6016: { name: "Samina Pathan", email: "samina.Pathan@ins.ac.in" },
    E6017: { name: "Lovita Dsouza", email: "lovita.dsouza@ins.ac.in" },
    E6018: { name: "Savita Mishra", email: "savita.mishra@ins.ac.in" },
    E6019: { name: "Pooja Patel", email: "POOJA.PATEL@INS.AC.IN" },
    E6023: { name: "Payal Gulati", email: "payal.gulati@ins.ac.in" },
    E6024: { name: "Chayanika Bhattacharjee", email: "chayanika.bhattacharjee@ins.ac.in" },
    E6025: { name: "Niki Mishra", email: "0.@ins.ac.in" }, // Invalid email
    E6026: { name: "Poonam Ingale", email: "poonam.ingale@ins.ac.in" },
    E6027: { name: "Santosh Naik", email: "santosh.naik@ins.ac.in" },
    E6028: { name: "Tuhin Goswami", email: "tuhin.goswami@ins.ac.in" },
    E6029: { name: "Santilata Kisku", email: "" },// Missing email
    //IGI Staff
    2066: { name: "Anand Ganpatrao Jumle", email: "principal@icacs.ac.in" },
    2897: { name: "Ashok Mulik", email: "ashikmulik2072@gmail.com" },
    2442: { name: "Deepa Madda", email: "deepamadda@gmail.com" },
    2177: { name: "Kiran Narayan Ghotkule", email: "kiran.ghotkule@icacs.ac.in" },
    2614: { name: "Namdev Mhetre", email: "namdev.mhetre@icacs.ac.in" },
    2377: { name: "Nisha Bhalchim", email: "nisha.bhalchim@icacs.ac.in" },
    2532: { name: "Prafulla Patil", email: "prafulla.patil@icacs.ac.in" },
    2165: { name: "Pratibha Nivrutti Bomble", email: "pratibha.bomble@icacs.ac.in" },
    2161: { name: "Priyanka Ramdas Sakhare", email: "priyanka.sakhare@icacs.ac.in" },
    2426: { name: "Radhika Nikhil Gandhe", email: "radhika.gandhe@icacs.ac.in" },
    1294: { name: "Sandesh Deshmukh", email: "sandesh.deshmukh@icacs.ac.in" },
    2795: { name: "Sushant Hande", email: "hande.sush@gmail.com" },
    2726: { name: "Swarupa Kulkarni", email: "swarupa.kulkarni@icacs.ac.in" },
    2896: { name: "Tejas Pawar", email: "tejas.pawar@icacs.ac.in" },
    116: { name: "Tushar S. Gaikwad", email: "gaikwadtushar392@gmail.com" },
    2794: { name: "Vaishnavi Sokate", email: "vaishnavi.sokate@icacs.ac.in" },
    2723: { name: "Vishal Kamthe", email: "vishal.kamathe@icacs.ac.in" },
    2984: { name: "Yogesh Sakhare", email: "yogeshsakhare1@icacs.ac.in" },
    2687: { name: "Abhijeet Vishwas Sankpal", email: "abhijeet.sankpal@iccs.ac.in" },
    2784: { name: "Anchal Abhinandan Satpute", email: "anchal.satpute@iccs.ac.in" },
    362: { name: "Ankush Ramchandra Jori", email: "ankush.jori@iccs.ac.in" },
    1814: { name: "Anushka Anil Chalke", email: "anushka.chalke@iccs.ac.in" },
    2239: { name: "Aparna Ashwin Jagtap", email: "aparna.jagtap@iccs.ac.in" },
    507: { name: "Ashish Govind Dhoke", email: "dhokeashish@iccs.ac.in" },
    E5446: { name: "Ashok Dashrath Lokhnade", email: "ashok.lokhande@indiranationalschool.ac.in" },
    E5593: { name: "Ashok Premnath Patil", email: "ashok.patil@indiranationalschool.ac.in" },
    2089: { name: "Ashwini Sachin Shivane", email: "ashwini.shivane@iccs.ac.in" },
    1659: { name: "Atul Sudam Bhondave", email: "atul.s.bhondve@iccs.ac.in" },
    1966: { name: "Bhakti Govind Shinde", email: "bhakti.shinde@iccs.ac.in" },
    2582: { name: "Chaitanya Tushar Palekar", email: "chaitanya.palekar@iccs.ac.in" },
    2232: { name: "Chaudhari Monali Milind", email: "monali.chaudhari@iccs.ac.in" },
    E5587: { name: "Datta Vishwanath Ransing", email: "datta.ransing@iccs.ac.in" },
    1253: { name: "Deepak Kishan Dahiwade", email: "deepak.dahiwade@iccs.ac.in" },
    2378: { name: "Deepali Devram Chaudhari", email: "deepali.chaudhari@iccs.ac.in" },
    449: { name: "Deepali Rishikesh Kulkarni", email: "deepalikulkarni@iccs.ac.in" },
    1971: { name: "Deven Prakash Mahajan", email: "deven.mahajan@iccs.ac.in" },
    2110: { name: "Dhanshri Sandip Kulkarni", email: "dhanashri.kulkarni@iccs.ac.in" },
    2652: { name: "Divya Mohan Bansari", email: "divya.bansari@iccs.ac.in" },
    1967: { name: "Ganesh Navanath Bhondve", email: "ganesh.bhondve@iccs.ac.in" },
    2875: { name: "Girish Rajan Jamdade", email: "girish.jamdade@iccs.ac.in" },
    2619: { name: "Hemant Naresh Rajesth", email: "hemant.rajesth@iccs.ac.in" },
    157: { name: "Jitendra Vishwanath Vaidya", email: "jitendra.vaidya@iccs.ac.in" },
    2665: { name: "Kadam Prajwal Raju", email: "prajwal.kadam@iccs.ac.in" },
    2263: { name: "Kakde Santosh Dnyanoba", email: "santosh.kakde@iccs.ac.in" },
    2644: { name: "Kalyani Ravindranath Naidu", email: "kalyani.naidu@iccs.ac.in" },
    2963: { name: "Limraina Saloman", email: "limraina.saloman@iccs.ac.in" },
    2926: { name: "Madhumita", email: "madhumita.sharma@iccs.ac.in" },
    773: { name: "Mahendra Eknath Pawar", email: "mahendra.pawar@iccs.ac.in" },
    10: { name: "Mangesh Narayan Kuman", email: "mangesh.kuman@iccs.ac.in" },
    2831: { name: "Mayuri Lakshman Mangade", email: "mayuri.mangade@iccs.ac.in" },
    2886: { name: "Milind Balasaheb Ghalme", email: "milind.ghalme@iccs.ac.in" },
    2371: { name: "Monika Jagannath Verma", email: "monikaverma@iccs.ac.in" },
    1976: { name: "Moushmi Pratap Dhumal", email: "moushmi.dhumal@iccs.ac.in" },
    2170: { name: "Nandu Bhaskar Sakhare", email: "nandu.sakhare@iccs.ac.in" },
    2830: { name: "Neha Satish Karade", email: "neha.karade@iccs.ac.in" },
    2709: { name: "Nikita Arjun Chavan", email: "nikita.chavan@iccs.ac.in" },
    2302: { name: "Nilesh Adinath Pawar", email: "nilesh.pawarexm@iccs.ac.in" },
    66: { name: "Nilesh Prakash Marne", email: "nilesh.marne@iccs.ac.in" },
    288: { name: "Nitin Manashing Phadatare", email: "nitin.phadtare@indiraisbs.ac.in" },
    2663: { name: "Pranav Namdev Pawar", email: "pranav.pawar@iccs.ac.in" },
    2294: { name: "Prashant Maruti Maske", email: "prashant.maskeit@iccs.ac.in" },
    1820: { name: "Prashant Rajaram Sawant", email: "prashantsawant@iccs.ac.in" },
    2648: { name: "Pravin Irappa Borgalli", email: "pravin.borgalli@iccs.ac.in" },
    2849: { name: "Priyavanda Jayesh Khanvilkar", email: "priyavanda.khanvilkar@iccs.ac.in" },
    2871: { name: "Rakamanna Annaraya Metakari", email: "rakamanna.metakari@iccs.ac.in" },
    307: { name: "Rashid Shahbuddin Shaikh", email: "shaikhrashid@iccs.ac.in" },
    2907: { name: "Saakshi Lunkad", email: "saakshi.lunkad@iccs.ac.in" },
    591: { name: "Sajosh Chandrasekharan P Nair", email: "sajosh.nair@indiragbs.edu.in" },
    2931: { name: "Sakapal Jagadish Baburao", email: "jagadisha.sakapal@iccs.ac.in" },
    2244: { name: "Sandip Vishwnath Adagale", email: "sandip.adagale@iccs.ac.in" },
    2491: { name: "Sanskruti Balasaheb Jodh", email: "sanskruti.jodh@iccs.ac.in" },
    332: { name: "Santoh Bhaskar Kulkarni", email: "santosh.kulkarni@iccs.ac.in" },
    2704: { name: "Sarika Dhananjay Shingate", email: "sarika.sawant@iccs.ac.in" },
    2: { name: "Satish Vithal Kamble", email: "satish.kamble@indiraiimp.edu.in" },
    1564: { name: "Saurabh Ganesh Pandey", email: "saurabh.pandey@iccs.ac.in" },
    2334: { name: "Saurav Kumar", email: "saurav.kumar@indiraedu.com" },
    946: { name: "Shantilal Tukaram Ghalme", email: "Shantilal.ghalme@iccs.ac.in" },
    2676: { name: "Sheetal Dattatraya Deshmukh", email: "sheetal.deshmukh@iccs.ac.in" },
    2917: { name: "Shilpa Mahesh Nawale", email: "shilpa.nawale@iccs.ac.in" },
    1137: { name: "Shilpa Shantaram Pawar", email: "shilpa.pawar@iccs.ac.in" },
    2240: { name: "Shilpa Suhas Pawale", email: "shilpa.pawale@iccs.ac.in" },
    2589: { name: "Shivam Dattatray Teli", email: "shivam.teli@iccs.ac.in" },
    1096: { name: "Shivani Sachin Sawant", email: "shivani.sawant@indiraedu.com" },
    75: { name: "Shivendu Rajendra Bhushan", email: "shivendu@iccs.ac.in" },
    2974: { name: "Shubham Sanjay Mane", email: "shubham.maneit@iccs.ac.in" },
    2111: { name: "Shweta Amol Bhoyate", email: "shweta.bhoyate@iccs.ac.in" },
    1711: { name: "Sneha Parag Pathak", email: "sneha.pathak@iccs.ac.in" },
    1969: { name: "Snehankita Pavankumar Shirdhone", email: "snehankita.majalekar@iccs.ac.in" },
    2912: { name: "Someshwar Popat Mahadik", email: "someshwar.mahadik@iccs.ac.in" },
    2901: { name: "Sourabh Bhagwan Shingade", email: "sourabh.shingade@iccs.ac.in" },
    2391: { name: "Sujay Shankar Karmakar", email: "sujay.karmakar@iccs.ac.in" },
    331: { name: "Sunil Someshwar Nandurkar", email: "sunil.nandurkar@iccs.ac.in" },
    2826: { name: "Supriya Darshan deshmukh", email: "supriya.deshmukh@iccs.ac.in" },
    3024: { name: "Supriya Watve", email: "supriya.watve@iccs.ac.in" },
    2600: { name: "Surabhi Rajesh Jain", email: "surabhi.jain@iccs.ac.in" },
    2938: { name: "Surekha Baburao Dhole", email: "surekha.dhole@iccs.ac.in" },
    18: { name: "Suresh Bajirao Gaikwad", email: "suresh.gaikwad@iccs.ac.in" },
    2617: { name: "Swati Soni", email: "swati.soni@iccs.ac.in" },
    1762: { name: "Tejas Namdev More", email: "tejas@iccs.ac.in" },
    2382: { name: "Tejas Shailendra Patil", email: "tejasspatil@iccs.ac.in" },
    2550: { name: "Tukaram Bapu Salokhe", email: "tukaram.salokhe@iccs.ac.in" },
    184: { name: "Udaysing Nathuram Satavekar", email: "udaykamble007@iccs.ac.in" },
    44: { name: "Vaijanath Punjaram Dhurandhare", email: "vaijinathd@iccs.ac.in" },
    2231: { name: "Varsha Ashish Khorgade (IKHE)", email: "varsha.ikhe@iccs.ac.in" },
    2659: { name: "Viitthal Sanjay Nemane", email: "vitthal.nemane@iccs.ac.in" },
    2252: { name: "Vijay Khema Jadhav", email: "vijayk.jadhav@iccs.ac.in" },
    2793: { name: "Vinayak Sambhaji More", email: "vinayak.more@iccs.ac.in" },
    2601: { name: "Vinita Kushwah", email: "vinita.kushwah@iccs.ac.in" },
    829: { name: "Vinita Shrivastava", email: "vinita.shrivastava@iccs.ac.in" },
    2850: { name: "Yogesh Bhausaheb Vyavahare", email: "yogesh.vyavahare@iccs.ac.in" },
    1139: { name: "Yogita Tukaram Sutar", email: "yogita.sutar@iccs.ac.in" },
    2523: { name: "Abhishek Omprakash Raidas", email: "abhishek.raidas@indiraiimp.edu.in" },
    2640: { name: "Ajit Gore", email: "ajit.gore@indiraiimp.edu.in" },
    2125: { name: "Ashwini Yadav", email: "ashwini.yadav@indiraiimp.edu.in" },
    67: { name: "Avinash Shantaram Sathe", email: "avinash.sathe@indiraiimp.edu.in" },
    1878: { name: "Chetan Ganjidhar Patil", email: "chetan.patil@indiraiimp.edu.in" },
    8: { name: "Chetan Hemchandra Chavan", email: "chetan.chavan@indiraiimp.edu.in" },
    2910: { name: "Chetan Vasant Varade", email: "chetan.varade@indiraaiimp.edu.in" },
    2367: { name: "Dinesh Dhumal", email: "dinesh.dhumal@indiraiimp.edu.in" },
    102: { name: "Ajay Varade", email: "ajay.varade@indiraiimp.edu.in" },
    2487: { name: "G Sakthivadivel", email: "gsakthivadivel@indiraiimp.edu.in" },
    1220: { name: "Geeta Brahmbhatt", email: "geeta.brahmbhatt@indiraedu.com" },
    2930: { name: "Jayesh Kharat", email: "jayesh.kharat@indiraedu.com" },
    1252: { name: "Jitesh Avtade", email: "jitesh.awatade@indiraiimp.edu.in" },
    2174: { name: "Jyoti Bhanage", email: "jyoti.bhanage@indiraiimp.edu.in" },
    2605: { name: "Jyoti Parase", email: "jyoti.parase@indiraiimp.edu.in" },
    2988: { name: "Komal Desai (Goyal)", email: "komal.desai@indiraiimp.edu.in" },
    2094: { name: "Kundan Bilade", email: "kundan.bilade@indiraiimp.edu.in" },
    897: { name: "Makarand Sawant", email: "makarand.sawant@indiraiimp.edu.in" },
    1946: { name: "Mayur Jaybhay", email: "mayur.jaybhay@indiraiimp.edu.in" },
    1948: { name: "Mehul Soudagar", email: "mmehuls@indiraiimp.edu.in" },
    1947: { name: "Leena Swanand Divashikar", email: "leena.divashikar@indiraiimp.edu.in" },
    2712: { name: "Nandani Shrivastav", email: "nandani.shrivastav@indiraiimp.edu.in" },
    2959: { name: "Patil Somnath Rajshekhar", email: "somanth.patil@indiraiimp.edu.in" },
    46: { name: "Pradeep Kharat", email: "pradeep_k@indiraiimp.edu.in" },
    2604: { name: "Pradyumna Inamdar", email: "pradyumna.inamdar@indiraiimp.edu.in" },
    1405: { name: "Prasad Chavan", email: "prasad.chavan@indiraiimp.edu.in" },
    2267: { name: "Priyanka Srivastava", email: "priyanka.srivastava@indiraiimp.edu.in" },
    2952: { name: "Rajeshwari Rajput", email: "rajeshwari.rajput@indiraiimp.edu.in" },
    2966: { name: "Sachin Sapkal", email: "sachin.sapkal@indiraiimp.edu.in" },
    370: { name: "Sakore Digamber Krishnaji", email: "dksakore@yahoo.com" },
    1398: { name: "Samita Ingle", email: "samita.ingle@indiraiimp.edu.in" },
    862: { name: "Sanjaykumar Jagannath Patil", email: "sanjaykumar.patil@indiraiimp.edu.in" },
    106: { name: "Santosh Pullewar", email: "santosh.pullewar@indiraiimp.edu.in" },
    2497: { name: "Savita Margale", email: "savita.margale@indiraiimp.edu.in" },
    234: { name: "Shefali Naidu", email: "shefalin@indiraedu.com" },
    28: { name: "Shirish Shukla", email: "shirish.shukla@indiraiimp.edu.in" },
    2699: { name: "Shrirang Sajanapwar", email: "shrirang.sajanapwar@indiraiimp.edu.in" },
    58: { name: "Sitabai Rathod", email: "sitabai.rathod@indiraiimp.edu.in" },
    2987: { name: "Smita Lahorkar", email: "smita.lahorkar@indiraiimp.edu.in" },
    1030: { name: "Sukhdev Kale", email: "sukhdev.kale@indiraiimp.edu.in" },
    104: { name: "Sulbha Bhanudas Waghmare", email: "sulbha.waghmare@indiraiimp.edu.in" },
    2531: { name: "Swati Bhole", email: "swati.bhole@indiraiimp.edu.in" },
    2225: { name: "Swayam Prakash Singh", email: "sp.singh@indiraiimp.edu.in" },
    2356: { name: "Vrinda Tushar Dingankar", email: "vrinda.dingankar@indiraiimp.edu.in" },
    19: { name: "Zumber Ovhal", email: "zumber.ovhal@indiraiimp.edu.in" },
    2834: { name: "Avinash Anurath Gawali", email: "avinash.gawali@indiraiimp.edu.in" },
    2420: { name: "Kishor Jaywant Waykar", email: "kishor.waykar@indiraisc.edu.in" },
    3019: { name: "Madhusudan Krishna Kate", email: "madhusudan.kate@indiraiimp.edu.in" },
    2935: { name: "Prity Sandeep Bidwai", email: "prity.bidwai@indiraiimp.edu.in" },
    996: { name: "Sharda Mahendra Wani", email: "sharda.wain@indiraisc.edu.in" },
    EMP0786: { name: "Aatish Dilip Zagade", email: "aatish.zagade@indiraigsb.edu.in" },
    EMP2989: { name: "Amarkant Baliyan", email: "amarkant.baliyan@indiraigsb.edu.in" },
    EMP2543: { name: "Amit Shashikant Kothari", email: "" },
    EMP2596: { name: "Amol Kundalik Ankush", email: "amol.ankush@indiraigsb.edu.in" },
    EMP2620: { name: "Aniruddha Vilas Thuse", email: "aniruddha.thuse@indiraigsb.edu.in" },
    EMP2354: { name: "Anuradha Samarth Phadnis", email: "anuradha.phadnis@indiraigsb.edu.in" },
    EMP2228: { name: "Ashish Bhimrao Jadhav", email: "ashish.jadhav@indiraigsb.edu.in" },
    EMP2889: { name: "Ashish Krishna Vyas", email: "Ashish.Vyas@indiraigsb.edu.in" },
    EMP0027: { name: "Bhagavan Shivaji Patil", email: "bhagavan.patil@indiragbs.edu.in" },
    EMP0213: { name: "Dinesh Vilas Khodke", email: "dinesh.khodke@indiraigsb.edu.in" },
    EMP2392: { name: "Girija Deepak Shirurkar", email: "Girija.shirurkar@indiraigsb.edu.in" },
    EMP2621: { name: "Jayant Arun Joshi", email: "Jayant.Joshi@indiraigsb.edu.in" },
    EMP2895: { name: "Jibin Balachandran Murikal", email: "jibin.murikal@indiraigsb.edu.in" },
    EMP1752: { name: "Kadam Jagannath Dhanaji", email: "jagannath.kadam@indiraigsb.edu.in" },
    EMP2237: { name: "Mahesh Ganpatrao Bhagat", email: "mahesh.bhagat@indiraigsb.edu.in" },
    EMP2990: { name: "Neelesh Madhukar Atre", email: "neelesh.atre@indiraigsb.edu.in" },
    EMP2905: { name: "Neha Chaudhry", email: "Neha.Chaudhry@indiraigsb.edu.in" },
    EMP0302: { name: "Nilesh Govind Yedre", email: "nilesh.yedre@indiraisbs.ac.in" },
    EMP0099: { name: "Pallavi Shrirang Sajanapwar", email: "dean.igsb@indiraigsb.edu.in" },
    EMP2233: { name: "Poonam Avinash Wani", email: "poonam.wani@indiraigsb.edu.in" },
    EMP2344: { name: "Prashant Dubey", email: "prashant.dubey@indiraigsb.edu.in" },
    EMP0725: { name: "Priyanka Rohan Darekar", email: "priyanka.darekar@indiraigsb.edu.in" },
    EMP2545: { name: "Rohan Ravindra Shinde", email: "rohan.shinde@indiraigsb.edu.in" },
    EMP1796: { name: "Santosh Vitthalrao Dagade", email: "Santosh.Dagade@indiraigsb.edu.in" },
    EMP2789: { name: "Shashwat Naresh Doshetti", email: "Shashwat.Doshetti@indiraigsb.edu.in" },
    EMP2593: { name: "Shinde Balasaheb Chhaburao", email: "balasaheb.shinde@indiraigsb.edu.in" },
    EMP2832: { name: "Snehal Ganesh Masurkar", email: "Snehal.Masurkar@indiraigsb.edu.in" },
    EMP2528: { name: "Solomon Sanjay Gaikwad", email: "solomon.gaikwad@indiraigsb.edu.in" },
    EMP2928: { name: "Ujjwala Ramesh Kamble", email: "ujjwala.kamble@indiraedu.com" },
    EMP0408: { name: "Virendra Vasant Tatake", email: "director@indiragbs.edu.in" },
    EMP1492: { name: "Yogesh Dilip Gheware", email: "yogesh.gheware@indiraigsb.edu.in" },
    2361: { name: "Akansha Mehta", email: "akanksha.mehta@indiraiimp.edu.in" },
    2257: { name: "Anand Lalitkumar Solanki", email: "anand.solanki@indiraedu.com" },
    2868: { name: "Bhagawan Dattu Dhole", email: "bhagwan.dhole@indiraiimp.edu.in" },
    189: { name: "Bhujang Maruti Maske", email: "bhujang.maske@indiraiimp.edu.in" },
    2424: { name: "Gajanan Arvind Nerkar", email: "gajanan.nerkar@indiraiimp.edu.in" },
    3000: { name: "Govind Ramdas Kamble", email: "govind.kamble@indiraiimp.edu.in" },
    2362: { name: "Grace Jemima Anandaraj", email: "grace.jemima@indiraiimp.edu.in" },
    2781: { name: "Jenny Sabu Puliken", email: "jenny.puliken@indiraiimp.edu.in" },
    2229: { name: "Jincy Biju", email: "jincybiju.bba@indiraiimp.edu.in" },
    2107: { name: "Kamlesh Kailashchandra Loat", email: "kamlesh.loat@indiraiimp.edu.in" },
    2359: { name: "Kiran Vitthal Samant", email: "kiran.samant@indiraiimp.edu.in" },
    2218: { name: "Poonam Pandit Pawar", email: "poonam.pawar@indiraiimp.edu.in" },
    2425: { name: "Pradnya Pradeep Yadav", email: "pradnya.yadav@indiraiimp.edu.in" },
    2520: { name: "Prajakta Abhijit Dani", email: "prajakta.dani@indiraiimp.edu.in" },
    2403: { name: "Prajakta Nilesh Kalyani", email: "prajakta.kalyani@indiraiimp.edu.in" },
    68: { name: "Prakash Ramchandra Bodke", email: "prakash.bodke@indiraiimp.edu.in" },
    1491: { name: "Prashant Madhav Satpute", email: "prashant.satpute@indiraiimp.edu.in" },
    2162: { name: "Pravin Pandurang Patil", email: "pravinpatil.bba@indiraiimp.edu.in" },
    2837: { name: "Rajeshwari Saraswat", email: "rajeshwari.saraswat@indiraiimp.edu.in" },
    2219: { name: "Rama Bhimrao Bhise", email: "rama.bhise@indiraiimp.edu.in" },
    2407: { name: "Ratnesh Shivaji Patil", email: "ratnesh.patil@indiraiimp.edu.in" },
    2612: { name: "Sagarraj Giridhar Tambade", email: "sagarraj.tambade1@indiraiimp.edu.in" },
    2381: { name: "Sareet Kunden", email: "sareet.kunden@indiraiimp.edu.in" },
    2101: { name: "Subhan Maruti Maske", email: "subhan.maske@indiraiimp.edu.in" },
    2951: { name: "Swanand Laxmanrao Raut", email: "swanand.raut@indiraiimp.edu.in" },
    127: { name: "Abdul Salim Karim Shaikh", email: "salim.shaikh@indiraicp.edu.in" },
    2853: { name: "Abhishek Dhananjay Bachkar", email: "abhishek.bachkar@indiraicp.edu.in" },
    2804: { name: "Aishwarya Ashutosh Huparikar", email: "aishwarya.huparikar@indiraicp.edu.in" },
    2810: { name: "Akshada Bharat Murkute", email: "akshadamurkute@indiraicp.edu.in" },
    2060: { name: "Akshaya Kumar Dash", email: "akshaya.dash@indiraicp.edu.in" },
    492: { name: "Amir Afzal Shaikh", email: "amir.shaikh@indiraicp.edu.in" },
    2785: { name: "Anant Satish Phatak", email: "anant.phatake@indiraicp.edu.in" },
    1915: { name: "Anjali Sameer Naik", email: "anjali.naik@indiraicp.edu.in" },
    2819: { name: "Anmaria Thomas", email: "anmaria.thomas@indiraicp.edu.in" },
    1234: { name: "Archana Mukul Karnik", email: "archana.karnik@indiraicp.edu.in" },
    806: { name: "Bhagyesh Hari Wakalkar", email: "b.wakalkar@indiraisbs.ac.in" },
    128: { name: "Dattatray Maruti Dhamale", email: "datta.dhamale@indiraicp.edu.in" },
    2851: { name: "Dinesh Subhashsing Girase", email: "dinesh.girase@indiraicp.edu.in" },
    2044: { name: "Falguni Chirag Mistry", email: "falguni.mistry@indiraicp.edu.in" },
    2995: { name: "Gayatri Satish Borge", email: "gayatri.borge@indiraicp.edu.in" },
    3006: { name: "Harshali Bhanudas Dhaygude", email: "harshali.dhaygude@indiraicp.edu.in" },
    1910: { name: "Jagruti Ramesh Jadhav", email: "jagruti.jadhav@indiraicp.edu.in" },
    3005: { name: "Komal Dattatray Pol", email: "komal.pol@indiraicp.edu.in" },
    1209: { name: "Kushabhau Dadasaheb Pathak", email: "kushabhau.pathak@indiraicem.ac.in" },
    1032: { name: "Madhur Chandrashekhar Kulkarni", email: "madhur.kulkarni@indiraicp.edu.in" },
    2654: { name: "Mahadev Ashru Kamble", email: "mahadev.kamble@indiraicp.edu.in" },
    164: { name: "Milind Shankar Khedkar", email: "milind.khedkar@indiraicp.edu.in" },
    2841: { name: "Namrata Narsingrao Shinde", email: "namrata.shinde@indiraicp.edu.in" },
    2946: { name: "Nikita Anand Sadalage", email: "nikita.sadalage@indiraicp.edu.in" },
    691: { name: "Nilesh Manohar Pasalkar", email: "nilesh.pasalkar@indiraicp.edu.in" },
    2813: { name: "Nishigandha Jayant Waykule", email: "nishigandhawaykule@indiraicp.edu.in" },
    2802: { name: "Nupuri Ashok Joshi", email: "nupuri.joshi@indiraicp.edu.in" },
    2510: { name: "Pooja Janardan", email: "pooja.janardan@indiraicp.edu.in" },
    112: { name: "Pramod Vitthal Sakhare", email: "pramodsakhare@iccs.ac.in" },
    2968: { name: "Prashant Naganath Ghodake", email: "prashant.ghodake@indiraicp.edu.in" },
    1787: { name: "Rahul Subhash Buchade", email: "rahul.buchade@indiraicp.edu.in" },
    1691: { name: "Rajkamal Manohar Kakade", email: "rajkamal.kakade@indiraicp.edu.in" },
    2717: { name: "Riya Sagar Banerjee", email: "riya.banerjee@indiraicp.edu.in" },
    1726: { name: "Rohit Jagannath Gunjal", email: "rohit.gunjal@indiraicp.edu.in" },
    1512: { name: "Roopal Sunil Bhat", email: "roopal.bhat@indiraicp.edu.in" },
    1181: { name: "Rutuja Vijay Kamble", email: "rutuja.sonawane@indiraicp.edu.in" },
    2706: { name: "Sakshi Dharmendrasingh Chauhan", email: "sakshi.chauhan@indiraicp.edu.in" },
    2062: { name: "Samadhan Gautam Ingle", email: "samadhan.ingle@indiraicp.ed" },
    1162: { name: "Samadhan Tatyaram Tupare", email: "samadhan.tupare@indiraicp.edu.in" },
    2635: { name: "Sanjay Abaji Vibhute", email: "sanjay.vibhute@indiraicp.edu.in" },
    2342: { name: "Sayali Deepak Dhamal", email: "sayalidhamal@indiraicp.edu.in" },
    2416: { name: "Sayali Santosh More", email: "sayali.more@indiraicp.edu.in" },
    2874: { name: "Sayli Uday Wankhade", email: "sayli.wankhade@indiraicp.edu.in" },
    3004: { name: "Shivani Dilip Patil", email: "shivani.patil@indiraicp.edu.in" },
    2807: { name: "Shivkanya Sanjay Chandrawanshi", email: "shivkanya.chandrawanshi@indiraicp.edu.in" },
    2878: { name: "Shridhar Suresh Pandkar", email: "shridharpandkar@indiraicp.edu.in" },
    3003: { name: "Siddheya Ravindra Uttarwar", email: "siddheya.uttarwar@indiraicp.edu.in" },
    2816: { name: "Smita Datta Kadam", email: "smita.kadam@indiraicp.edu.in" },
    2801: { name: "Smita Sameer Shimpi", email: "smita.shimpi@indiraicp.edu.in" },
    2842: { name: "Snehal Rajendra Thakar", email: "snehal.thakar@indiraicp.edu.in" },
    2818: { name: "Snehal Sanjay Birajdar", email: "snehal.birajdar@indiraicp.edu.in" },
    1341: { name: "Sunil Ramhari Kakad", email: "sunil.kakad@indiraicp.edu.in" },
    2977: { name: "Sushil Sunil Gaikwad", email: "sushil.gaikwad@indiraicp.edu.in" },
    359: { name: "Suvarna Pramod Ingale", email: "suvarna.ingle@indiraicp.edu.in" },
    2918: { name: "Swati Somesh Bhalerao", email: "swati.bhalerao@indiraicp.edu.in" },
    1701: { name: "Tejal Nikhil Bele", email: "tejal.mulay@indiraicp.edu.in" },
    2929: { name: "Yogesh Manilal Patil", email: "yogesh.patil@indiraedu.com" },
    2877: { name: "Abhilash Sanjay Kasbe", email: "Abhilash.Kasbe@indiraisbs.edu.in" },
    2825: { name: "Amar Chandrakant Pawar", email: "amar.pawar@indiraisbs.edu.in" },
    1548: { name: "Amrita Sunny Karnawat", email: "amrita.karnawat@indiraisbs.ac.in" },
    3014: { name: "Arun Dattatray Kanekar", email: "arun.kanekar@indiraisbs.edu.in" },
    1892: { name: "Arvind Laxman Burande", email: "arvind.burande@indiraisbs.ac.in" },
    2039: { name: "Avinash Shesherao Rathod", email: "avinash.rathod@indiraisbs.edu.in" },
    1197: { name: "Dayanand Fulchand Kamble", email: "dayanand.kamble@indiraisbs.ac.in" },
    3032: { name: "Dilip Waman Rathod", email: "dilip.rathod@indiraisbs.edu.in" },
    2346: { name: "Hetal Nitin Bhinde", email: "hetal.bhinde@indiraisbs.edu.in" },
    2401: { name: "Jai Tushar Lunkad", email: "NA" },
    2402: { name: "Tushar Lunkad", email: "NA" },
    1494: { name: "Komal Baljinder Singh", email: "komal.singh@indiraisbs.ac.in" },
    228: { name: "Lahu Panditrao Jadhav", email: "lahu.jadhav@indiraisbs.ac.in" },
    2145: { name: "Manisha Mandar Maddel", email: "manisha.maddel@indiraisbs.edu.in" },
    2779: { name: "Manjali Prafulla Tehare", email: "manjali.tehare@indiraisbs.edu.in" },
    2345: { name: "Manoj Mallinath Singe", email: "manoj.singe@indiraisbs.edu.in" },
    647: { name: "Nayana Madhusudan Moray", email: "nayana.more@indiraisbs.ac.in" },
    2677: { name: "Nilesh Sakharam Joshi", email: "nilesh.joshi@indiraisbs.edu.in" },
    1856: { name: "Purva Shirish Agarwal", email: "purva.agarwal@indiraisbs.ac.in" },
    2678: { name: "Roopesh Gupta", email: "roopesh.gupta@indiraisbs.edu.in" },
    2226: { name: "Rushikesh Sunil Pawade", email: "rushikesh.pawade@indiraisbs.edu.in" },
    2292: { name: "Sagar Vilas Jadhav", email: "sagar.jadhav@indiraisbs.ac.in" },
    2909: { name: "Sandeep Nagorao Kangule", email: "Sandeep.Kangule@indiraisbs.edu.in" },
    2941: { name: "Sarang Suryakant Gutte", email: "sarang.gutte@indiraisbs.edu.in" },
    1274: { name: "Sharvari Sachin Ratnakar", email: "sharvari.ratnakar@indiraisbs.ac.in" },
    2486: { name: "Simarpreet Kaur", email: "simarpreet.kaur@indiraisbs.edu.in" },
    2876: { name: "Sweta Shivani", email: "Sweta.Shivani@indiraisbs.edu.in" },
    2008: { name: "Trupti Mandar Joshi", email: "trupti.joshi@indiraisbs.edu.in" },
    155: { name: "Umesh Pralhad Gujar", email: "umesh.gujar@indiraicad.ac.in" },
    2791: { name: "Aishwarya Pawar", email: "aishwarya.pawar@indiraisbs.ac.in" },
    5609: { name: "Ambarai Mane", email: "ambarai.mane@indiranationalschool.ac.in" },
    385: { name: "Amol Varpe", email: "amol.varpe@indiraisbs.ac.in" },
    2885: { name: "Anant Kadu", email: "anant.kadu@indiraisbs.ac.in" },
    692: { name: "Anjaneya Guru", email: "anjaneya.guru@indiraisbs.ac.in" },
    2711: { name: "Anuja Patil", email: "anuja.patil@indiraedu.com" },
    2919: { name: "Anup Jadhav", email: "anup.jadhav@indiraisbs.ac.in" },
    322: { name: "Arpana Boodle", email: "arpanaboodle@indiraicem.ac.in" },
    2668: { name: "Ashish Shrivastava", email: "ashish.shrivastava@indiraisbs.ac.in" },
    2862: { name: "Bhagyashri Patil", email: "bhagyashri.patil@indiraisbs.ac.in" },
    2132: { name: "Bhushan Patil", email: "bhushan.patil@indiraisbs.ac.in" },
    575: { name: "Chanakya Kumar", email: "chanakya.kumar@indiraisbs.ac.in" },
    3026: { name: "Chetan Khairnar", email: "chetan.khairnar@indiraisbs.ac.in" },
    2975: { name: "Chhaya Gaikwad", email: "chhaya.gaikwad@indiraisbs.ac.in" },
    4501: { name: "Darshana Metange", email: "darshana.metange@indiraedu.com" },
    3002: { name: "Mohd Hammad Naeem", email: "hammad.naeem@indiraisbs.ac.in" },
    664: { name: "Durairaj Nadar", email: "durairaj@indiraedu.com" },
    2719: { name: "Kasturi Dutt", email: "kasturi.dutt@indiraisbs.ac.in" },
    1589: { name: "Madhura Godbole", email: "madhura.godbole@indiranationalschool.ac.in" },
    2954: { name: "Mazhar Ali Meer", email: "mazhar.meer@indiraisbs.ac.in" },
    114: { name: "Muddasar Khan", email: "muddasar.khan@indiraisbs.ac.in" },
    2797: { name: "Mussarat Shah", email: "mussarat.shah@indiraisbs.ac.in" },
    1401: { name: "Neetu Randhawa", email: "neetu.randhawa@indiraisbs.ac.in" },
    574: { name: "Parmeshwar Yadav", email: "parmeshwar.yadav@indiraisbs.ac.in" },
    2955: { name: "Parth Hajare", email: "parth.hajare@indiraisbs.ac.in" },
    1906: { name: "Pranay Chavan", email: "pranay.chavan@indiraisbs.ac.in" },
    1961: { name: "Prashant Kalaskar", email: "prashant.kalaskar@indiraisbs.ac.in" },
    2911: { name: "Prashant Karke", email: "prashant.karke@indiraisbs.ac.in" },
    2904: { name: "Prince Yadav", email: "prince.yadav@indiraisbs.ac.in" },
    2906: { name: "Priyanka Jarolia", email: "priyanka.jarolia@indiraisbs.ac.in" },
    431: { name: "Rajlaxmi Pujar", email: "rajlakshmi.pujar@indiraisbs.ac.in" },
    802: { name: "Rajyavardhan Tater", email: "rajyavardhan.tater@indiraisbs.ac.in" },
    736: { name: "Rakesh Shelar", email: "rakesh.shelar@iccs.ac.in" },
    1255: { name: "Ravindra Kate", email: "ravindra.kate@indiraisbs.ac.in" },
    11: { name: "Renu Bhargava", email: "renub@indiraedu.com" },
    2144: { name: "Rishikesh Nalawade", email: "rishikesh.nalawade@indiraisbs.ac.in" },
    2674: { name: "Rohit Sayanak", email: "rohit.sayanak@indiraisbs.ac.in" },
    2855: { name: "Rupali Huggi", email: "rupali.huggi@indiraedu.com" },
    3013: { name: "Ruturaj Naikde", email: "ruturaj.naikade@indiraisbs.ac.in" },
    36: { name: "Santosh Kumar", email: "skumar@indiraedu.com" },
    1547: { name: "Santosh Yadav", email: "santosh.yadav@indiraisbs.ac.in" },
    2673: { name: "Saurabh Mohite", email: "saurabh.mohite@indiraisbs.ac.in" },
    2657: { name: "Shankar Bhapkar", email: "shankar.bhapkar@indiraisbs.ac.in" },
    545: { name: "Shirly Abraham", email: "shirly.abraham@indiraisbs.ac.in" },
    1800: { name: "Shobha Shinde", email: "shobha.pophalkar@indiraisbs.ac.in" },
    2710: { name: "Shruti Agalave", email: "shruti.aglave@indiraedu.com" },
    2892: { name: "Shubhada Tathe", email: "shubhada.tathe@indiraedu.com" },
    2108: { name: "Smrutiranjan Mohanty", email: "sr.mohanty@indiraisbs.ac.in" },
    2667: { name: "Sonali Jadhav", email: "sonali.jadhav@indiraisbs.ac.in" },
    2800: { name: "Sujata Deshmukh", email: "sujata.deshmukh@indiraisbs.ac.in" },
    2579: { name: "Suraj Chavan", email: "suraj.chavan@indiraisbs.ac.in" },
    2379: { name: "Swapnil Koli", email: "koliswapnil11@gmail.com" },
    2939: { name: "Tushar Kalne", email: "tushar.kalne@indiraisbs.ac.in" },
    2934: { name: "Udaysingh Pawar", email: "udaysingh.pawar@indiraisbs.ac.in" },
    15: { name: "Upendra Katageri", email: "upen_katageri@indiraedu.com" },
    2139: { name: "Vajesing Patil", email: "vajesing.patil@indiraisbs.ac.in" },
    1854: { name: "Varsha Manish Bihade", email: "varsha.bihade@indiraisbs.ac.in" },
    5607: { name: "Varsharani Mane", email: "varsharani.mane@indiranationalschool.ac.in" },
    62: { name: "Vilas Kamble", email: "vilas.kamble@indiraisbs.ac.in" },
    2284: { name: "Abhay Anant Kurgund", email: "abhay.kurgund@indiraicem.ac.in" },
    2764: { name: "Aishwarya Ashutosh Huparikar", email: "aishwarya.huparikar@icp.edu.in" },
    2735: { name: "Aditya Sanjay Mhalaskar", email: "aditya.mhalaskar@indiraicem.ac.in" },
    2739: { name: "Aishwarya Bhimrao Patil", email: "aishwarya.patil@indiraicem.ac.in" },
    2923: { name: "Akshada Ashok Dhumal", email: "akshada.dhumal@indiraedu.com" },
    2729: { name: "Akshay Sitaram Surve", email: "akshay.surve@indiraicem.ac.in" },
    482: { name: "Amar Buwasaheb Bhote", email: "amar.bhote@indiraicem.ac.in" },
    1519: { name: "Amit Gangadhar Narwade", email: "amit.narwade@indiraicem.ac.in" },
    435: { name: "Anil Anandrao Jadhav", email: "anil.jadhav@indiraicem.ac.in" },
    2742: { name: "Anita Atul Patil", email: "anita.patil@indiraicem.ac.in" },
    206: { name: "Anita Kishor Chavan", email: "anita.chavan@indiraicem.ac.in" },
    246: { name: "Anita Tukaram Surve", email: "anita.surve@indiraicem.ac.in" },
    3007: { name: "Ankita Sunil Shinde", email: "shinde.ankita@indiraicem.ac.in" },
    479: { name: "Ankush Gautam Kadam", email: "ankush.kadam@indiraicem.ac.in" },
    31: { name: "Anup Jagannath Vaidya", email: "anup.vaidya@indiraiimp.edu.in" },
    2771: { name: "Apeksha Suresh Giri", email: "apeksha.giri@indiraicemac.in" },
    1521: { name: "Archana Ravindra Salve", email: "sagar.chirade@indiraicem.ac.in" },
    2777: { name: "Arun Vijay Lad", email: "arun.lad@indiraicem.ac.in" },
    2774: { name: "Ashish Ashok Khole", email: "ashish.khole@indiraicem.ac.in" },
    1290: { name: "Ashwin Shriram Dharme", email: "ashwin.dharme@indiraicem.ac.in" },
    964: { name: "Ashwini Atul Admane", email: "ashwini.admane@icem.ac.in" },
    2915: { name: "Ashwini Devanand Wankhade", email: "ashwini.wankhade@indiraicem.ac.in" },
    1456: { name: "Ashwini Sadashiv Gaikwad", email: "ashwini.gaikwad@icem.ac.in" },
    2730: { name: "Atul Dnyanoba Shelar", email: "atul.shelar@indiraicem.ac.in" },
    1360: { name: "Atul Kundlik Gore", email: "atul.gore@icem.ac.in" },
    277: { name: "Atul Shrinivas Talashikar", email: "atul.talashikar@indiraicem.ac.in" },
    1516: { name: "Avinash Santram Bansode", email: "avinash.bansode@icem.ac.in" },
    1975: { name: "Awantika N.Bijwe", email: "awantika.bijwe@icem.ac.in" },
    3017: { name: "B.Ujwal Shetty", email: "ujwal.shetty@indiraicem.ac.in" },
    1415: { name: "Babu Banaji Botre", email: "babu.botre@indiraicem.ac.in" },
    2944: { name: "Balu Chatrbhuj Tandale", email: "balu.tandale@indiraicem.ac.in" },
    177: { name: "Balu Sakharam Rathod", email: "balu.rathod@indiraicem.ac.in" },
    286: { name: "Bashir Rajasab Sumbad", email: "bashir.sombad@indiraicem.ac.in" },
    2985: { name: "Bhimrao Babasaheb Bhosale", email: "bhimrao.bhosale@indiraicem.ac.in" },
    1011: { name: "Darshanaben Jignesh Desai", email: "darshanaben.desai@icem.ac.in" },
    2213: { name: "Dattatraya Ashok Dabhade", email: "dattatray.dabhade@indiraicem.ac.in" },
    261: { name: "Dattatraya Atmaram Bhalerao", email: "dattatray.bhalerao@indiraicem.ac.in" },
    2736: { name: "DattatrayaTukaram Ovhal", email: "dattatray.ovhal@indiraicem.ac.in" },
    2956: { name: "Debasish Ghosh", email: "debasishghosh@indiraicem.ac.in" },
    1680: { name: "Deepa Nitin Jamnik", email: "deepa.jamnik@icem.ac.in" },
    2751: { name: "Deepa Vishal Padwal", email: "deepa.padwal@icem.ac.in" },
    496: { name: "Deepali Shashikant Dhadwad", email: "deepali.dhadwad@icem.ac.in" },
    2343: { name: "Dhanashree Vishal Pisal", email: "dhanashree.pisal@icem.ac.in" },
    393: { name: "Dhiraj Shashikant Bhagwate", email: "dhiraj.bhagwate@icem.ac.in" },
    2772: { name: "Dinesh Bansilal Deore", email: "dinesh.deore@indiraicem.ac.in" },
    2846: { name: "Dinkar Kisan Choudhari", email: "dinkar.choudhari@indiraicem.ac.in" },
    2750: { name: "Dipak Raju Raut", email: "dipak.raut@icem.ac.in" },
    2288: { name: "Dipali Nikhil Junankar", email: "dipali.junankar@icem.ac.in" },
    2957: { name: "Dipali Rahul Nimbalkar", email: "dipali.nimbalkar@indiraicem.ac.in" },
    2749: { name: "Harshal Chandrashekhar Mahajan", email: "harshal.mahajan@icem.ac.in" },
    422: { name: "Hemant Vasant Darokar", email: "hemant.darokar@icem.ac.in" },
    2854: { name: "Hetal Hardik Thaker", email: "hetal.thaker@indiraicem.ac.in" },
    2770: { name: "Indrajeet Balasaheb Babar", email: "indrajeet.babar@indiraicem.ac.in" },
    592: { name: "Jorasingh Gurucharan Sidhu", email: "jorasingh.sidhu@icem.ac.in" },
    2943: { name: "Jyoti ranjan Bal", email: "jyotiranjan.bal@indiraicem.ac.in" },
    3015: { name: "Karan Mohan Gaikwad", email: "karan.gaikwad@indiraicem.ac.in" },
    1883: { name: "Kiran Dattatray Devade", email: "kiran.devade@icem.ac.in" },
    2728: { name: "Kiran Vithoba Bhote", email: "kiran.bhote@indiraicem.ac.in" },
    203: { name: "Kishor Haribhau Chavan", email: "kishor.chavan@indiraicem.ac.in" },
    2758: { name: "Kulkarni Vaibhav Vijaykumar", email: "kulkarni.vijaykumar@icem.ac.in" },
    215: { name: "Mahesh Ganpat Bhong", email: "mahesh.bhong@icem.ac.in" },
    521: { name: "Mahesh Mahadev Mahamunkar", email: "mahesh.mahamunkar@indiragbs.edu.in" },
    2859: { name: "Malayaj Kumar", email: "malayaj.kumar@indiraicem.ac.in" },
    2760: { name: "Mandakini Sanjay Dahiwade", email: "dipali.junankar@indiraicem.ac.in" },
    2869: { name: "Mani Shankar Pandey", email: "manishankar.pandey@indiraicem.ac.in" },
    176: { name: "Manish Sakharam Patel", email: "manish.patel@indiraiimp.edu.in" },
    3016: { name: "Manisha Aburao Dhiwar", email: "manisha.dhiwar@icem.ac.in" },
    984: { name: "Manjusha Ashwin Tomar", email: "manjusha.tomar@icem.ac.in" },
    472: { name: "Manjusha Rahul Tatiya", email: "manjusha.tatiya@icem.ac.in" },
    2737: { name: "Manoj Laxman Sutar", email: "manoj.sutar@indiraicem.ac.in" },
    2649: { name: "Manoj Ram", email: "manoj.ram@icem.ac.in" },
    312: { name: "Meenakshi Somnath Patil", email: "meenakshi.patil@icem.ac.in" },
    2873: { name: "Menoki Vidya Jaykumar", email: "vidya.minoki@indiraicem.ac.in" },
    2744: { name: "Minal Pravin Jungare", email: "minal.jungare@icem.ac.in" },
    2864: { name: "Minal Sunil Patil", email: "patil.minal@indiraicem.ac.in" },
    1522: { name: "Narayan Shankar Jundre", email: "narayan.jundre@icem.ac.in" },
    2539: { name: "Neha Prakash Choudhary", email: ":neha.choudhary@indiraicem.ac.in" },
    2860: { name: "Nilesh Avinash Joshi", email: "nilesh.joshi@indiraicem.ac.in" },
    2787: { name: "Nilesh Janardan Uke", email: "nilesh.uke@icem.ac.in" },
    204: { name: "Nitinkumar Hindurao Khandait", email: "nitin.khandait@indiraicem.ac.in" },
    2752: { name: "Pallavi Laxmikant Chavan", email: "pallavi.chavan@icem.ac.in" },
    2072: { name: "Poorna Shankar", email: "poorna.shankar@icem.ac.in" },
    2743: { name: "Pragati Sambhaji Malusare", email: "pragati.malusare@icem.ac.in" },
    2847: { name: "Pragati Yuvraj Kharbade", email: "pragati.kharbade@indiraicem.ac.in" },
    1288: { name: "Pranali Rahul Rote", email: "pranali.rote@icem.ac.in" },
    2748: { name: "Pranjali Nilkanthrao Manmode", email: "pranjali.manmode@icem.ac.in" },
    2773: { name: "Prasad Sanjay Jadhav", email: "prasad.jadhav@indiraicem.ac.in" },
    2211: { name: "Pratap Bhagwant Gadekar", email: "pratap.gadekar@indiraicem.ac.in" },
    465: { name: "Pratima Amrut Gaikwad", email: "pratima.gaikwad@icem.ac.in" },
    265: { name: "Pravin Devidas Charde", email: "pravin.charde@indiraicem.ac.in" },
    2763: { name: "Pravin Namdeo Thorat", email: "pravin.thorat@icem.ac.in" },
    2734: { name: "Priti Abhijit Shinde", email: "priti.shinde@indiraicem.ac.in" },
    2300: { name: "Priya Jeevan Pise", email: "priya.pise@icem.ac.in" },
    987: { name: "Priyanka Amol Pawar", email: "priyanka.pawar@icem.ac.in" },
    2845: { name: "Priyanka Harshal Mahajan", email: "priyanka.mahajan@indiraicem.ac.in" },
    2973: { name: "Priyanka Kiran Sonar", email: "priyanka.sonar@indiraicem.ac.in" },
    2741: { name: "Priyanka Nagesh Shingade", email: "priyanka.shingade@indiraicem.ac.in" },
    2848: { name: "Priyanka Ramesh Patil", email: "patilpriyanka@indiraicem.ac.in" },
    2765: { name: "Priyanka Shirish Shinde", email: "priyanka.shinde@icem.ac.in" },
    2341: { name: "Reshma Parag Kohad", email: "reshma.kohad@icem.ac.in" },
    2778: { name: "Radheyshyam Choudhary", email: "radheyshyam.choudhary@indiraicem.ac.in" },
    2887: { name: "Raghunandan Vinayakrao Kale", email: "raghunandan.kale@indiraicem.ac.in" },
    2733: { name: "Raj Uttam Gajarmal", email: "raj.gajarmal@indiraicem.ac.in" },
    2732: { name: "Ravindra Shantaram Ghare", email: "ravindra.ghare@indiraicem.ac.in" },
    2775: { name: "Reshma Prabhakar Chopade", email: "reshma.chopade@indiraicem.ac.in" },
    2708: { name: "Rohit Arvind Deshmukh", email: "rohit.deshmukh@indiraicem.ac.in" },
    2993: { name: "Roshni Rohidas Bhalerao", email: "roshni.bhalerao@indiraicem.ac.in" },
    2746: { name: "Rupali Pravin Adhau", email: "rupali.adhau@icem.ac.in" },
    372: { name: "Rupali Vilas Salunke", email: "rupali.salunke@icem.ac.in" },
    1486: { name: "Sachin Bhaskar Ugalmugale", email: "sachin.ugalmugale@indiraicem.ac.in" },
    2788: { name: "Sagar Balasaheb Botre", email: "sagar.botre@indiraicem.ac.in" },
    1520: { name: "Sagar Uttamrao Chirade", email: "sagar.chirade@icem.ac.in" },
    2606: { name: "Saurabh Harishchand Gupta", email: "saurabh.gupta@icem.ac.in" },
    201: { name: "Santosh Dada Sawant", email: "santosh.sawant@indiraicem.ac.in" },
    2891: { name: "Santosh Namdeo Khokarale", email: "santosh.khokarale@indiraicem.ac.in" },
    2925: { name: "Santosh Sakharam Shinde", email: "santosh.shinde@indiraicem.ac.in" },
    2840: { name: "Sapna Shrikrishna Dahake", email: "sapna.dahake@indiraicem.ac.in" },
    2290: { name: "Sarika Sanjay Choudhari", email: "sarika.choudhari@indiraicem.ac.in" },
    2731: { name: "Sarita Hemant Pardeshi", email: "sarita.pardeshi@indiraicem.ac.in" },
    2890: { name: "Satyam Sanjay Gaikawad", email: "satyam.gaikawad@indiraicem.ac.in" },
    2757: { name: "Satyam Shamrao Kalyane", email: "pallavi.chavan@indiraicem.ac.in" },
    1200: { name: "Savita Achyut Jangale", email: "savita.jangale@icem.ac.in" },
    2745: { name: "Savitri Ashok Mote", email: "savitri.mote@icem.ac.in" },
    743: { name: "Shivaji Subhash Patil", email: "shivaji.patil@indiraicem.ac.in" },
    2747: { name: "Shraddha Sandip Suryawanshi", email: "shraddha.suryawanshi@icem.ac.in" },
    2768: { name: "Shreya Sohan Shenai", email: "shreya.shenai@icem.ac.in" },
    2879: { name: "Shraddha Vishnu Murade", email: "shraddha.murade@indiraicem.ac.in" },
    2754: { name: "Shreyas Rajendra Satpute", email: "shreyas.satpute@indiraicem.ac.in" },
    2965: { name: "Shriya Ajay Ketkar", email: "shriya.ketkar@indiraicem.ac.in" },
    624: { name: "Shubhangi Jagdish Kamble", email: "shubhangi.kamble@icem.ac.in" },
    2197: { name: "Shwetkranti Sushant Gaikwad", email: "shwetkranti.gaikwad@icem.ac.in" },
    643: { name: "Siddheshwar Suresh Shirbhate", email: "siddheshwar.shirbhate@icem.ac.in" },
    474: { name: "Somnath Nivrutti Bhote", email: "somnath.bhote@indiraicem.ac.in" },
    244: { name: "Sonali Shashank Pradhan", email: "sonali.pradhan@indiraicem.ac.in" },
    2032: { name: "Soumitra Shibshankar Das", email: "soumitra.das@icem.ac.in" },
    2776: { name: "Sudhir Sawarkar", email: "sudhir.sawarkar@icem.ac.in" },
    2366: { name: "Sunil Damodar Rathod", email: "sunil.rathod@icem.ac.in" },
    2208: { name: "Sunil Sudam Phuge", email: "sunil.phuge@indiraicem.ac.in" },
    645: { name: "Supriya Deepak Kumbhar", email: "supriya.kumbhar@icem.ac.in" },
    2863: { name: "Suresh Mohanrao Renge", email: "suresh.renge@indiraicem.ac.in" },
    594: { name: "Sushil B.Chopade", email: "sushil.chopade@icem.ac.in" },
    2888: { name: "Swapnil Machhindra Chaudhari", email: "swapnil.chaudhari@indiraicem.ac.in" },
    2767: { name: "Tejas Chandrakant Pawar", email: "tejas.pawar@icem.ac.in" },
    1326: { name: "Vijay Kumar Saini", email: "vijay.saini@icem.ac.in" },
    2881: { name: "Trupti Nandkumar Kathale", email: "trupti.kathale@indiraicem.ac.in" },
    2986: { name: "Vijay Dattatray Sinalkar", email: "Vijay.Sinalkar@indiraicem.ac.in" },
    2195: { name: "Vikas Narayan Nandgaonkar", email: "vikas.nandgaonkar@indiraicem.ac.in" },
    739: { name: "Vishal Abhiman Meshram", email: "siddheshwar.shirbhate@indiraicem.ac.in" },
    117: { name: "Vivek Shivanand Ganmukhi", email: "vivek.ganmukhi@indiraedu.com" },
    2755: { name: "Vrushali Satyajit Patil", email: "vrushali.patil@icem.ac.in" },
    2337: { name: "Sarita Wakalkar", email: "sarita.wakalkar@icem.ac.in" },
    2642: { name: "Nitu Rosha", email: "nitu.rosha@indiraedu.com" },
    2867: { name: "Swapna Amit Dixit", email: "swapna.dixit@indiraisa.com" },
    1: { name: "Tarita Shankar", email: "taritashankar@gmail.com" },
    4: { name: "Chetan Wakalkar", email: "cwakalkar@indiraedu.com" },
    5606: { name: "Sahil Mehendale", email: "sahilmehendale@gmail.com" },
    2786: { name: "Shardul Gangal", email: "shardul@indiraedu.com" },
    3009: { name: "Anand Palkar", email: "anand.palkar@indiraiimp.edu.in" },
    792: { name: "Krushna Prasad Mishra", email: "kp.mishra@indiraiimp.edu.in" },
    546: { name: "Thirumagal Pillai", email: "thirumagalpillai@indiraiimp.edu.in" },
    1867: { name: "Rahul Dattatray Pathak", email: "rahulpathak@indiraiimp.edu.in" },
    2135: { name: "Maruti Nandan Prasad", email: "maruti.prasad@indiraiimppgdm.edu.in" },
    1954: { name: "Vishakha Bhattacharya", email: "vishakha.bhattacharya@indiraiimppgdm.edu.in" },
    2137: { name: "Manik Sujit Rajopadhye", email: "manik.rajopadhye@indiraiimppgdm.edu.in" },
    2370: { name: "Vinita Swpanil Shinde", email: "vinita.shinde@indiraiimppgdm.edu.in" },
    2685: { name: "Rahul Prakash Patil", email: "rahul.patil@indiraiimppgdm.edu.in" },
    2882: { name: "Neha Shah", email: "neha.shah@indiraiimppgdm.edu.in" },
    2932: { name: "Anagha Sohani", email: "anagha.sohani@indiraiimppgdm.edu.in" },
    3038: { name: "Komal Sakharam Chaudhari", email: "komal.chaudharilib@iccs.ac.in" },
    3039: { name: "Shubhada Shivaji Gadekar", email: "shubhada.jogadand@iccs.ac.in" },
    3042: { name: "Arvind Bhairu Gavali", email: "arvind.gavali@icem.ac.in" },
    3044: { name: "Ms.Ruchita Sanjay Bhoite", email: "ms.bhoite@icem.ac.in" },
    3047: { name: "Mr. Dadasaheb Anandrao Jadhav", email: "mr.jadhav@icem.ac.in" },
    3045: { name: "Deepak Dagdu More", email: "deepak.more@icem.ac.in" },
    3046: { name: "Shweta Prashant Ketgale", email: "shweta.ketgale@icem.ac.in" },
    3035: { name: "Juli Pal", email: "juli.pal@indirauniversity.edu.in" },
    3036: { name: "Sanika Shrikant Zagade", email: "sanika.zagade@indirauniversity.edu.in" },
    2976: { name: "Arin Malhotra", email: "arin.malhotra@icacs.ac.in" }

  };

  if (coupons[code]) {
    return res.status(200).json({
      success: true,
      name: coupons[code].name,
      email: coupons[code].email,
    });
  } else {
    return res.status(404).json({
      success: false,
      message: "Invalid or expired coupon code",
    });
  }
}
