export default function handler(req, res) {
  // 🔐 Allow all origins for testing — change to a specific domain in production
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "GET, OPTIONS");

  if (req.method === "OPTIONS") {
    return res.status(200).end(); // Respond to preflight requests
  }

  const { code } = req.query;

  const coupons = {
    Bhush: { name: "Bhushan", email: "bhushan@example.com" },
    SHARDULSIR2: { name: "Shardul Gangal", email: "shardul@indiraedu.com" },
    CHETANSIR2: { name: "Chetan Wakalkar", email: "cwakalkar@indiraedu.com" },
    MANISHSIR2: { name: "Manish Dalmia", email: "manish.dalmia@indiraedu.com" },
    2967: { name: "Manish Dalmia", email: "manish.dalmia@indiraedu.com", coupon: "MANISHDALMIA" },
    1705: { name: "Ravindra Sarje", email: "Director-admission@indiraedu.com", coupon: "RAVINDRASARJE" },
    3008: { name: "Priyashi Priya Yadav", email: "priyashi.yadav@indiraisbs.edu.in", coupon: "PRIYASHIPRIYAYADAV" },
    1817: { name: "Dr. Sachin Hapase", email: "sachin.hapase@indiraisbs.ac.in", coupon: "DRSACHINHAPASE" },
    2650: { name: "Sohel Javed Shaikh", email: "sohel.shaikh@indiraisbs.ac.in", coupon: "SOHELJAVEDSHAIKH" },
    2684: { name: "Abhinav Jha", email: "abhinav.jha@indiraiimp.edu.in", coupon: "ABHINAVJHA" },
    2634: { name: "Vishal Popat Pawar", email: "vishal.pawar@icacs.ac.in", coupon: "VISHALPOPATPAWAR" },
    2611: { name: "Avani Suresh Patel", email: "avani.patel@indiraiimp.edu.in", coupon: "AVANISURESHPATEL" },
    2577: { name: "Ms. Sweta Gour", email: "sweta.gour@indiraisbs.ac.in", coupon: "MSSWETAGOUR" },
    2683: { name: "Supriya Diwate", email: "supriya.diwate@indiraisbs.ac.in", coupon: "SUPRIYADIWATE" },
    2351: { name: "Nagalaxmi Erlapaty", email: "nagalaxmi.erlapaty@indiraisbs.ac.in", coupon: "NAGALAXMIERLAPATY" },
    2336: { name: "Neha Thakur", email: "neha.thakur@indiraisbs.ac.in", coupon: "NEHATHAKUR" },
    1757: { name: "Purva Yogesh Randive", email: "purva.randive@indiraisbs.ac.in", coupon: "PURVAYOGESHRANDIVE" },
    2084: { name: "Shital Pawar", email: "shital.pawar@indiraisbs.ac.in", coupon: "SHITALPAWAR" },
    2428: { name: "Sunita Barule", email: "sunita.barule@indiraisbs.ac.in", coupon: "SUNITABARULE" },
    2992: { name: "Shreyad Barai", email: "shreyad.barai@indiraisbs.ac.in", coupon: "SHREYADBARAI" },
    3022: { name: "Srushti Talwekar", email: "srushti.talwekar@iccs.ac.in", coupon: "SRUSHTITALWEKAR" },
    2994: { name: "Nitisha Ranit", email: "nitisha.ranit@iccs.ac.in", coupon: "NITISHARANIT" },
    3050: { name: "Meghal Gandhi", email: "meghal.gandhi@indiraiimp.edu.in", coupon: "MEGHALGANDHI" },
    2999: { name: "Shahin Tadvi", email: "shahin.tadvi@indiraiimp.edu.in", coupon: "SHAHINTADVI" },
    3043: { name: "Ragani Sonawane", email: "ragini.sonawane@indiraisbs.edu.in", coupon: "RAGANISONAWANE" },
    2857: { name: "Vaishnavi Bhagwat Godbole", email: "vaishnavi.godbole@icacs.ac.in", coupon: "VAISHNAVIBHAGWATGODBOL" },
    2991: { name: "Prajakta Telang", email: "prajakta.telang@indiraisbs.ac.in", coupon: "PRAJAKTATELANG" },
    2638: { name: "Trupti kakuste", email: "trupti.kakuste@indiraiimp.edu.in", coupon: "TRUPTIKAKUSTE" },
    2971: { name: "Tamanna Kalal", email: "tamannakalal@indiraicp.edu.in", coupon: "TAMANNAKALAL" },
    2679: { name: "Madhuri Pardeshi", email: "madhuri.pardeshi@indiraiimp.edu.in", coupon: "MADHURIPARDESHI" },
    2998: { name: "Prajwal Chauhan", email: "prajwal.chauhan@indiraiimp.edu.in", coupon: "PRAJWALCHAUHAN" },
    3030: { name: "Aarti Kamble", email: "Aarti.Kamble@indiraiimp.edu.in", coupon: "AARTIKAMBLE" },
    2913: { name: "Shashank Wani", email: "Shashank.wani@indiraicp.edu.in", coupon: "SHASHANKWANI" },
    1830: { name: "Kishor Gaikwad", email: "kishor.gaikwad@indiraisbs.ac.in", coupon: "KISHORGAIKWAD" },
    2716: { name: "Pankaj Bendale", email: "pankaj.bendale@indiraisbs.edu.in", coupon: "PANKAJBENDALE" },
    2386: { name: "Shubham Shahane", email: "shubham.shahane@icacs.ac.in", coupon: "SHUBHAMSHAHANE" },
    2360: { name: "Kavita Bhoite", email: "kavita@indiraedu.com", coupon: "KAVITABHOITE" },
    1959: { name: "Shubham Shingote", email: "shubham.shingote@indiraisc.edu.in", coupon: "SHUBHAMSHINGOTE" },
    2675: { name: "Vijaykumar Mali", email: "vijaykumar.mali@indiraisbs.edu.in", coupon: "VIJAYKUMARMALI" },
    2423: { name: "Yash Aryan", email: "yash.aryan@indiraedu.com", coupon: "YASHARYAN" },
    3031: { name: "Prerna Bhat", email: "prerna.bhat@indiraiimp.edu.in", coupon: "PRERNABHAT" },
    2997: { name: "Saumya Srivastava", email: "saumya.srivastava@indiraiimp.edu.in", coupon: "SAUMYASRIVASTAVA" },
    2264: { name: "Ishwar Malve", email: "ishwar.malve@indiraiimp.edu.in", coupon: "ISHWARMALVE" },
    2799: { name: "Rushikesh Jaju", email: "Rushikesh.jaju@indiraisbs.ac.in", coupon: "RUSHIKESHJAJU" },
    2439: { name: "Anand Ambekar", email: "anand.ambekar@indiraisc.edu.in", coupon: "ANANDAMBEKAR" },
    3011: { name: "Disha Ghai", email: "disha.ghai@indiraiimp.edu.in", coupon: "DISHAGHAI" },
    3010: { name: "Varun Soni", email: "varun.soni@indiraiimp.edu.in", coupon: "VARUNSONI" },
    INTERNNEHA: { name: "Neha Shekhavat", email: "neha24.shekhawat@gmail.com", coupon: "NEHASHEKHAVAT" },
    INTERNLAKSH: { name: "Laksh Dhanani", email: "lakshdhanani26@gmail.com", coupon: "LAKSHDHANANI" },
    2384: { name: "Vivek J", email: "vivek_j@indiraiimp.edu.in" },
    INTERNROHIT: { name: "Rohit Mane", email: "rohitsmane2029@gmail.com" },
    2553: { name: "Mrunalinee D", email: "mrunalinee.deshmukh@indiraisbs.ac.in" },
    2961: { name: "Mr. Rajive Bansal", email: "rajiv.bansal@indiraedu.com" },
    95: { name: "Dr Anagha Joshi", email: "vc@indirauniversity.edu.in" },
    2961: { name: "Dr. Rupa Hiremath", email: "rupa_hiremath@indiraedu.com" },
    2927: { name: "Ashwini Patwe", email: "ashwini.patve@indiraicp.edu.in" },
    2899: { name: "Suhas Koli", email: "suhas.koli@indiraisbs.edu.in" },
    //IGI
    2408: { name: "Anuja Babanrao Thube", email: "anuja.thube@icacs.ac.in" },
    2615: { name: "Mahendra Narke", email: "mknarke@gmail.com" },
    2724: { name: "Mitesh Kolhapure", email: "mitesh.kolhapure@icacs.ac.in" },
    2167: { name: "Nilesh Shrikantrao Khalikar", email: "nilesh.khalikar@icacs.ac.in" },
    2440: { name: "Punam Kavade", email: "punam.kavade@icacs.ac.in" },
    2156: { name: "Shobha Santosh Jagtap", email: "shobha.jagtap@icacs.ac.in" },
    2525: { name: "Swapnali Vayadande", email: "swapnali.vayadande@icacs.ac.in" },
    798: { name: "Vishal Parghale", email: "vishal.parghale@icacs.ac.in" },
    2074: { name: "Akaram Anna Tale", email: "akaram.tale@iccs.ac.in" },
    2914: { name: "Akash Kailas Gavhad", email: "akash.gavhad@iccs.ac.in" },
    1974: { name: "Amol Dattatraya Gaikwad", email: "amol.gaikwad90@iccs.ac.in" },
    2335: { name: "Anil Ramrao Kamlapure", email: "anil.kamlapure@iccs.ac.in" },
    83: { name: "Avinash Chandrakant Shingte", email: "avinash.shingate@iccs.ac.in" },
    568: { name: "Badshaha Gulab Nadaf", email: "nadaf@iccs.ac.in" },
    1716: { name: "Bharat Keshav Nagargoje", email: "bharat.nagargoje@iccs.ac.in" },
    1981: { name: "Dalnar Komal Shivajirao", email: "komal.dalnar@iccs.ac.in" },
    2431: { name: "Dattatraya Madhavrao Kulkarni", email: "dattatraya.kulkarni@iccs.ac.in" },
    1983: { name: "Divya Swapnil Chitre", email: "divya.chitre@iccs.ac.in" },
    333: { name: "Gouri Amol Vaidya", email: "vaidya.gouri@iccs.ac.in" },
    33: { name: "Janardan Adinath Pawar", email: "janardanp@iccs.ac.in" },
    712: { name: "Javed Masud Shaikh", email: "javed@iccs.ac.in" },
    341: { name: "Jyoti Narayan Shrote", email: "jyoti.shrote@iccs.ac.in" },
    2530: { name: "Jyoti Ramchandra Jadhav", email: "jyoti.jadhav@iccs.ac.in" },
    346: { name: "Kavita Yogesh Dhakad", email: "kavita.dhakad@iccs.ac.in" },
    1283: { name: "Madhavi Satish Avhankar", email: "madhavi.avhankar@iccs.ac.in" },
    90: { name: "Manisha Manish Patil", email: "manisha.patil@iccs.ac.in" },
    828: { name: "Marceline Fernandes", email: "marseline.fernandes@iccs.ac.in" },
    219: { name: "Nalanda Dyneshwar Wani", email: "nalanda.wani@iccs.ac.in" },
    2276: { name: "Nidhi Menaria", email: "nidhi.menaria@iccs.ac.in" },
    1433: { name: "Ninad Narayan Thorat", email: "ninad.thorat@iccs.ac.in" },
    570: { name: "Pashankar Shital S", email: "shital.pashankar@iccs.ac.in" },
    2672: { name: "Patil Sejal Deepak", email: "sejal.patil@iccs.ac.in" },
    1566: { name: "Prajwal Vitthal Bhalsing", email: "prajwal.bhalsing@iccs.ac.in" },
    1447: { name: "Pramod Ramesh Gholap", email: "pramod.gholap@iccs.ac.in" },
    86: { name: "Pravin Shantaram Mate", email: "pravin.mate@iccs.ac.in" },
    1717: { name: "Rajesh Navnath Bansode", email: "rajesh.bansode@iccs.ac.in" },
    1674: { name: "Rajminar Devidas Navgire", email: "rajminar.navgire@iccs.ac.in" },
    1742: { name: "Raju Babu Jagtap", email: "raju.jagtap@iccs.ac.in" },
    1567: { name: "Ramdas Sanjay Bolage", email: "ramdas.bolage@iccs.ac.in" },
    1672: { name: "Ranjeet Dattatray More", email: "ranjeet.more@iccs.ac.in" },
    1986: { name: "Rupali Jalindar Zaware", email: "jadhav.rupali@iccs.ac.in" },
    2713: { name: "Sagar Babasaheb Kharade", email: "sagar.kharade@iccs.ac.in" },
    229: { name: "Sarika Yogesh Thakare", email: "sarika.thakare@iccs.ac.in" },
    118: { name: "Sarita Mareppa Byagar", email: "sarita.byagar@iccs.ac.in" },
    2295: { name: "Shambhu Anil Mahadik", email: "shambhu.mahadik@iccs.ac.in" },
    2180: { name: "Shubhangi Deepak Gore", email: "shubhangi.gore@iccs.ac.in" },
    1964: { name: "Shubhangi Sanjay Chavan", email: "shubhangi.chavan@iccs.ac.in" },
    1982: { name: "Soman Vikrant Sanjay", email: "vikrant.soman@iccs.ac.in" },
    2053: { name: "Sonali Pramod Patil (Bujbal)", email: "sonali.bhujbal@iccs.ac.in" },
    1204: { name: "Sumit Subhash Sasane", email: "Sumit.sasane@iccs.ac.in" },
    78: { name: "Sunita Tukaram Gawade", email: "sunita.gawade@iccs.ac.in" },
    1707: { name: "Suwarna Suresh Kedari", email: "kedari.suwarna@iccs.ac.in" },
    532: { name: "Tejashri Anil Phalke", email: "tejashriphalle@iccs.ac.in" },
    719: { name: "Thomson Varghese", email: "thomson.varghese@iccs.ac.in" },
    1970: { name: "Valmik Kashinath Dhanwate", email: "valmik.dhanwate@iccs.ac.in" },
    2933: { name: "Vede Amit Ankush", email: "amit.vede@iccs.ac.in" },
    335: { name: "Vijay Daulatrao More", email: "vijay.more@iccs.ac.in" },
    235: { name: "Vishal Pramod Verma", email: "vishal.verma@iccs.ac.in" },
    2127: { name: "Vividha Bahety", email: "vividha.bahety@iccs.ac.in" },
    1978: { name: "Yewale Sharmila B", email: "sharmila.yewale@iccs.ac.in" },
    1318: { name: "Yogesh Shamrao Bhusari", email: "yogesh.bhusari@iccs.ac.in" },
    316: { name: "Abhijit Chandratreya", email: "abhijitc@indiraiimp.edu.in" },
    1621: { name: "Anil Parkhe", email: "anil.parkhe@indiraiimp.edu.in" },
    2271: { name: "Ashish Marne", email: "ashish.marne@indiraiimp.edu.in" },
    2150: { name: "Ashutosh Kulkarni", email: "ashutosh.kulkarni@indiraiimp.edu.in" },
    103: { name: "Dinkar Kamble", email: "dinkar.kamble@indiraiimp.edu.in" },
    744: { name: "Dipanjay Jayant Bhalerao", email: "dipanjay.bhalerao@indiraiimp.edu.in" },
    2082: { name: "Sakshi Mann", email: "sakshi.mann@indiraiimp.edu.in" },
    310: { name: "Gopal Nandurkar", email: "gopal.nandurkar@indiraiimp.edu.in" },
    1513: { name: "Jyoti Gore", email: "jyoti.gore@indiraiimp.edu.in" },
    902: { name: "Kailas Mhetre", email: "kailas.mhetre@indiraiimp.edu.in" },
    95: { name: "Kailash Pawar", email: "kailas_p@indiraiimp.edu.in" },
    29: { name: "Khandu Inamke", email: "khandu.inamke@indiraiimp.edu.in" },
    2243: { name: "Kirti Vasudeo", email: "kirti.vasudeo@indiraiimp.edu.in" },
    2260: { name: "Laxman Narute", email: "laxman.narute@indiraiimp.edu.in" },
    318: { name: "Manasi Patil", email: "manasi.pawar@indiraiimp.edu.in" },
    85: { name: "Girish Parekh", email: "girishparekh@indiraedu.com" },
    1239: { name: "Neha Ramteke", email: "neha.ramteke@indiraiimp.edu.in" },
    1905: { name: "Nitin Joshi", email: "nitin.joshi@indiraiimp.edu.in" },
    2220: { name: "Priti Kulkarni", email: "priti.kulkarni@indiraiimp.edu.in" },
    429: { name: "Punam Bhoyar", email: "punam.bhoyar@indiraiimp.edu.in" },
    109: { name: "Purvi Shah", email: "purvi.shah@indiraiimp.edu.in" },
    1745: { name: "Rahul Pande", email: "rahul.pande@indiraedu.com" },
    1679: { name: "Ravi Baijulal Bhandari", email: "ravi.bhandari@indiraiimp.edu.in" },
    733: { name: "Rita Dangre", email: "rita.dangre@indiraedu.com" },
    205: { name: "Sachin Ramchandra Kamble", email: "sachin@indiraedu.com" },
    294: { name: "Sagar Kamble", email: "sagar.kamble@indiraiimp.edu.in" },
    2064: { name: "Sanchit Bhauso Pansare", email: "sanchit.pansare@indiraiimp.edu.in" },
    39: { name: "Sandeep Gunjal", email: "sandeep.gunjal@indiraiimp.edu.in" },
    1358: { name: "Sanjay Bhale", email: "sanjay.bhale@indiraiimp.edu.in" },
    1338: { name: "Shashikant Bade", email: "shashikant.bade@indiraiimp.edu.in" },
    13: { name: "Subhash Gaikwad", email: "subhash.gaikwad@indiraiimp.edu.in" },
    1650: { name: "Sumit Omprakash Sharma", email: "sumit.sharma@indiraedu.com" },
    2357: { name: "Sunil Maske", email: "sunil.maske@indiraiimp.edu.in" },
    2358: { name: "Swapnali Amol Kulkarni", email: "swapnali.kulkarni@indiraiimp.edu.in" },
    2833: { name: "Swati Patil", email: "swati.patil@indiraiimp.edu.in" },
    1797: { name: "Tushar Patil", email: "tushar.patil@indiraiimp.edu.in" },
    88: { name: "Yestrela Evangelist Vaz", email: "yestrela.vaz@indiraiimp.edu.in" },
    1880: { name: "Renu Darshan Garg", email: "renu.garg@indiraisc.edu.in" },
    2590: { name: "Alisha Mukhopadhayay", email: "alisha.mukhopadhayay@indiraiimp.edu.in" },
    1862: { name: "Anjali P Kalkar", email: "anjali.kalkar@indiraiimp.edu.in" },
    2429: { name: "Manoj Hemant Tapaswi", email: "manoj.tapaswi@indiraiimp.edu.in" },
    2176: { name: "P S Deepa", email: "deepa.sakthi@indiraiimp.edu.in" },
    2027: { name: "Patil Sudhir Jijabrao", email: "prof.sudhir.patil@indiraiimp.edu.in" },
    2034: { name: "Sachin Shankar Hadapad", email: "sachin.hadpad@indiraiimp.edu.in" },
    2141: { name: "Santoshkumar Tatyaram Kadam", email: "santoshkumar.kadam@indiraiimp.edu.in" },
    2613: { name: "Sarika Ravindranath Sagar", email: "sarika.sagar@indiraiimp.edu.in" },
    1960: { name: "Sonali Suresh Shrotri", email: "sonali.shrotri@indiraiimp.edu.in" },
    1922: { name: "Swapnil Dattatray Kharde", email: "swapnil.kharde@indiraiimp.edu.in" },
    2340: { name: "Torsha Ghosh", email: "torsha.ghosh@indiraiimp.edu.in" },
    2028: { name: "Vijayalakshmi Ganganna Nemmaniwar", email: "dr.vijayalaxmi@indiraiimp.edu.in" },
    1254: { name: "Akshay Ranjan Pawar", email: "akshay.pawar@indiraicp.edu.in" },
    1472: { name: "Amruta Prasann Walvekar", email: "amruta.walvekar@indiraicp.edu.in" },
    405: { name: "Anil Rama Gaikwad", email: "anil.gaikwad@indiraicp.edu.in" },
    2806: { name: "Anirudha Vasant Munde", email: "anirudha.munde@indiraicp.edu.in" },
    2258: { name: "Ashutosh Narayan Misal", email: "ashutosh.misal@indiraiimp.edu.in" },
    2817: { name: "Ashwini Chitrangad Kotkar", email: "ashwini.kotkar@indiraicp.edu.in" },
    354: { name: "Dayanand Mukund Kannur", email: "dayanand.kannur@indiraicp edu.in" },
    1813: { name: "Digambar Balkrishna Ambikar", email: "digambar.ambikar@indiraicp.edu.in" },
    32: { name: "Dilip Maruti Dhamale", email: "dilipdhamale@indiraicp.edu.in" },
    2803: { name: "Divya Ashok Kulkarni", email: "divya.kulkarni@indiraicp.edu.in" },
    446: { name: "Manasi Jayant Wagdarikar", email: "mansi.wagdarikar@indiraicp.edu.in" },
    153: { name: "Manohar Vitthal Jadhav", email: "manohar.jadhav@indiraicp.edu.in" },
    1577: { name: "Meghna Mandar Dabhadkar", email: "meghna.dabhadkar@indiraicp.edu.in" },
    1509: { name: "Pallavi Yogendra Singh Chouhan", email: "pallavi.chouhan@indiraicp.edu.in" },
    1388: { name: "Pradnya Parag Kulkarni", email: "pradnya.kulkarni@indiraicp.edu.in" },
    2805: { name: "Rajanigandha Rajendra Jori", email: "rajanigandha.jori@indiraicp.edu.in" },
    723: { name: "Ramling Arjun Gaikwad", email: "Ramling.gaikwad@indiraicp.edu.in" },
    2524: { name: "Rutuja Saurabh Lokhande", email: "rutuja.lokhande@indiraicp.edu.in" },
    224: { name: "Samadhan Prabhakar Gaikwad", email: "samadhan.gaikwad@indiraicp.edu.in" },
    2824: { name: "Sharmishtha Anurag Singh", email: "sharmishthasingh@indiraicp.edu.in" },
    1474: { name: "Shraddha Prakash Devarshi", email: "shraddha.devarshi@indiraicp.edu.in" },
    1699: { name: "Shubham Vijay Pawar", email: "shubham.pawar@indiraicp.edu.in" },
    2812: { name: "Sneha Anil Pachore", email: "sneha.pachore@indiraicp.edu.in" },
    2814: { name: "Sneha Ganesh Nawkar", email: "sneha.nawkar@indiraicp.edu.in" },
    1712: { name: "Sneha Vishwas Joshi", email: "sneha.joshi@indiraicp.edu.in" },
    2099: { name: "Snehali Pandurang Saykar", email: "snehali.saykar@indiraicp.edu.in" },
    1470: { name: "Swapnil Vilas Dhamale", email: "swapnil.dhamale@indiraicp.edu.in" },
    1870: { name: "Abhijit Prabhakar Bobde", email: "abhijit.bobde@indiraisbs.ac.in" },
    2703: { name: "Anita Sanjay Mathapati", email: "anita.mathapati@indiraisbs.edu.in" },
    2041: { name: "Bibeesh Kannan P.V.", email: "bibeesh.p@indiraisbsmba.edu.in" },
    2158: { name: "Dhanashri Swapnil Deshpande", email: "dhanashri.deshpande@indiraisbs.edu.in" },
    34: { name: "Haridas Ashok Deshmukh", email: "harish.deshmukh@indiraiimp.ac.in" },
    2153: { name: "Harshal Suresh Gajbhe", email: "harshal.gajbhe@indiraisbsmba.edu.in" },
    1623: { name: "Kalpana Kamalakar Deshmukh", email: "kalpana.deshmukh@indiraisbs.ac.in" },
    1334: { name: "Laxman Navnath Misal", email: "laxman.misal@indiraisbs.ac.in" },
    1869: { name: "Mrityunjay Kameshwar Lal Kumar", email: "mrityunjay.Kumar@indiraisbs.ac.in" },
    2838: { name: "Mrunalini Saheb Khandare", email: "mrunalini.khandare@indiraisbs.edu.in" },
    2893: { name: "Poonam Nitin Satpute", email: "poonam.satpute@indiraisbs.edu.in" },
    2823: { name: "Pravin Dnyandev Dolas", email: "pravin.dolas@indiraisbs.edu.in" },
    2087: { name: "Rajneesh Madanlal Bali", email: "rajneesh.bali@indiraedu.com" },
    132: { name: "Sangita Shahu Devare", email: "sangeeta.devare@indiraisbs.ac.in" },
    2493: { name: "Sanjay Kapoorchand Asati", email: "sanjay.asati@indiraisbs.edu.in" },
    1606: { name: "Subhash Tukaram Ghogare", email: "subhash.ghogare@indiraisbs.ac.in" },
    2478: { name: "Sushil Dashrath Shende", email: "sushil.shende@indiraisbs.edu.in" },
    1237: { name: "Tanaji Gopal Durgade", email: "tanaji.durgade@indiraisbs.ac.in" },
    2666: { name: "Tilak Kisan Nugurwar", email: "tilak.nugurwar@indiraedu.com" },
    2836: { name: "Vaibhavi Shashikant Shahane", email: "vaibhavi.shahane@indiraisbs.edu.in" },
    2908: { name: "Yogesh Sunil Pansare", email: "yogesh.pansare@indiraisbs.edu.in" },
    1307: { name: "Amruta Deshpande", email: "amruta.deshpande@indiraisbs.ac.in" },
    1671: { name: "Anagha Bhope", email: "anagha1.bhope@indiraisbs.ac.in" },
    1654: { name: "Anil Chalke", email: "anil.chalke@indiraisbs.ac.in" },
    2653: { name: "Anna Philips", email: "anna.philips@indiraisbs.ac.in" },
    133: { name: "Arun Padale", email: "arun.padale@indiraiscs.ac.in" },
    2399: { name: "Bharti Shukla", email: "bharti.shukla@indiraisbs.ac.in" },
    1575: { name: "Chetan Parange", email: "chetan.parange@indiraisbs.ac.in" },
    1635: { name: "Dipesh Kawale", email: "dipesh.kawale@indiraisbs.ac.in" },
    1541: { name: "Gaganpreet Ahluwalia", email: "gaganpreet.ahluwalia@indiraisbs.ac.in" },
    2270: { name: "Jaya Saxena", email: "jaya.saxena@indiraisbs.ac.in" },
    1957: { name: "Jayanthi Kumbhar", email: "jayanti.kumbhar@indiraisbs.ac.in" },
    1616: { name: "Jitendra Patil", email: "jitendra.patil@indiraisbs.ac.in" },
    2686: { name: "Kishan Giri", email: "kishan.giri@indiraisbs.ac.in" },
    1952: { name: "Kumendra Raheja", email: "kumendrar@indiraisbs.ac.in" },
    2380: { name: "Madan Khandekar", email: "madan.khandekar@indiraedu.com" },
    762: { name: "Mahesh Mangaonkar", email: "mahesh.mangaonkar@indiraisbs.ac.in" },
    1951: { name: "Mahesh Pol", email: "mahesh.pol@indiraisbs.ac.in" },
    5441: { name: "Maruti Uttekar", email: "maruti.utterkar@indiranationalschool.ac.in" },
    2221: { name: "Mayuresh Naregalkar", email: "mayuresh.naregalkar@indiraisbs.ac.in" },
    1855: { name: "Meghasham Chaudhari", email: "meghasham.chaudhari@indiraisbs.ac.in" },
    2241: { name: "Mohan Rathod", email: "mohan.rathod@indiraisbs.ac.in" },
    1399: { name: "Neetal Vyas", email: "neetal.vyas@indiraisbs.ac.in" },
    1899: { name: "Padmashree Chandak", email: "padmashree.chandak@indiraisbs.ac.in" },
    2029: { name: "Piyush Dixit", email: "piyush.dixit@indiraisbs.ac.in" },
    569: { name: "Pradip Patil", email: "pradip.patil@indiraisbs.ac.in" },
    1595: { name: "Pramod Shinde", email: "pramod.shinde@indiraicp.edu.in" },
    1279: { name: "Prashant Rege", email: "prashant.rege@indiraisbs.ac.in" },
    1182: { name: "Rajendra Vikhar", email: "rajendra.vikhar@indiraisbs.ac.in" },
    2245: { name: "Ravindra Shinde", email: "ravindra.shinde@indiraedu.com" },
    171: { name: "Sachin More", email: "sachin.more@indiraisbs.ac.in" },
    1357: { name: "Sadhana Ingle", email: "sadhana.ingle@indiraisbs.edu.in" },
    59: { name: "Sahebrao Patil", email: "sahebrao.patil@indiraisbs.ac.in" },
    2702: { name: "Sajid Shaikh", email: "sajid.shaikh@indiraisbs.ac.in" },
    508: { name: "Sameer Sheshgir", email: "samir.sheshgir@indiraicp.edu.in" },
    1536: { name: "Sanjay Muthal", email: "sanjay.muthal@indiraisbs.ac.in" },
    1538: { name: "Sanjay Rathod", email: "sanjay.rathod@indiraisbs.ac.in" },
    2521: { name: "Sarita Agarwal", email: "sarita.agarwal@indiraisbs.ac.in" },
    1050: { name: "Shikha Sindhu", email: "shikha.sindhu@indiraisbs.ac.in" },
    2720: { name: "Shweta Vyas", email: "shweta.vyas@indiraisbs.ac.in" },
    2395: { name: "Sumit Shinde", email: "sumit.shinde@indiraedu.com" },
    2078: { name: "Sushmitha Rao", email: "sushmitha.rao@indiraisbs.ac.in" },
    1214: { name: "Tausif Mistry", email: "tausif.mistry@indiraisbs.ac.in" },
    2718: { name: "Trupti Sharad Joshi", email: "padirector@indiraisbs.ac.in" },
    1729: { name: "Umesh Jagdale", email: "umesh.jagdale@indiraisbs.edu.in" },
    2721: { name: "Varsha Nagpure", email: "varsha.murhe@indiraisbs.ac.in" },
    26: { name: "Vinay Khawale", email: "vinayk@indiraedu.com" },
    2415: { name: "Yamini Ghanghorkar", email: "yamini.ghanghorkar@indiraisbs.ac.in" },
    3012: { name: "Karun Kumar Chaugule", email: "karunkumar.chaugule@indiraiimp.edu.in" },
    3027: { name: "Bharti Khaire", email: "bharti.khaire@indiraiimp.edu.in" },
    3021: { name: "Sunil Kashinath Sakhare", email: "sunil.sakhare@indiraedu.com" },
    3034: { name: "Kadambari Vishnu Suryawanshi", email: "Kadambari.Suryawanshi@indiraiimp.edu.in" },
    3048: { name: "Kavita Mathad", email: "dean.sob@indirauniversity.edu.in" },
    3037: { name: "Prakash Vishnu Khadse", email: "prakash.khadse@indiraedu.com" },
    2789: { name: "Shashwat Doshetti", email: "shashwat.doshetti@indiraigsb.edu.in" },
    //INS
    2322: { name: "Abhilasha Tiwari", email: "abhilasha.tiwari@ins.ac.in" },
    2972: { name: "Akshay Thosar", email: "thosarra45@gmail.com" },
    2329: { name: "Alwin Daniel Satpute", email: "alwin.satpute@ins.ac.in" },
    2307: { name: "Anand Hari Patil", email: "ananda.patil@ins.ac.in" },
    2585: { name: "Asha Mahendra Ghodke", email: "asha.ghodke@ins.ac.in" },
    2947: { name: "Bhagyashree Yogesh Vispute", email: "bhagyashree.vispute@ins.ac.in" },
    2558: { name: "Bharat Chandrakant Kshirsagar", email: "bharat.kshirsagar@ins.ac.in" },
    683: { name: "Dattatraya Mohan Sutar", email: "dattatraya.sutar@ins.ac.in" },
    1645: { name: "Gayatri Jorwekar", email: "gayatri.jorwekar@indiraedu.com" },
    2568: { name: "Jyoti Santosh Thorat", email: "Jyoti.thorat@ins.ac.in" },
    2306: { name: "Kamaljit Kaur Sidhu", email: "kamaljit.sidhu@ins.ac.in" },
    2962: { name: "Kasturi Kapil Kedari", email: "kasturi.kedari@ins.ac.in" },
    2587: { name: "Meenakshi Sisodia", email: "meenakshi.sisodia@ins.ac.in" },
    2691: { name: "Mrunal Vaidya", email: "mrunal.vaidya@ins.ac.in" },
    2633: { name: "Nisha Nitin Deore", email: "nisha.deore@ins.ac.in" },
    2697: { name: "Pallavi Nitin Chinchole", email: "pallavi.chinchole@ins.ac.in" },
    2981: { name: "Pallavi Shejwal", email: "pallavi.shejwal@ins.ac.in" },
    2320: { name: "Prachi Jain", email: "prachi.jain@ins.ac.in" },
    2312: { name: "Prachi Sandeep Sant", email: "prachi.sant@ins.ac.in" },
    2693: { name: "Ruchi Dilip Tulshyan", email: "ruchi.tulshyan@ins.ac.in" },
    2936: { name: "Saroj Jain", email: "saroj.jain@ins.ac.in" },
    2647: { name: "Shilpa Sachin Biradar", email: "shilpa.biradar@ins.ac.in" },
    2727: { name: "Shravani Shriniwas Arole", email: "shravani.arole@ins.ac.in" },
    2629: { name: "Shreya Roy", email: "shreya.roy@ins.ac.in" },
    2569: { name: "Shweta Santosh Sawant", email: "sweta.sawant@ins.ac.in" },
    2333: { name: "Sipra Ray", email: "sipra.ray@ins.ac.in" },
    2308: { name: "Snehal Pravin Kakade", email: "snehal.kakade@ins.ac.in" },
    2689: { name: "Sonal Jha", email: "sonal.jha@ins.ac.in" },
    2561: { name: "Sonam Keshwani", email: "Sonam.Keshwani@ins.ac.in" },
    1523: { name: "Suhas Suryawanshi", email: "suhas.suryawanshi@indiraiimp.edu.in" },
    1198: { name: "Sunil Namdeo Thakar", email: "sunil.thakar@ins.ac.in" },
    2572: { name: "Sushma Sachin Bora", email: "sushma.bora@ins.ac.in" },
    2324: { name: "Tapati Sil", email: "tapati.sil@ins.ac.in" },
    2555: { name: "Vedanti Shinde", email: "vedanti.shinde@ins.ac.in" },
    2692: { name: "Yogita Lamkanikar", email: "yogita.lamkanikar@ins.ac.in" },
    37: { name: "Ganesh Dhumal", email: "ganesh.dhumal@indiraiimp.edu.in" },
    E5406: { name: "Sumit Sunil Adkitte", email: "sumit.adkitte@ins.ac.in" },
    E5351: { name: "Yogita Dattatraya Sutar", email: "yogita.sutar@ins.ac.in" },
    E5459: { name: "Swapnali Gaikwad", email: "Swapnali.gaikwad@ins.ac.in" },
    E5347: { name: "Umesh Gajanan Palande", email: "umesh.palande@ins.ac.in" },
    E5846: { name: "Seema Ghogare", email: "seema.ghogare@ins.ac.in" },
    E5569: { name: "Indrani Das", email: "Indrani.Das@ins.ac.in" },
    E5005: { name: "Tanu Pankaj Pandhi", email: "tanu.pandhi@ins.ac.in" },
    E5007: { name: "Sangeeta Vimal Khandka", email: "sangeeta.khandka@ins.ac.in" },
    E5021: { name: "Anjali Nitin Dharmadhikari", email: "anjali.dharmadhikari@ins.ac.in" },
    E5023: { name: "Jayashree Vivek Thorat", email: "jayashree.thorat@ins.ac.in" },
    E5036: { name: "Vrushali Nitin Deshmukh", email: "vrushali.deshmukh@ins.ac.in" },
    E5047: { name: "Ravindra Gyanba Kamble", email: "ravindra.kamble@ins.ac.in" },
    E5050: { name: "Nitin Chandrakant Sangme", email: "nitin.sangme@ins.ac" },
    E5051: { name: "Anup Dattatray Kutwal", email: "anup.kutwal@ins.ac.in" },
    E5065: { name: "Prashant Sakharam Paste", email: "prashant.paste@ins.ac.in" },
    E6446: { name: "Ganesh Raju Pawar", email: "ganesh.pawar@ins.ac.in" },
    E5067: { name: "Nivas Vasant Pujari", email: "niwas.pujari@ins.ac.in" },
    E5040: { name: "Vinit Ramesh Yadav", email: "Vinit.yadav@ins.ac.in" },
    E5025: { name: "Nima Velangi", email: "nima.velangi@ins.c.in" },
    E5010: { name: "Archana Abhijit Hulawale", email: "archana.hulawale@ins.ac.in" },
    E5027: { name: "Smita Yogesh Kataria", email: "Smita.Kataria@ins.ac.in" },
    E5054: { name: "Abhijit Balasaheb Mankar", email: "abhijit.mankar@ins.ac.in" },
    E5015: { name: "Varsha Prasad Joshi", email: "varsha.joshi@ins.ac.in" },
    E5029: { name: "Aarti Chandrashekhar Garampalli", email: "aarti.garampalli@indiranationalschool.ac.in" },
    E5042: { name: "Suman Rangarao Mane", email: "suman.mane@ins.ac.in" },
    E5018: { name: "Urmila Gaikwad", email: "Urmila.gaikwad@ins.ac.in" },
    E5039: { name: "Premchand Mohanlal Kumbhar", email: "Premchand.Kumbhar@ins.ac.in" },
    E5072: { name: "Supriya Akhilesh Shukla", email: "Supriya.Wankhede@ins.ac.in" },
    E5064: { name: "Amit Uttam Yerunkar", email: "amit.yerunkar@ins.ac.in" },
    E6003: { name: "Aakanksha Anand Bhangaonkar", email: "aakanksha.bhangaonkar@indiranationalschool.ac.in" },
    E5090: { name: "Gurunath Baban Kale", email: "Gurunath.Kale@ins.ac.in" },
    E5087: { name: "Najeeb Ahmed Munshi", email: "najeeb.munshi@ins.ac.in" },
    E5098: { name: "Neelima Srivastava", email: "Neelima. Srivastava@ins.ac.in" },
    E5105: { name: "Shivaji Kashiram Uttekar", email: "shivaji.uttekar@ins.ac.in" },
    E5106: { name: "Anita Suryabhan Shinde", email: "anita.shinde@ins.ac.in" },
    E5108: { name: "Sameer Alam Shaikh", email: "sameer.shaikh@ins.ac.in" },
    E5107: { name: "Yogini Pankaj Randive", email: "yogini.ranadive@ins.ac.in" },
    E5125: { name: "Aparna Vineet Bhasin", email: "Aparna.Bhasin@ins.ac.in" },
    E5131: { name: "Aradhana Narayan Budhwant", email: "aradhana.budhwant@ins.ac.in" },
    E5447: { name: "Munjaji Pitale", email: "munjaji.pithale@ins.ac.in" },
    E5152: { name: "Tanima Sanjoy Sengupta", email: "tanima.sengupta@ins.ac.in" },
    E5155: { name: "Nidhi Abhijitkumar Saxena", email: "nidhi.saxena@ins.ac.in" },
    E5137: { name: "Lakshmi Prabha Mitra", email: "lakshmi.mitra1@ins.ac.in" },
    E5444: { name: "Vijaypal Galthya Singh", email: "vijaypal.singh@ins.ac.in" },
    E5077: { name: "Vaishali Bhaskar Khatal", email: "vaishali.khatal@ins.ac.in" },
    E5102: { name: "Gauri Mani", email: "Gauri.Mani@ins.ac.in" },
    E5225: { name: "Swanandi Sagar Shinde", email: "swanandi.shinde@ins.ac.in" },
    E5103: { name: "Roli Sachin Jain", email: "roli.jain@ins.ac.in" },
    E5104: { name: "Mukul Vinaykumar Pal", email: "mukul.pal@ins.ac.in" },
    E5076: { name: "Lucky Manash Sengupta", email: "lucky.sengupta@ins.ac.in" },
    E5168: { name: "Chaitali Guha", email: "chaitali.guha@ins.ac.in" },
    E5349: { name: "Bhausaheb Madhukar Kalkhair", email: "bhausaheb.kalkhair@ins.ac.in" },
    E5452: { name: "Sachin Bhimaji Salunke", email: "sachin.salunke@ins.ac.in" },
    E5210: { name: "Jyoti Nilkanth Mahajan", email: "jyoti.mahajan@ins.ac.in" },
    E5580: { name: "Indira Rajeshwari", email: "Indira.Rajeshwari@ins.ac.in" },
    E5238: { name: "Shravina Satish Dubey", email: "shravina.dubey@ins.ac.in" },
    E5247: { name: "Shabana Salim Shaikh", email: "shabana.shaikh@ins.ac.in" },
    1367: { name: "Gautam Suhas Sabnis", email: "gautam.sabnis@indiraedu.com" },
    E5240: { name: "Reshmi Shubhadeep Ghosh", email: "Reshmi.Ghosh@ins.ac.in" },
    E5439: { name: "Amol Dilip Pimple", email: "amol.pimple@indiraedu.com" },
    E5300: { name: "Meghna Mittal", email: "meghna.mittal@ins.ac.in" },
    E5309: { name: "Manasi Rahul Deshpande", email: "Mansi.deshpande@ins.ac.in" },
    E5301: { name: "Ranjana Negi", email: "ranjana.negi@ins.ac.in" },
    E5290: { name: "Swati Kailas Kumbhar", email: "Swati.kumbhar@ins.ac.in" },
    E5353: { name: "Rajan Gyanba Jamdade", email: "Rajan.Jamdade@ins.ac.in" },
    E5324: { name: "Preetam Deepak Kale", email: "preetam.kale@ins.ac.in" },
    E5291: { name: "Pooja Sandeep Jahagirdar", email: "Pooja.Jahagirdar@ins.ac.in" },
    E5327: { name: "Shamal Sandesh Vartak", email: "Shamal.Vartak@ins.ac.in" },
    E5453: { name: "Nilesh Bhiku Ratwadkar", email: "nilesh.ratwadkar@ins.ac.in" },
    E5726: { name: "Shalini Baghel", email: "shalini.baghel@ins.ac.in" },
    E5344: { name: "Ram Niwas", email: "ram.niwas@ins.ac.in" },
    E5358: { name: "Priya Samudre", email: "priya.samudre@ins.ac.in" },
    E5383: { name: "Manisha Martule", email: "Manisha.Martule@ins.ac.in" },
    E5381: { name: "Smita Anand Desai", email: "smita.desai@ins.ac.in" },
    E5387: { name: "Kiran Rahul Gaikwad", email: "Indira National School" },
    E5438: { name: "Soni Singh", email: "soni.singh@ins.ac.in" },
    E5478: { name: "Mala Gupta", email: "Mala.Gupta@ins.ac.in" },
    E5470: { name: "Prajakta Shirolikar", email: "prajakta.shirolikar@ins.ac.in" },
    E5476: { name: "Elizabeth Samuel", email: "elizabeth.samuel@ins.in.ac" },
    E5579: { name: "Sujata Mohod", email: "sujata.mohod@ins.ac.in" },
    E5461: { name: "Nancy Sachdeva", email: "Nancy.Sachdeva@ins.ac.in" },
    E5495: { name: "Manisha Jha Choudhary", email: "Manisha.Choudhary@ins.ac.in" },
    E5602: { name: "Aarti Bhalerao", email: "aarti.bhalerao@ins.ac.in" },
    E5501: { name: "Kanchan Bala Goel", email: "Kanchan.Goel@ins.ac.in" },
    E5518: { name: "Amol Zarkar", email: "amol.zarkar@ins.ac.in" },
    E5523: { name: "Ananya Aniket Dhuru", email: "ananya.dhuru@ins.ac.in" },
    E5549: { name: "Anant Jodh", email: "anant.jodh@ins.ac.in" },
    E5566: { name: "Durga Dnyaneshwar Chavan", email: "durga.chavan@ins.ac.in" },
    E5595: { name: "Satish Vitthal Bade", email: "satish.bade@indiraiimp.edu.in" },
    E5260: { name: "Gaurav Navaskar", email: "gaurav.navaskar@ins.ac.in" },
    E5565: { name: "Ashwini Shashank Kulkarni", email: "ashwini.kulkarni@ins.ac.in" },
    E5568: { name: "Uma Senthil Kumar", email: "uma. senthilkumar@ins.ac.in" },
    E5348: { name: "Sadhu Ganoba Landge", email: "sadhu.landge@ins.ac.in" },
    E5588: { name: "Jayram Jadhav", email: "jayaram.jadhav@ins.ac.in" },
    E5589: { name: "Jyoti Deepak Thosar", email: "jyoti.thosar@ins.ac.in" },
    E5591: { name: "Ganesh Jadhav", email: "ganesh.jadhav@ins.ac.in" },
    E5421: { name: "Sanjeevani Thaksen Gadhave", email: "sanjeevani.gadhave@ins.ac.in" },
    E5599: { name: "Chaiti Bhowmick", email: "Chaiti.bhowmick@ins.ac.in" },
    1351: { name: "Sandeep Sukalal Dhangar", email: "sandip.suryawanshi@indiraedu.com" },
    998: { name: "Bhausaheb Changdeo Gaikwad", email: "bhausaheb.gaikwad@indiraicem.ac.in" },
    E5610: { name: "Balaji Udhav Yekile", email: "balaji.yekile@ins.ac.in" },
    E5608: { name: "Vaibhav Kakade", email: "Vaibhav.Kakade@ins.ac.in" },
    E5622: { name: "Aditi Pramanick", email: "Aditi.Pramanick@ins.ac.in" },
    E5616: { name: "Nandita Sanjib Mustafi", email: "nandita.mustafi@ins.ac.in" },
    E5621: { name: "Gayatri Chawla", email: "gayatri.chawla@ins.ac.in" },
    E5625: { name: "Sarika Bhauso Mane", email: "Sarika.Mane@ins.ac.in" },
    E5624: { name: "Ranjeeta Dixit", email: "ranjeeta.dixit@ins.ac.in" },
    E5615: { name: "Monika Rajput", email: "monika.rajput@ins.ac.in" },
    E5620: { name: "Vasanti Mahadik", email: "vasanti.mahadik@ins.ac.in" },
    E5639: { name: "Vijaya Borhade", email: "vijaya.borhade@ins.ac.in" },
    E5637: { name: "Rohini Sukhdeo Jadhav", email: "rohini.jadhav@ins.ac.in" },
    E5642: { name: "Samiksha Sanjay Jadhav", email: "samiksha.jadhav@ins.ac.in" },
    E5521: { name: "Akshay Shete", email: "akshay.shete@ins.ac.in" },
    137: { name: "Sachin Waghmare", email: "archanasachin208@gmail.com" },
    676: { name: "Harilal Gorakhnath Yadav", email: "Harilal.Gorakhnath@ins.ac.in" },
    697: { name: "Rajendra Laxman Parase", email: "rajendraparse@indiraedu.com" },
    1724: { name: "Vaibhav Pawar", email: "vaibhav.pawar@indiraisbs.ac.in" },
    1212: { name: "Sachin Dhumal", email: "sachin.dhumal@indiraicem.ac.in" },
    1177: { name: "Umesh Shrirang Waghmare", email: "umesh.waghmare@IndiraInternationalSchool.ac.in" },
    E5641: { name: "Rajasouriya Singh", email: "rajasouriya.singh@ins.ac.in" },
    194: { name: "Gangadhar Kurhade", email: "gangadhar.kurhade@indiraiimp.edu.in.in" },
    E5649: { name: "Himani Bhole", email: "himani.bhole@ins.ac.in" },
    1386: { name: "Dagdu Rokade", email: "" },
    1090: { name: "Prashant Yeole", email: "prashant.yeole@indiraiimp.edu.in" },
    E5653: { name: "Shubhangi Desai", email: "shubhangi.desai@ins.ac.in" },
    1431: { name: "Sameer Surendra Waghmare", email: "sameer.waghmare@indiraiimp.edu.in" },
    E5652: { name: "Shubhangi Bodhankar", email: "Shubhangi.bodhankar@ins.ac.in" },
    E5660: { name: "Antima Jaipuria", email: "Antima.Jaipuria@ins.ac.in" },
    E5657: { name: "Rohini Yadav", email: "rohini.yadav@ins.ac.in" },
    E5666: { name: "Kirti Vikas Joshi", email: "kirti.joshi@ins.ac.in" },
    E5664: { name: "Swati Bavaskar", email: "Swati.Bavaskar@ins.ac.in" },
    E5670: { name: "Shruti Chadha", email: "Shruti.chadha@ins.ac.in" },
    E5668: { name: "Manjusha Koranne", email: "manjusha.koranne@ins.ac.in" },
    E5715: { name: "Snehal Ankush Basutkar", email: "Snehal.badutkar@ins.ac.in" },
    E5676: { name: "Archana Singh", email: "Archana.Singh@ins.ac.in" },
    E5686: { name: "Renuka Pande", email: "renuka.pande@ins.ac.in" },
    E5688: { name: "Kalpana Claudius", email: "kalpana.claudius@ins.ac.in" },
    E5679: { name: "Madhurani Mathane", email: "Madhurani.mathane@ins.ac.in" },
    E5682: { name: "Preeti Purohit", email: "Preeti.Purohit@ins.ac.in" },
    E5704: { name: "Manisha Badlamwar", email: "manisha.badlamwar@ins.ac.in" },
    E5707: { name: "Priti Singh", email: "Priti.singh@ins.ac" },
    E5716: { name: "Ganesh Dhawale", email: "ganesh.dhawale@ins.ac.in" },
    E5706: { name: "Aaditi Maheshwari", email: "aaditi.maheshwari@ins.ac.in" },
    E5022: { name: "Uma Pradeep", email: "uma.pradeep@indiranationalschool.ac.in" },
    E5717: { name: "Sireesha Kongara", email: "sireesha.kongara@ins.ac.in" },
    E5187: { name: "Mariamma Shibu Anthony", email: "mariamma.anthony@ins.ac.in" },
    E5728: { name: "Ashwini Mahesh Nagargoje", email: "ashwini.nagargoje@ins.ac.in" },
    E5735: { name: "Vandana Patnaik", email: "vandana.patnaik@ins.ac.in" },
    E5722: { name: "Anagha Yogesh Tungar", email: "anagha.tungar@ins.ac.in" },
    E5721: { name: "Parmeshwar Sonpasare", email: "parmeshwar.sonpasare@ins.ac.in" },
    E5743: { name: "Vinay Eknath Suryavanshi", email: "vinay.suryavanshi@ins.ac.in" },
    E5740: { name: "Mahesh Baban Gadave", email: "Mahesh.Gadave@ins.ac.in" },
    E5736: { name: "Sunil Vishwas Gaikwad", email: "Sunil.gaikwad@ins.ac.in" },
    E5741: { name: "Jitendra Pratap Rokade", email: "Jitendra.Rokade@ins.ac.in" },
    E5746: { name: "Mamta Salokhe", email: "mamta.salokhe@ins.ac.in" },
    E5745: { name: "Nikita Sikandar Sawant", email: "nikita.sawant@ins.ac.in" },
    E5732: { name: "Ravi Gotsurwe", email: "ravi.gotsurve@ins.ac.in" },
    E5724: { name: "Vaishnavi Anil Bhangare", email: "Vaishnavi.Bhangare@ins.ac.in" },
    192: { name: "Santosh Koli", email: "Santosh.koli@indiraiimp.edu.in" },
    183: { name: "Mangesh Gaikwad", email: "mangesh.gaikwad@ins.ac.in" },
    E5753: { name: "Deepak Kodak", email: "Deepak.kodak@ins.ac.in" },
    E5749: { name: "Bharati Sillode", email: "Bharati.sillode@ins.ac.in" },
E5750: { name: "Neha Solanki", email: "Neha.solanki@ins.ac.in" },
1886: { name: "Sheetal Todkar", email: "sheetal.todkar@indiraiimp.edu.in" },
E5763: { name: "Vaishnavi Ghumai", email: "vaishnavi.ghumai@ins.ac.in" },
E5767: { name: "Bhagyashri Ainapure", email: "Bhagyashri.Ainpure@ins.ac.in" },
E5758: { name: "Vaishnavi Ghadage", email: "Vaishnavi.ghadage@indiranationalschool.ac.in" },
E5783: { name: "Vaishali Sonawane", email: "vaishali.sonawane@ins.ac.in" },
E5778: { name: "Manisha Hirekude", email: "" }, // E5778 has no email
E5784: { name: "Mohini Joshi", email: "mohini.joshi@ins.ac.in" },
E5794: { name: "Anita Sharma", email: "anita.sharma@ins.ac.in" },
1992: { name: "Harshal Papal", email: "harshal.papal@indiraiimp.edu.in" },
E5795: { name: "Swapnali Ahire", email: "Swapnali.Ahire@ins.ac.in" },
E5797: { name: "Sankari Roy Das", email: "Sankari.roydas@ins.ac.in" },
E5798: { name: "Medini Pohare", email: "medini.pohare@ins.ac.in" },
E5796: { name: "Ranjana Tiwari", email: "ranjana.tiwari@ins.ac.in" },
E5799: { name: "Purnima Mohite", email: "purnima.mohite@ins.ac.in" },
E5805: { name: "Rasika Patil", email: "rasika.patil@ins.ac.in" },
E5800: { name: "Saurabh Sharma", email: "Saurabh.sharma@ins.ac.in" },
E5802: { name: "Neelam Bhagwat", email: "Neel.Bhagwat@ins.ac.in" },
E5801: { name: "Pooja Bandgar", email: "pooja.bandgar@ins.ac.in" },
E5808: { name: "Rajesh Dhebe", email: "rajesh.dhebe@ins.ac.in" },
E5810: { name: "Fatima Banu", email: "fatima.banu@ins.ac.in" },
E5811: { name: "Tanushree Das", email: "tanushree.das@indiranationalschool.ac.in" },
E5812: { name: "Rohan Jagtap", email: "rohan.jagtap@ins.ac.in" },
E5814: { name: "Seenul Kaparwan", email: "seenul.kaparwan@ins.ac.in" },
E5816: { name: "Rucha Ubale", email: "rucha.ubale@ins.ac.in" },
E5820: { name: "Protusha Mukherjee", email: "protusha.mukherjee@ins.ac.in" },
E5819: { name: "Shrikant Panda", email: "shrikant.panda@ins.ac.in" },
E5817: { name: "Alpa Patadia", email: "alpa.patadia@ins.ac.in" },
E5818: { name: "Kanchan Gongle", email: "Kanchan.gongle@ins.ac.in" },
E5813: { name: "Swati Khekare", email: "swati.khekare@ins.ac.in" },
E5822: { name: "Pinal Kotak", email: "pinal.kotak@ins.ac.in" },
E5824: { name: "Ashat Pujari", email: "Ashat.pujari@ins.ac.in" },
E5823: { name: "Suvarna Dawkhar", email: "suvarna.dawkhar@ins.ac.in" },
E5832: { name: "Darshana Parte", email: "darshana.parte@indiranationalschool.ac.in" },
E5834: { name: "Soujanya Jamajaggali", email: "soujanya.jamajaggali@ins.ac.in" },
E5829: { name: "Padmashri Pagar", email: "Padmashri.Pagar@ins.ac.in" },
E5791: { name: "Shubhangi Narayane", email: "shubhangi.narayane@ins.ac.in" },
E5804: { name: "Dhammapal Kamble", email: "Dhammapal.Kamble@ins.ac.in" },
E5839: { name: "Pradeep Kadam", email: "Pradeep.kadam@ins.in.ac" }, // Possibly invalid domain
E5860: { name: "Ram Panday", email: "Ram.panday@ins.ac.in" },
E5847: { name: "Sachin Talole", email: "sachin.talole@ins.ac.in" },
E5851: { name: "Sasmita Bhanja", email: "sasmita.bhanja@ins.ac.in" },
E5858: { name: "Vinita Mandlik", email: "Vinita.Mandlik@ins.ac.in" },
E5848: { name: "Tejas Mistry", email: "tejas.mestry@ins.ac.in" },
E5854: { name: "Ashwini Ekbote", email: "ashwini.ekbote@ins.ac.in" },
E5861: { name: "Siddharth Terdale", email: "siddharth.terdale@ins.ac.in" },
E5864: { name: "Shubhangee Gaikwad", email: "Shubhangee.Gaikwad@ins.ac.in" },
E5865: { name: "Juhi Dhall", email: "juhi.dhall@ins.ac.in" },
E5870: { name: "Shreya Mukherjee", email: "shreya.mukherjee@ins.ac.in" },
E5872: { name: "Karuna Rokade", email: "Karuna.Rokade@ins.ac.in" },
E5880: { name: "Pramathesh Karandikar", email: "pramathesh.karandikar@ins.ac.in" },
E5787: { name: "Abhijeet Kadam", email: "abhijeet.kadam@ins.ac.in" },
E5887: { name: "Mayuri Ghorpade", email: "Mayuri.Ghorpade@ins.ac.in" },
E5885: { name: "Swati Karande", email: "Swati.Karande@ins.ac.in" },
E5889: { name: "Poonam Shirsat", email: "Poonam.shirsat@ins.ac.in" },
E5892: { name: "Madhura Shukla", email: "Madhura.Shukla@ins.ac.in" },
E5895: { name: "Ganesh Singh", email: "ganesh.singh@ins.ac.in" },
E5896: { name: "Deepti Pandey", email: "deepti.pandey@ins.ac.in" },
E5897: { name: "Sonia Chawla", email: "Sonia.chawla@ins.ac.in" },
E5901: { name: "Apurva Solapure", email: "apurva.solapure@ins.ac.in" },
E5903: { name: "Vishakha Nemade", email: "vishakha.nemade@ins.ac.in" },
E5911: { name: "Puja Sangme", email: "info@indiranationalschool.ac.in" },
E5908: { name: "Swapnil Ranit", email: "swapnil.ranit@ins.ac.in" },
E5909: { name: "Mamta Mantri", email: "Mamta.Mantri@ins.ac.in" },
E5915: { name: "Kiran Tiwari", email: "Kiran.tiwari@ins.ac.in" },
E5898: { name: "Apurwa Chauhan", email: "Apurwa.chauhan@ins.ac.in" },
E5899: { name: "Varsha Ambegave", email: "Varsha.ambegave@ins.ac.in" },
E5907: { name: "Veena Yadav", email: "Veena.Yadav@ins.ac.in" },
E5917: { name: "Reena Brahmane", email: "reena.brahmane@ins.ac.in" },
E5912: { name: "Rashmi Bawankar", email: "rashmi.bawankar@ins.ac.in" },
E5906: { name: "Vidya Sankpal", email: "Vidya.sankpal@ins.ac.in" },
E5902: { name: "Pooja Chaudhary", email: "pooja.chaudhary@ins.ac.in" },
E5919: { name: "Abhishree More", email: "abhishree.more@ins.ac.in" },
E5918: { name: "Ashwin Mohite", email: "ashwin.mohite@ins.ac.in" },
E5883: { name: "Bhushan Sutar", email: "bhushan.sutar@ins.ac.in" },
E5597: { name: "Vishnu K. Kulkarni", email: "vishnu.kulkarni@indiraedu.com" },
E5598: { name: "Vaibhav Vasant Joshi", email: "vaibhav.joshi@ins.ac.in" },
1365: { name: "Shailesh Adinath Pawar", email: "shailesh.adinath@ins.ac.in" },
E5925: { name: "Santosh Itkare", email: "santosh.itkare@ins.ac.in" },
E5928: { name: "Nivedita Joshi", email: "nivedita.joshi@ins.com" }, // Possibly invalid domain
E5929: { name: "Shital Joshi", email: "Shital.Joshi@ins.ac.in" },
E5930: { name: "Raju Raut", email: "raju.raut@ins.ac.in" },
E5931: { name: "Vibha Mathur", email: "vibha.mathur@ins.ac.in" },
E5933: { name: "Mansi Pandhare", email: "mansi.pandhare@ins.ac.in" },
E5935: { name: "Swapnil Kadam", email: "swapnil.kadam@ins.ac.in" },
E5936: { name: "Pranita Patil", email: "pranita.patil@ins.ac.in" },
E5937: { name: "Swati Shinde", email: "Swati.Shinde@ins.ac.in" },
E5938: { name: "Sanket Surve", email: "sanket.surve@ins.ac.in" },
E5809: { name: "Salim Shaikh", email: "salim.shaikh@ins.ac.in" },
E5941: { name: "Yogita Jadhav", email: "Yogita.jadhav@ins.ac.in" },
E5942: { name: "Pooja Gidveer", email: "pooja.gidveer@ins.ac.in" },
E5943: { name: "Kavita Gaikwad", email: "kavita.gaikwad@ins.ac.in" },
E5944: { name: "Pratima Yadav", email: "pratima.yadav@ins.ac.in" },
E5945: { name: "Madhuri Jagadale", email: "madhuri.jagadale@ins.ac.in" },
E5946: { name: "Rajani Lakhyani", email: "rajani.lakhyani@ins.ac.in" },
E5951: { name: "Sunita Dhane", email: "sunita.dhane@ins.ac.in" },
E5955: { name: "Mayuri Jain", email: "mayuri.jain@ins.ac.in" },
E5956: { name: "Swapna Kadekar", email: "Swapna.kadekar@ins.ac.in" },
E5959: { name: "Komada Shinde", email: "komada.shinde@ins.ac.in" },
E5964: { name: "Jayashree Patil", email: "jayashree.patil@indiranationalschool.ac.in" },
E5965: { name: "Sumitkumar Gandhi", email: "sumitkumar.gandhi@ins.ac.in" },
E5966: { name: "Adinath Satpute", email: "adinath.satpute@ins.ac.in" },
E5852: { name: "Akash Shetty", email: "akash.shetty@ins.ac.in" },
E5762: { name: "Vinod Sathe", email: "vinod.sathe@ins.ac.in" },
240: { name: "Eazaz R. Bagwan", email: "eazaz.bagwan@indiraedu.com" },
E5967: { name: "Indira Choudhary", email: "indira.choudhary@ins.ac.in" },
E5968: { name: "Amol Lambhate", email: "amol.lambhate@ins.ac.in" },
E5973: { name: "Nimishaben Trivedi", email: "nimishaben.trivedi@ins.ac.in" },
E5975: { name: "Priyanka Sapkale", email: "priyanka.sapkale@ins.ac.in" },
E5976: { name: "Taru Shikha", email: "taru.shikha@ins.ac.in" },
E5890: { name: "Prathamesh Salunke", email: "prathamesh.salunke@ins.ac.in" },
E5978: { name: "Supriya Aglaye", email: "Supriya.m.todkar@gmail.com" },
E5979: { name: "Arti Badola", email: "Arti.badola@ins.ac.in" },
E5981: { name: "Eesha Deshpande", email: "eesha.deshpande@ins.ac.in" },
E5985: { name: "Vinay Waghmare", email: "vinay.waghmare@ins.ac.in" },
E5986: { name: "Tejal Mehta", email: "tejal.mehta@ins.ac.in" },
E5988: { name: "Debasmita Biswas", email: "debasmita.biswas@ins.ac.in" },
E5989: { name: "Angha Nalgirkar", email: "anagha.nalgirkar@ins.ac.in" },
E5990: { name: "Suraj Bhise", email: "suraj.bhise@ins.ac.in" },
328: { name: "Babasaheb Patil", email: "babasaheb.patil@ins.ac.in" },
E5991: { name: "Vaibhavkumar Dhundle", email: "Vaibhavkumar.dhundle@ins.ac.in" },
E5992: { name: "Reema Punjabi", email: "reema.punjabi@ins.ac.in" },
E5994: { name: "Harpreet Kaur", email: "harpreet.kaur@ins.ac.in" },
E5995: { name: "Sonam Lonkar", email: "sonam.lonkar@ins.ac.in" },
E5997: { name: "Swapna Kulkarni", email: "swapna.kulkarni@ins.ac.in" },
E5998: { name: "Devshree Patil", email: "devshree.patil@ins.ac.in" },
E5999: { name: "Shobhana Pardeshi", email: "shobhana.pardessi@ins.ac.in" },
E6000: { name: "Rupali Shirsat", email: "rupali.shirsat@ins.ac.in" },
E6001: { name: "Jayshri Deshpande", email: "jayshri.deshpande@ins.co.in" }, // Possibly incorrect domain
E6004: { name: "Kritika Alwani", email: "kritika.alwani@ins.ac.in" },
E6005: { name: "Jyotika Biswas", email: "jyotika.biswas@ins.ac.in" },
E6006: { name: "Niharika Singh", email: "niharika.singh@ins.ac.in" },
E6008: { name: "Archana Trisal", email: "archana.trisal@ins.ac.in" },
E6009: { name: "Sajed Shaikh", email: "sajed.shaikh@ins.ac.in" },
E6010: { name: "Dipali Koli", email: "dipali.koli@ins.ac.in" },
E6011: { name: "Chandrakant Sathe", email: "csathe01@gmail.com" },
E5984: { name: "Pallavi Patankar", email: "pallavi.patankar@INS.ac.in" },
E6012: { name: "Garima Sinha", email: "garima.sinha@ins.ac.in" },
E6013: { name: "Ranjita Yelmule", email: "ranjita.yelmule@ins.ac.in" },
E6014: { name: "Nidashireen Khan", email: "Nidashireen.khan@ins.ac.in" },
E6015: { name: "Pranali Waghmare", email: "Pranali.waghmare@ins.ac.in" },
E6016: { name: "Samina Pathan", email: "samina.Pathan@ins.ac.in" },
E6017: { name: "Lovita Dsouza", email: "lovita.dsouza@ins.ac.in" },
E6018: { name: "Savita Mishra", email: "savita.mishra@ins.ac.in" },
E6019: { name: "Pooja Patel", email: "POOJA.PATEL@INS.AC.IN" },
E6023: { name: "Payal Gulati", email: "payal.gulati@ins.ac.in" },
E6024: { name: "Chayanika Bhattacharjee", email: "chayanika.bhattacharjee@ins.ac.in" },
E6025: { name: "Niki Mishra", email: "0.@ins.ac.in" }, // Invalid email
E6026: { name: "Poonam Ingale", email: "poonam.ingale@ins.ac.in" },
E6027: { name: "Santosh Naik", email: "santosh.naik@ins.ac.in" },
E6028: { name: "Tuhin Goswami", email: "tuhin.goswami@ins.ac.in" },
E6029: { name: "Santilata Kisku", email: "" } // Missing email


  };

  if (coupons[code]) {
    return res.status(200).json({
      success: true,
      name: coupons[code].name,
      email: coupons[code].email,
    });
  } else {
    return res.status(404).json({
      success: false,
      message: "Invalid or expired coupon code",
    });
  }
}
